// The open UI/icon library (D-UILIB-1, D-UILIB-2): search it, and upload one file into the
// user's own Roblox account so an ImageLabel can show it.
//
// WHAT IS BUNDLED AND WHAT IS NOT. The worker cannot read the repository, so the compact index
// (pack, folder, file name) generated by packages/asset-library/build-manifest.mjs is compiled in.
// The bytes are not: they live in the D1 static store at /asset-library/<pack>/<path>, put there
// by packages/asset-library/upload.mjs, and are read through `serveStatic`, the same path the site
// gallery loads them from.
//
// WHICH ACCOUNT. The upload goes through creator-dashboard's `uploadAsset`, exactly as
// generate_model_external does: the customer's own connected key, into their own account, audited,
// with a Robux ceiling of 0. There is no path here to Apple's account.
import index from '../../../packages/asset-library/index.json';
import type { Env } from './env';
import { serveStatic } from './static';
import { getUploadStatus, uploadAsset, type CreatorEnv, type Result, type UploadedAsset, type UploadAssetInput } from './creator-dashboard';
import { describeRobloxCredential } from './user-credentials';

interface IndexPack { id: string; name: string; kind: string; license: string; attribution: string | null; folders: [string, string[]][] }
interface Entry { asset: string; pack: IndexPack; path: string; nameTokens: string[]; placeTokens: string[] }

export interface LibraryHit {
  /** `<pack id>/<path>` — the value upload_ui_asset takes. */
  asset: string;
  pack: string;
  packName: string;
  kind: string;
  license: string;
  attribution: string | null;
  /** Where the site serves the file, relative to the app origin. */
  url: string;
}

// JSON imports widen tuples to arrays, so the [folder, names] pairs need the cast through unknown.
const PACKS = (index as unknown as { packs: IndexPack[] }).packs;
const URL_PREFIX = '/asset-library/';

/** "fightJoy_09" -> fight, joy, 09; "DPAD_right" -> dpad, right; "style-1" -> style, 1. */
export function tokensOf(s: string): string[] {
  return s.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
}

let entries: Entry[] | null = null;
let byAsset: Map<string, Entry> | null = null;
function all(): Entry[] {
  if (entries) return entries;
  entries = [];
  for (const pack of PACKS) {
    const packTokens = [...tokensOf(pack.name), pack.kind];
    for (const [folder, names] of pack.folders) {
      const folderTokens = tokensOf(folder);
      for (const name of names) {
        const path = `${folder ? folder + '/' : ''}${name}.png`;
        entries.push({ asset: `${pack.id}/${path}`, pack, path, nameTokens: tokensOf(name), placeTokens: [...folderTokens, ...packTokens] });
      }
    }
  }
  byAsset = new Map(entries.map((e) => [e.asset, e]));
  return entries;
}

export function libraryFileCount(): number {
  return all().length;
}

function hitOf(e: Entry): LibraryHit {
  return {
    asset: e.asset, pack: e.pack.id, packName: e.pack.name, kind: e.pack.kind,
    license: e.pack.license, attribution: e.pack.attribution, url: URL_PREFIX + e.asset,
  };
}

/** Exact lookup: only a file the index names resolves, so a path cannot be made up. */
export function libraryAsset(asset: string): LibraryHit | null {
  all();
  const e = byAsset!.get(String(asset ?? ''));
  return e ? hitOf(e) : null;
}

function packSummaries() {
  return PACKS.map((p) => ({
    id: p.id, name: p.name, kind: p.kind, license: p.license, attribution: p.attribution,
    files: p.folders.reduce((n, [, names]) => n + names.length, 0),
    folders: p.folders.map(([f]) => f).filter(Boolean),
  }));
}

// A query word matches a file word when it is equal, or (for words of 3+ letters) one is a prefix
// of the other — so "hearts" finds heart and "arrow" finds arrows. Short words must be exact, or
// "a" would match everything that starts with an a.
function matches(q: string, t: string): boolean {
  if (q === t) return true;
  if (q.length < 3 || t.length < 3) return false;
  return t.startsWith(q) || q.startsWith(t);
}

export function findUiAssets(input: { query?: string; pack?: string; kind?: string; limit?: number }) {
  const limit = Math.max(1, Math.min(40, Math.floor(Number(input.limit) || 12)));
  const words = tokensOf(String(input.query ?? ''));
  const pool = all().filter((e) => (!input.pack || e.pack.id === input.pack) && (!input.kind || e.pack.kind === input.kind));
  if (!words.length) {
    return { total: pool.length, results: pool.slice(0, input.pack ? limit : 0).map(hitOf), packs: packSummaries() };
  }
  const scored: { e: Entry; hit: number; score: number }[] = [];
  for (const e of pool) {
    let hit = 0;
    let score = 0;
    for (const w of words) {
      if (e.nameTokens.some((t) => matches(w, t))) { hit++; score += 2; }
      else if (e.placeTokens.some((t) => matches(w, t))) { hit++; score += 1; }
    }
    // At least one word must be in the file's own name: a folder match alone would return every
    // file in "keyboard-mouse" for "keyboard".
    if (hit && e.nameTokens.some((t) => words.some((w) => matches(w, t)))) scored.push({ e, hit, score });
  }
  const best = scored.reduce((m, s) => Math.max(m, s.hit), 0);
  const kept = scored
    .filter((s) => s.hit === best)
    .sort((a, b) => b.score - a.score || a.e.nameTokens.length - b.e.nameTokens.length || a.e.asset.localeCompare(b.e.asset));
  return {
    total: kept.length,
    matchedWords: best,
    ofWords: words.length,
    results: kept.slice(0, limit).map((s) => hitOf(s.e)),
    ...(kept.length ? {} : { packs: packSummaries(), note: 'Nothing matched. Try one plain word (button, heart, arrow, coin, xbox), or browse a pack by passing only `pack`.' }),
  };
}

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

/** The stored bytes of a library file, or null when the store does not hold a PNG at that path. */
export async function readLibraryPng(
  env: Env,
  asset: string,
  serve: (env: Env, req: Request) => Promise<Response> = serveStatic,
): Promise<Uint8Array | null> {
  const res = await serve(env, new Request(`https://asset-library.internal${URL_PREFIX}${asset}`));
  // A missing path answers with the marketing 404 page, so the status is checked, not assumed.
  if (res.status !== 200 || !String(res.headers.get('content-type') ?? '').startsWith('image/png')) return null;
  const bytes = new Uint8Array(await res.arrayBuffer());
  return bytes.length > PNG_MAGIC.length && PNG_MAGIC.every((b, i) => bytes[i] === b) ? bytes : null;
}

export interface UploadDeps {
  describeCredential?: (env: CreatorEnv, userId: string) => Promise<{ scopes: readonly string[] } | null>;
  read?: (env: Env, asset: string) => Promise<Uint8Array | null>;
  upload?: (env: CreatorEnv, userId: string, input: UploadAssetInput) => Promise<Result<UploadedAsset>>;
  uploadStatus?: (env: CreatorEnv, userId: string, operationId: string) => Promise<Result<UploadedAsset>>;
  sleep?: (ms: number) => Promise<void>;
}

/** Roblox usually finishes a small Image in a few seconds; past this the caller gets the operation. */
const POLLS = 5;
const POLL_MS = 2_000;

export async function uploadLibraryAsset(
  env: Env,
  userId: string | undefined,
  input: { asset: string; displayName?: string },
  deps: UploadDeps = {},
): Promise<Record<string, unknown>> {
  const hit = libraryAsset(input.asset);
  if (!hit) return { error: 'That is not a library file. Call find_ui_asset and pass one of its `asset` values unchanged.' };
  if (!userId) return { error: 'upload_ui_asset needs a signed-in user: the image is created in their own Roblox account.' };
  const describe = deps.describeCredential ?? describeRobloxCredential;
  const cred = await describe(env as CreatorEnv, userId);
  if (!cred || !cred.scopes.includes('asset:write')) {
    return {
      error: 'Connect a Roblox Open Cloud key with the asset:write scope in Settings first — the image is created in your own Roblox account.',
      stage: 'roblox_key',
    };
  }
  const bytes = await (deps.read ?? ((e, a) => readLibraryPng(e, a)))(env, hit.asset);
  if (!bytes) return { error: 'The library file is not in the static store yet (packages/asset-library/upload.mjs has not been run). Nothing was uploaded.', stage: 'library' };

  const base = hit.asset.slice(hit.asset.lastIndexOf('/') + 1, -4).replace(/[_-]+/g, ' ');
  const name = (input.displayName ?? base).replace(/\s+/g, ' ').trim().slice(0, 50) || 'UI image';
  const up = await (deps.upload ?? ((e, u, i) => uploadAsset(e, u, i)))(env as CreatorEnv, userId, {
    file: bytes.slice().buffer,
    contentType: 'image/png',
    displayName: name,
    description: `${hit.packName} by Kenney (www.kenney.nl), ${hit.license}. Added by Apple.`,
    expectedPrice: 0,
  });
  if (!up.ok) return { error: up.error, stage: 'upload' };

  const status = deps.uploadStatus ?? ((e, u, id) => getUploadStatus(e, u, id));
  const sleep = deps.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
  let asset = up.data;
  for (let i = 0; i < POLLS && !asset.done; i++) {
    await sleep(POLL_MS);
    const s = await status(env as CreatorEnv, userId, asset.operationId);
    if (!s.ok) return { error: s.error, stage: 'upload' };
    asset = s.data;
  }
  const credit = { license: hit.license, attribution: hit.attribution, source: hit.packName };
  if (!asset.done || asset.assetId === null) {
    return {
      pending: true,
      operationId: asset.operationId,
      ...credit,
      note: 'Uploaded to the user\'s Roblox account; Roblox is still processing it, so there is no id yet. Do not set an Image property with a guessed id.',
    };
  }
  return {
    assetId: asset.assetId,
    image: `rbxassetid://${asset.assetId}`,
    use: `Set ImageLabel.Image or ImageButton.Image to "rbxassetid://${asset.assetId}" (set_properties or build_ui). Nothing was put in the place yet.`,
    ...credit,
  };
}
