// GENERATED by scripts/gen-blocks.mjs from packages/blocks. Do not edit.
/* eslint-disable */
import type { Block } from './block-types';
export const BLOCKS: Record<string, Block> = {
 "panel": {
  "block": {
   "id": "panel",
   "kind": "ui",
   "summary": "A titled window on the player's screen: header bar, dark body, rounded corners and outline.",
   "params": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "name": {
      "type": "string",
      "pattern": "^[A-Za-z][A-Za-z0-9_]{0,39}$",
      "default": "Panel",
      "description": "The ScreenGui's name in StarterGui"
     },
     "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 40,
      "default": "Menu",
      "description": "Text in the header"
     },
     "width": {
      "type": "integer",
      "minimum": 200,
      "maximum": 900,
      "default": 480,
      "description": "Pixels"
     },
     "height": {
      "type": "integer",
      "minimum": 160,
      "maximum": 700,
      "default": 360,
      "description": "Pixels"
     },
     "accent": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{6}$",
      "default": "#2b6cff",
      "description": "Header colour"
     }
    }
   },
   "provides": [],
   "depends": []
  },
  "recipe": {
   "steps": [
    {
     "id": "create",
     "op": "create_instances",
     "items": [
      {
       "className": "ScreenGui",
       "name": "{{name}}",
       "parent": "game.StarterGui",
       "children": [
        {
         "className": "Frame",
         "name": "Body",
         "props": {
          "AnchorPoint": {
           "t": "Vector2",
           "v": [
            0.5,
            0.5
           ]
          },
          "Position": {
           "t": "UDim2",
           "v": [
            0.5,
            0,
            0.5,
            0
           ]
          },
          "Size": {
           "t": "UDim2",
           "v": [
            0,
            "{{width}}",
            0,
            "{{height}}"
           ]
          },
          "BackgroundColor3": "#16213a",
          "BackgroundTransparency": 0.08,
          "BorderSizePixel": 0
         },
         "children": [
          {
           "className": "UICorner",
           "name": "Corner",
           "props": {
            "CornerRadius": {
             "t": "UDim",
             "v": [
              0,
              12
             ]
            }
           }
          },
          {
           "className": "UIStroke",
           "name": "Outline",
           "props": {
            "Thickness": 3,
            "Color": "#000000"
           }
          },
          {
           "className": "Frame",
           "name": "Header",
           "props": {
            "Size": {
             "t": "UDim2",
             "v": [
              1,
              0,
              0,
              48
             ]
            },
            "BackgroundColor3": "{{accent}}",
            "BorderSizePixel": 0
           },
           "children": [
            {
             "className": "UICorner",
             "name": "Corner",
             "props": {
              "CornerRadius": {
               "t": "UDim",
               "v": [
                0,
                12
               ]
              }
             }
            },
            {
             "className": "TextLabel",
             "name": "Title",
             "props": {
              "Size": {
               "t": "UDim2",
               "v": [
                1,
                -24,
                1,
                -12
               ]
              },
              "Position": {
               "t": "UDim2",
               "v": [
                0,
                12,
                0,
                6
               ]
              },
              "BackgroundTransparency": 1,
              "Text": "{{title}}",
              "TextColor3": "#ffffff",
              "TextScaled": true
             }
            }
           ]
          }
         ]
        }
       ]
      }
     ]
    }
   ]
  },
  "checks": [
   {
    "id": "body",
    "kind": "exists",
    "after": "create",
    "path": "game.StarterGui.{{name}}.Body",
    "describes": "the panel's body frame is in StarterGui"
   },
   {
    "id": "title",
    "kind": "prop",
    "after": "create",
    "path": "game.StarterGui.{{name}}.Body.Header.Title",
    "prop": "Text",
    "equals": "{{title}}",
    "param": "title",
    "describes": "the header shows the requested title"
   },
   {
    "id": "clean",
    "kind": "play_clean",
    "describes": "a play test with the panel has no errors"
   }
  ],
  "hint": "A plain window on screen: a coloured header with a title over a dark rounded body. Use it as the frame for a shop, inventory or settings screen; other UI blocks place their content inside its Body. `name` must be unique in StarterGui. Keep `title` short (a word or two). The size is in pixels for a 1280×720 screen.",
  "sources": {}
 }
};
