// Prompt → Hugging Face mesh → a Model asset in the CUSTOMER'S OWN Roblox account → asset id.
//
// WHICH ACCOUNT, AND WHY NOT OURS. The obvious wiring is Apple's own ROBLOX_API_KEY. It does not
// work and it is the one path this repository has already paid for:
//   1. Open Cloud creates a GLB as a `Model` (create.roblox.com/docs/cloud/guides/usage-assets:
//      "Model | .fbx, .gltf, .glb, .rbxm, .rbxmx | … Imports custom 3D models as a Model container
//      containing MeshPart objects"). A Model is not Open Use, and `insert_asset` loads with
//      InsertService:LoadAsset, which answered "User is not authorized" for an asset the Studio
//      user does not own (the ownership note of 2026-09-19 cited in apps/apple-plugin
//      Commands.luau). An asset in Apple's account would upload fine and then never insert.
//   2. Writing to Apple's own account is what put 299 permanent assets in the owner's personal
//      account (roblox-upload.ts, creator-dashboard.ts). roblox-upload's `preflight` refuses it
//      without ROBLOX_UPLOAD_AUTHORISED_FOR, and a Model cannot be deleted through the API either.
// So the upload goes through creator-dashboard's `uploadAsset`: the customer's own connected key,
// into their own account, audited, with a Robux ceiling of 0. The customer owns the Model, so
// LoadAsset in their Studio can load it.
//
// THE KEY IS CHECKED BEFORE ANYTHING IS SPENT. Hugging Face calls are capped at a handful a day;
// generating a mesh for somebody who cannot receive it would burn one for nothing.
import { generate3d, type HfEnv, type HfOptions } from './hf';
import {
  getUploadStatus,
  uploadAsset,
  type CreatorEnv,
  type Result,
  type UploadedAsset,
  type UploadAssetInput,
} from './creator-dashboard';
import { describeRobloxCredential } from './user-credentials';
import { startModelUploadFollowUp, type ModelUploadParams } from './model-upload';

export interface ModelPipelineDeps extends HfOptions {
  describeCredential?: (env: CreatorEnv, userId: string) => Promise<{ scopes: readonly string[] } | null>;
  upload?: (env: CreatorEnv, userId: string, input: UploadAssetInput) => Promise<Result<UploadedAsset>>;
  uploadStatus?: (env: CreatorEnv, userId: string, operationId: string) => Promise<Result<UploadedAsset>>;
  followUp?: (env: ModelPipelineEnv, params: ModelUploadParams) => Promise<boolean>;
}

export type ModelPipelineEnv = HfEnv & CreatorEnv & { MODEL_UPLOAD_WORKFLOW?: Workflow<ModelUploadParams> };

export type ModelPipelineResult =
  | {
    ok: true;
    /** Null while Roblox is still processing; `operationId` is then the handle to ask again. */
    assetId: number | null;
    operationId: string;
    done: boolean;
    /** True when a Workflow is now watching the still-processing upload and will notify the user. */
    followUp: boolean;
    triangles: number;
    model: string;
  }
  | { ok: false; stage: 'roblox_key' | 'generate' | 'upload'; reason?: string; message: string };

/** Roblox usually finishes a small Model in a few seconds; past this the caller gets the operation. */
const POLLS = 5;
const POLL_MS = 2_000;

export async function generateModelForRoblox(
  env: ModelPipelineEnv,
  userId: string,
  input: { prompt: string; displayName?: string; projectId?: string | null },
  deps: ModelPipelineDeps = {},
): Promise<ModelPipelineResult> {
  const describe = deps.describeCredential ?? describeRobloxCredential;
  const upload = deps.upload ?? ((e, u, i) => uploadAsset(e, u, i));
  const status = deps.uploadStatus ?? ((e, u, id) => getUploadStatus(e, u, id));
  const sleep = deps.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));

  const cred = await describe(env, userId);
  if (!cred || !cred.scopes.includes('asset:write')) {
    return {
      ok: false,
      stage: 'roblox_key',
      message: 'Connect a Roblox Open Cloud key with the asset:write scope in Settings first — the model is created in your own Roblox account so your Studio can insert it.',
    };
  }

  const mesh = await generate3d(env, { prompt: input.prompt }, deps);
  if (!mesh.ok) return { ok: false, stage: 'generate', reason: mesh.reason, message: mesh.message };

  const name = (input.displayName ?? input.prompt).replace(/\s+/g, ' ').trim().slice(0, 50) || 'Generated model';
  const up = await upload(env, userId, {
    file: mesh.glb.slice().buffer,
    contentType: 'model/gltf-binary',
    displayName: name,
    description: `Generated by Apple with ${mesh.model} (${mesh.triangles} triangles).`,
    type: 'Model',
    expectedPrice: 0,
  });
  if (!up.ok) return { ok: false, stage: 'upload', message: up.error };

  let asset = up.data;
  for (let i = 0; i < POLLS && !asset.done; i++) {
    await sleep(POLL_MS);
    const s = await status(env, userId, asset.operationId);
    if (!s.ok) return { ok: false, stage: 'upload', message: s.error };
    asset = s.data;
  }
  // Roblox is slower than the tool can wait: hand the operation to a durable follow-up that keeps
  // asking and tells the user the asset id when it lands (model-upload-workflow.ts).
  const followUp = asset.done
    ? false
    : await (deps.followUp ?? startModelUploadFollowUp)(env, {
      userId,
      operationId: asset.operationId,
      projectId: input.projectId ?? null,
      displayName: name,
    });
  return {
    ok: true,
    assetId: asset.done ? asset.assetId : null,
    operationId: asset.operationId,
    done: asset.done,
    followUp,
    triangles: mesh.triangles,
    model: mesh.model,
  };
}
