// GENERATED by scripts/curate-templates.mjs. Do not edit by hand — re-run the curator.
//
// Every row here survived: a named-rule exclusion sweep for exploits, macros, account abuse and
// client tampering; a licence that permits reuse; and a file tree read over the network in which
// a Luau path is NAMED after the mechanic it is cited for. The cited files were then read and
// contain no Roblox call that has been removed.
//
// NO CODE IS VENDORED. This is a bibliography. The licence and the author travel with every row
// because the agent is meant to READ the implementation and write its own, and a customer's game
// must never contain someone else's GPL Luau.
// Curated 2026-09-15 from a harvest of 3017 repositories; 131 survived.

export interface MechanicCitation {
  repo: string;
  owner: string;
  url: string;
  stars: number;
  licence: string;
  licenceUrl: string | null;
  /** The mechanic, and the path in that repository whose NAME is the evidence for it. */
  mechanics: { id: string; file: string }[];
  /** 'clean' = the cited files were read and hold no removed or deprecated call. */
  currency: string;
  /** Deprecated calls found in the cited files, named, so the agent does not copy them forward. */
  deprecated: string[];
}

export const MECHANIC_CITATIONS: readonly MechanicCitation[] = [
 {
  "repo": "Quenty/NevermoreEngine",
  "owner": "Quenty",
  "url": "https://github.com/Quenty/NevermoreEngine",
  "stars": 610,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Quenty/NevermoreEngine#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "src/access/src/Client/Commands/AccessCommandServiceClient.lua"
   },
   {
    "id": "customization",
    "file": "src/avatareditorutils/src/Client/AvatarEditorInventory.lua"
   },
   {
    "id": "inventory",
    "file": "src/avatareditorutils/src/Client/AvatarEditorInventoryServiceClient.lua"
   },
   {
    "id": "persistence",
    "file": "src/datastore/src/Client/Cmdr/DataStoreCmdrServiceClient.lua"
   },
   {
    "id": "dialogue",
    "file": "src/inputkeymaputils/src/Shared/ProximityPromptInputUtils.lua"
   },
   {
    "id": "monetization",
    "file": "src/marketplaceutils/src/Shared/MarketplaceServiceCache.lua"
   },
   {
    "id": "camera",
    "file": "src/mouseshiftlockservice/src/Client/MouseShiftLockService.lua"
   },
   {
    "id": "path_waypoints",
    "file": "src/pathfindingutils/src/Shared/PathfindingUtils.lua"
   },
   {
    "id": "ragdoll",
    "file": "src/ragdoll/src/Client/Classes/RagdollCameraShakeClient.lua"
   },
   {
    "id": "remotes",
    "file": "src/remotefunctionutils/src/Shared/RemoteFunctionUtils.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "evaera/Cmdr",
  "owner": "evaera",
  "url": "https://github.com/evaera/Cmdr",
  "stars": 527,
  "licence": "MIT",
  "licenceUrl": "https://github.com/evaera/Cmdr#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "Cmdr/BuiltInCommands/Admin/announce.luau"
   },
   {
    "id": "persistence",
    "file": "Cmdr/CmdrClient/Shared/BuiltInGuards/IsDataStoreAvailable.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Epix-Incorporated/Adonis",
  "owner": "Epix-Incorporated",
  "url": "https://github.com/Epix-Incorporated/Adonis",
  "stars": 494,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Epix-Incorporated/Adonis#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "MainModule/Client/Plugins/Anti_Cheat.luau"
   },
   {
    "id": "admin_commands",
    "file": "MainModule/Client/UI/Modern/Components/AdonisModernComponents/AdonisModernComponents.storybook.luau"
   },
   {
    "id": "camera",
    "file": "MainModule/Server/Dependencies/Assets/Freecam/Freecam.client.lua"
   },
   {
    "id": "pets",
    "file": "MainModule/Server/Dependencies/Assets/HatPets.server.luau"
   },
   {
    "id": "persistence",
    "file": "MainModule/Server/Dependencies/DataStoreService/MockDataStoreService/init.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()",
   "wait() is deprecated — use task.wait()"
  ]
 },
 {
  "repo": "paradoxum-games/lyra",
  "owner": "paradoxum-games",
  "url": "https://github.com/paradoxum-games/lyra",
  "stars": 152,
  "licence": "MIT",
  "licenceUrl": "https://github.com/paradoxum-games/lyra#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/dataStoreRetry.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "lisphm/A-Chassis",
  "owner": "lisphm",
  "url": "https://github.com/lisphm/A-Chassis",
  "stars": 101,
  "licence": "MPL-2.0",
  "licenceUrl": "https://github.com/lisphm/A-Chassis#license",
  "mechanics": [
   {
    "id": "vehicles",
    "file": "Scripts/A-Chassis Tune.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ahmicy/simplepath",
  "owner": "ahmicy",
  "url": "https://github.com/ahmicy/simplepath",
  "stars": 70,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ahmicy/simplepath#license",
  "mechanics": [
   {
    "id": "path_waypoints",
    "file": "src/SimplePath.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "real2nix/mineblox",
  "owner": "real2nix",
  "url": "https://github.com/real2nix/mineblox",
  "stars": 68,
  "licence": "MIT",
  "licenceUrl": "https://github.com/real2nix/mineblox#license",
  "mechanics": [
   {
    "id": "procedural_terrain",
    "file": "src/StarterPlayer/ParallelScripts/TerrainLoaderParallel.client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "pinehappi/DataDelve",
  "owner": "pinehappi",
  "url": "https://github.com/pinehappi/DataDelve",
  "stars": 48,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/pinehappi/DataDelve#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/UI/Views/OrderedDataStoreView/OrderedDataStoreKeyStyleState.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/UI/Views/OrderedDataStoreView/OrderedDataStoreKeyStyleState.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "kohls-admin/kohls-admin",
  "owner": "kohls-admin",
  "url": "https://github.com/kohls-admin/kohls-admin",
  "stars": 48,
  "licence": "MIT",
  "licenceUrl": "https://github.com/kohls-admin/kohls-admin#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/Shared/Data/Store.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "notreux/UpsideEngine",
  "owner": "notreux",
  "url": "https://github.com/notreux/UpsideEngine",
  "stars": 47,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/notreux/UpsideEngine#license",
  "mechanics": [
   {
    "id": "dialogue",
    "file": "src/Classes/Public/ProximityPrompt.spec2D.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "gaymeowing/luauberries",
  "owner": "gaymeowing",
  "url": "https://github.com/gaymeowing/luauberries",
  "stars": 37,
  "licence": "MIT",
  "licenceUrl": "https://github.com/gaymeowing/luauberries#license",
  "mechanics": [
   {
    "id": "currency",
    "file": "libs/leaderstats/init.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "loneka/avalog",
  "owner": "loneka",
  "url": "https://github.com/loneka/avalog",
  "stars": 37,
  "licence": "MPL-2.0",
  "licenceUrl": "https://github.com/loneka/avalog#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/Server/PlayerDataStorage/DataValidater.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "rduoDevs/CameraService",
  "owner": "rduoDevs",
  "url": "https://github.com/rduoDevs/CameraService",
  "stars": 36,
  "licence": "MIT",
  "licenceUrl": "https://github.com/rduoDevs/CameraService#license",
  "mechanics": [
   {
    "id": "camera",
    "file": "CameraService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "MaximumADHD/Roblox-Utils",
  "owner": "MaximumADHD",
  "url": "https://github.com/MaximumADHD/Roblox-Utils",
  "stars": 35,
  "licence": "MIT",
  "licenceUrl": "https://github.com/MaximumADHD/Roblox-Utils#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "Modules/Network/Remotes.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "rayanux/roblox-movement-anticheat",
  "owner": "rayanux",
  "url": "https://github.com/rayanux/roblox-movement-anticheat",
  "stars": 27,
  "licence": "MIT",
  "licenceUrl": "https://github.com/rayanux/roblox-movement-anticheat#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/ReplicatedStorage/App/Networking/MovementRemotes.lua"
   },
   {
    "id": "anticheat",
    "file": "src/ReplicatedStorage/App/Utilities/RateLimiter.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "PossiblePanda/QueryAuth",
  "owner": "PossiblePanda",
  "url": "https://github.com/PossiblePanda/QueryAuth",
  "stars": 25,
  "licence": "MIT",
  "licenceUrl": "https://github.com/PossiblePanda/QueryAuth#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "lib/DefaultAuthConditions/Gamepass.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "zblox164/PlacementService",
  "owner": "zblox164",
  "url": "https://github.com/zblox164/PlacementService",
  "stars": 21,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/zblox164/PlacementService#license",
  "mechanics": [
   {
    "id": "placement",
    "file": "PlacementService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "prooheckcp/RoQuest",
  "owner": "prooheckcp",
  "url": "https://github.com/prooheckcp/RoQuest",
  "stars": 20,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/prooheckcp/RoQuest#license",
  "mechanics": [
   {
    "id": "quests",
    "file": "RoQuest/Client/init.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "administer-org/administer",
  "owner": "administer-org",
  "url": "https://github.com/administer-org/administer",
  "stars": 20,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/administer-org/administer#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "src/ServerScriptService/Administer/Resources/AdministerMainPanel/UIScripts/Spinner_NewAdmin.client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "encodedlux/sling",
  "owner": "encodedlux",
  "url": "https://github.com/encodedlux/sling",
  "stars": 19,
  "licence": "MIT",
  "licenceUrl": "https://github.com/encodedlux/sling#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/api/setHotbar.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "loneka/moonlets",
  "owner": "loneka",
  "url": "https://github.com/loneka/moonlets",
  "stars": 19,
  "licence": "MIT",
  "licenceUrl": "https://github.com/loneka/moonlets#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "modules/GamepassHandler/bundler.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "modules/Leaderboard/bundler.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "AnotherSubatomo/RbxShader",
  "owner": "AnotherSubatomo",
  "url": "https://github.com/AnotherSubatomo/RbxShader",
  "stars": 17,
  "licence": "MIT",
  "licenceUrl": "https://github.com/AnotherSubatomo/RbxShader#license",
  "mechanics": [
   {
    "id": "procedural_terrain",
    "file": "shaders/BasicVoxelTunnel.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Asiandayboy/InventoryMaker",
  "owner": "Asiandayboy",
  "url": "https://github.com/Asiandayboy/InventoryMaker",
  "stars": 16,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Asiandayboy/InventoryMaker#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/client_modules/IMC/IMHotbar.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Iron-Stag-Games/Pronghorn",
  "owner": "Iron-Stag-Games",
  "url": "https://github.com/Iron-Stag-Games/Pronghorn",
  "stars": 15,
  "licence": "LGPL-2.1",
  "licenceUrl": "https://github.com/Iron-Stag-Games/Pronghorn#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "Pronghorn/Remotes/TypeChecker.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "nonlooped/roblox-suite",
  "owner": "nonlooped",
  "url": "https://github.com/nonlooped/roblox-suite",
  "stars": 14,
  "licence": "MIT",
  "licenceUrl": "https://github.com/nonlooped/roblox-suite#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "roblox-datastores/scripts/BudgetMonitor.lua"
   },
   {
    "id": "monetization",
    "file": "roblox-gamepasses/scripts/PassPurchaseHelper.lua"
   },
   {
    "id": "anticheat",
    "file": "roblox-networking/scripts/RateLimiter.lua"
   },
   {
    "id": "path_waypoints",
    "file": "roblox-npcs/scripts/PathfindingUtility.lua"
   },
   {
    "id": "vehicles",
    "file": "roblox-physics/scripts/Suspension.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Zyn-ic/Stoway",
  "owner": "Zyn-ic",
  "url": "https://github.com/Zyn-ic/Stoway",
  "stars": 13,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Zyn-ic/Stoway#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/client/StowayClientv1_2/NetworkFunctions/NetworkHandler.luau"
   },
   {
    "id": "inventory",
    "file": "src/client/StowayClientv1_2/Operations/InventoryController.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "XoifaiI/Ledger",
  "owner": "XoifaiI",
  "url": "https://github.com/XoifaiI/Ledger",
  "stars": 13,
  "licence": "MIT",
  "licenceUrl": "https://github.com/XoifaiI/Ledger#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/Core/Constants/Datastore.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "DialogueMaker/plugin",
  "owner": "DialogueMaker",
  "url": "https://github.com/DialogueMaker/plugin",
  "stars": 13,
  "licence": "MPL-2.0",
  "licenceUrl": "https://github.com/DialogueMaker/plugin#license",
  "mechanics": [
   {
    "id": "dialogue",
    "file": "src/DialogueEditor/hooks/useDialogueScriptType.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "LeoStormer/ragdoll-system",
  "owner": "LeoStormer",
  "url": "https://github.com/LeoStormer/ragdoll-system",
  "stars": 13,
  "licence": "MIT",
  "licenceUrl": "https://github.com/LeoStormer/ragdoll-system#license",
  "mechanics": [
   {
    "id": "ragdoll",
    "file": "lib/RagdollController/init.server.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "arxk/Leaderboard",
  "owner": "arxk",
  "url": "https://github.com/arxk/Leaderboard",
  "stars": 13,
  "licence": "MIT",
  "licenceUrl": "https://github.com/arxk/Leaderboard#license",
  "mechanics": [
   {
    "id": "leaderboard_global",
    "file": "lib/Leaderboard/Board/Manifest.luau"
   },
   {
    "id": "rebirth",
    "file": "testing/ServerExamples/RebirthsLeaderboards.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "rorooms/rorooms",
  "owner": "rorooms",
  "url": "https://github.com/rorooms/rorooms",
  "stars": 13,
  "licence": "MPL-2.0",
  "licenceUrl": "https://github.com/rorooms/rorooms#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "ext_packages/GamepassesHandler.luau"
   },
   {
    "id": "currency",
    "file": "ext_packages/LeaderStats.luau"
   },
   {
    "id": "persistence",
    "file": "src/Client/Profiles/ProfilesController.luau"
   },
   {
    "id": "zones",
    "file": "src/Server/Components/LockedZoneComponent.luau"
   },
   {
    "id": "upgrades",
    "file": "src/Server/PlayerDataStore/LevelingService.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Redon-Tech/Emergency-Vehicle-Creator",
  "owner": "Redon-Tech",
  "url": "https://github.com/Redon-Tech/Emergency-Vehicle-Creator",
  "stars": 12,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Redon-Tech/Emergency-Vehicle-Creator#license",
  "mechanics": [
   {
    "id": "vehicles",
    "file": "src/chassisHandler.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "luvmad/VANITY-ANTICHEAT-Discontinued-",
  "owner": "luvmad",
  "url": "https://github.com/luvmad/VANITY-ANTICHEAT-Discontinued-",
  "stars": 11,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/luvmad/VANITY-ANTICHEAT-Discontinued-#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "client/VANITY-ANTICHEAT-ADMIN-PANEL.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "vantoanvh/LuauDOOM",
  "owner": "vantoanvh",
  "url": "https://github.com/vantoanvh/LuauDOOM",
  "stars": 10,
  "licence": "GPL-2.0",
  "licenceUrl": "https://github.com/vantoanvh/LuauDOOM#license",
  "mechanics": [
   {
    "id": "round_system",
    "file": "LuauDOOM/Interface/Intermission.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Brawldude2/RagdollService",
  "owner": "Brawldude2",
  "url": "https://github.com/Brawldude2/RagdollService",
  "stars": 7,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Brawldude2/RagdollService#license",
  "mechanics": [
   {
    "id": "ragdoll",
    "file": "src/RagdollBuilder.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "robertocharretonkaplun/POORobloxStudio",
  "owner": "robertocharretonkaplun",
  "url": "https://github.com/robertocharretonkaplun/POORobloxStudio",
  "stars": 6,
  "licence": "MIT",
  "licenceUrl": "https://github.com/robertocharretonkaplun/POORobloxStudio#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "ReplicatedStorage/SOLID/DIP/MS_RepositorioDataStore.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "s-wick/FORTUNE_Products",
  "owner": "s-wick",
  "url": "https://github.com/s-wick/FORTUNE_Products",
  "stars": 6,
  "licence": "MIT",
  "licenceUrl": "https://github.com/s-wick/FORTUNE_Products#license",
  "mechanics": [
   {
    "id": "vehicles",
    "file": "VehicleSpawner/src/ReplicatedStorage/CarSpawnerConfig.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ryanlua/rojo-showcase-template",
  "owner": "ryanlua",
  "url": "https://github.com/ryanlua/rojo-showcase-template",
  "stars": 5,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/ryanlua/rojo-showcase-template#license",
  "mechanics": [
   {
    "id": "dialogue",
    "file": "src/client/ContextProximityPrompt.client.luau"
   },
   {
    "id": "badges",
    "file": "src/server/JoinBadge.server.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "NirlekaPlay/asymptote-engine",
  "owner": "NirlekaPlay",
  "url": "https://github.com/NirlekaPlay/asymptote-engine",
  "stars": 5,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/NirlekaPlay/asymptote-engine#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "src/client/PlayerScripts/GunSystemFramework.client.lua"
   },
   {
    "id": "camera",
    "file": "src/client/PlayerScripts/modules/camera/CameraManager.lua"
   },
   {
    "id": "admin_commands",
    "file": "src/client/PlayerScripts/modules/commands/CommandsClientPacketListener.lua"
   },
   {
    "id": "dialogue",
    "file": "src/client/PlayerScripts/modules/ui/dialogue/DialogueController.lua"
   },
   {
    "id": "path_waypoints",
    "file": "src/server/ai/behavior/pathfinding/PlayerPosTracker.lua"
   },
   {
    "id": "ragdoll",
    "file": "src/server/ai/control/RagdollControl.lua"
   },
   {
    "id": "quests",
    "file": "src/server/world/level/mission/MissionManager.lua"
   },
   {
    "id": "procedural_terrain",
    "file": "src/server/world/level/voxel/Heap.lua"
   },
   {
    "id": "customization",
    "file": "src/shared/network/payloads/CharacterAppearancePayload.lua"
   },
   {
    "id": "remotes",
    "file": "src/shared/network/remotes/GunSysTypedRemotes.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "CavefulGames/dalbit-polyfill",
  "owner": "CavefulGames",
  "url": "https://github.com/CavefulGames/dalbit-polyfill",
  "stars": 4,
  "licence": "MIT",
  "licenceUrl": "https://github.com/CavefulGames/dalbit-polyfill#license",
  "mechanics": [
   {
    "id": "procedural_terrain",
    "file": "src/perlin.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "dig1t/roblox-modules",
  "owner": "dig1t",
  "url": "https://github.com/dig1t/roblox-modules",
  "stars": 4,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/dig1t/roblox-modules#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "src/GamePass/init.luau"
   },
   {
    "id": "ragdoll",
    "file": "src/Ragdoll/init.luau"
   },
   {
    "id": "weapons",
    "file": "src/Weapon/WeaponClient.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "knownasrazi/roblox-tycoon-clean",
  "owner": "knownasrazi",
  "url": "https://github.com/knownasrazi/roblox-tycoon-clean",
  "stars": 4,
  "licence": "MIT",
  "licenceUrl": "https://github.com/knownasrazi/roblox-tycoon-clean#license",
  "mechanics": [
   {
    "id": "plots",
    "file": "src/PlotService.lua"
   },
   {
    "id": "dropper",
    "file": "src/TycoonService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "evilbocchi/bocchi-upgrade-tree",
  "owner": "evilbocchi",
  "url": "https://github.com/evilbocchi/bocchi-upgrade-tree",
  "stars": 4,
  "licence": "MIT",
  "licenceUrl": "https://github.com/evilbocchi/bocchi-upgrade-tree#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "src/ReplicatedStorage/Cmdr/Commands/BuyButton.luau"
   },
   {
    "id": "currency",
    "file": "src/ServerScriptService/Controllers/CurrencyController.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/ServerScriptService/Controllers/LeaderboardController.luau"
   },
   {
    "id": "dropper",
    "file": "src/Workspace/Bocchiria/Map/JToH Kit v5.5/ClientSidedObjects/Conveyor/Attachment/Beam/ClientObjectScript.luau"
   },
   {
    "id": "towers",
    "file": "src/Workspace/Bocchiria/Map/JToH Kit v5.5/ClientSidedObjects/Turret/Turret/ClientObjectScript.luau"
   },
   {
    "id": "weapons",
    "file": "src/Workspace/Buttons/B9/Hitbox/Script.server.luau"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()",
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation"
  ]
 },
 {
  "repo": "evxryyy/Rbxenv",
  "owner": "evxryyy",
  "url": "https://github.com/evxryyy/Rbxenv",
  "stars": 3,
  "licence": "MIT",
  "licenceUrl": "https://github.com/evxryyy/Rbxenv#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "Nexus (OLD/default/Client/RemoteEvent/init.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "mendezingridvanessa85-blip/r6-fist-combat-system",
  "owner": "mendezingridvanessa85-blip",
  "url": "https://github.com/mendezingridvanessa85-blip/r6-fist-combat-system",
  "stars": 3,
  "licence": "MIT",
  "licenceUrl": "https://github.com/mendezingridvanessa85-blip/r6-fist-combat-system#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "src/ReplicatedStorage/FistCombat/Modules/CombatConfig.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "maddoxbouldin/roblox-runtime-terrain",
  "owner": "maddoxbouldin",
  "url": "https://github.com/maddoxbouldin/roblox-runtime-terrain",
  "stars": 3,
  "licence": "CC0-1.0",
  "licenceUrl": "https://github.com/maddoxbouldin/roblox-runtime-terrain#license",
  "mechanics": [
   {
    "id": "procedural_terrain",
    "file": "Terrain/Config.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Ecliptorhizes/Hooksystem",
  "owner": "Ecliptorhizes",
  "url": "https://github.com/Ecliptorhizes/Hooksystem",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Ecliptorhizes/Hooksystem#license",
  "mechanics": [
   {
    "id": "round_system",
    "file": "src/server/services/LobbyService.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ZyCrypticz/CoreProfileX",
  "owner": "ZyCrypticz",
  "url": "https://github.com/ZyCrypticz/CoreProfileX",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ZyCrypticz/CoreProfileX#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "ProfileLoader.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "iqbaleff214/roblox-hikayat-pemuda",
  "owner": "iqbaleff214",
  "url": "https://github.com/iqbaleff214/roblox-hikayat-pemuda",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/iqbaleff214/roblox-hikayat-pemuda#license",
  "mechanics": [
   {
    "id": "badges",
    "file": "src/client/Controllers/AchievementController.lua"
   },
   {
    "id": "weapons",
    "file": "src/client/Controllers/CombatController.lua"
   },
   {
    "id": "inventory",
    "file": "src/client/Controllers/HotbarController.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "src/client/Controllers/LeaderboardController.lua"
   },
   {
    "id": "daily_reward",
    "file": "src/client/Controllers/LoginStreakController.lua"
   },
   {
    "id": "quests",
    "file": "src/client/Controllers/QuestController.lua"
   },
   {
    "id": "shop",
    "file": "src/client/Controllers/ShopController.lua"
   },
   {
    "id": "zones",
    "file": "src/client/Controllers/ZoneController.lua"
   },
   {
    "id": "currency",
    "file": "src/server/Services/CurrencyService.lua"
   },
   {
    "id": "enemies",
    "file": "src/server/Services/NPCService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "royhanantariksaaa/flite-rbx",
  "owner": "royhanantariksaaa",
  "url": "https://github.com/royhanantariksaaa/flite-rbx",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/royhanantariksaaa/flite-rbx#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "Server/DataStoreInbox.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "OverDsh/dash-framework",
  "owner": "OverDsh",
  "url": "https://github.com/OverDsh/dash-framework",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/OverDsh/dash-framework#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/Network/Client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "TemujinCalidius/SurvivorCore",
  "owner": "TemujinCalidius",
  "url": "https://github.com/TemujinCalidius/SurvivorCore",
  "stars": 2,
  "licence": "MIT",
  "licenceUrl": "https://github.com/TemujinCalidius/SurvivorCore#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "plugin/BuildAdminUi.luau"
   },
   {
    "id": "badges",
    "file": "src/client/AchievementsUi.luau"
   },
   {
    "id": "inventory",
    "file": "src/client/Hotbar.luau"
   },
   {
    "id": "quests",
    "file": "src/client/QuestsUi.luau"
   },
   {
    "id": "weapons",
    "file": "src/shared/CombatConfig.luau"
   },
   {
    "id": "enemies",
    "file": "src/shared/MobsConfig.luau"
   },
   {
    "id": "remotes",
    "file": "src/shared/Remotes.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "thebardchat/angel-cloud-roblox",
  "owner": "thebardchat",
  "url": "https://github.com/thebardchat/angel-cloud-roblox",
  "stars": 1,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/thebardchat/angel-cloud-roblox#license",
  "mechanics": [
   {
    "id": "camera",
    "file": "src/client/Controllers/CameraController.lua"
   },
   {
    "id": "tutorial",
    "file": "src/client/Controllers/TutorialController.lua"
   },
   {
    "id": "badges",
    "file": "src/server/Services/BadgeHandlerService.lua"
   },
   {
    "id": "daily_reward",
    "file": "src/server/Services/DailyRewardService.lua"
   },
   {
    "id": "pets",
    "file": "src/server/Services/EasterEggService.lua"
   },
   {
    "id": "admin_commands",
    "file": "src/server/Services/ModerationService.lua"
   },
   {
    "id": "enemies",
    "file": "src/server/Services/NPCService.lua"
   },
   {
    "id": "quests",
    "file": "src/server/Services/QuestService.lua"
   },
   {
    "id": "shop",
    "file": "src/server/Services/ShopService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ShiroKSH/skills",
  "owner": "ShiroKSH",
  "url": "https://github.com/ShiroKSH/skills",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ShiroKSH/skills#license",
  "mechanics": [
   {
    "id": "procedural_terrain",
    "file": "plugin/src/Bridge/TerrainGenerator.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "SBdevz/Chaos-Obby",
  "owner": "SBdevz",
  "url": "https://github.com/SBdevz/Chaos-Obby",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/SBdevz/Chaos-Obby#license",
  "mechanics": [
   {
    "id": "checkpoints",
    "file": "Scripts/Server Scripts/Checkpoints.legacy.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ReRand/ACE-ULTRA_old",
  "owner": "ReRand",
  "url": "https://github.com/ReRand/ACE-ULTRA_old",
  "stars": 1,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/ReRand/ACE-ULTRA_old#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "arc/Modules/Revared/Modules/GlobalSide/Functions/Damage/ClientSide.client.lua"
   },
   {
    "id": "persistence",
    "file": "arc/Modules/Revared/Modules/LocalDataStores/Runner.server.lua"
   },
   {
    "id": "ragdoll",
    "file": "arc/src/StarterPlayer/StarterCharacterScripts/Mechanics/RagdollÃ©.client.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "arc/src/StarterPlayer/StarterCharacterScripts/Modules/PlayerLeaderboard.lua"
   },
   {
    "id": "shop",
    "file": "arc/src/StarterPlayer/StarterPlayerScripts/Shop.client.lua"
   },
   {
    "id": "admin_commands",
    "file": "arc/src/Workspace/Adonis_Loader/Loader/Loader.server.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "vallkyrionxd-ops/RoB-Kit",
  "owner": "vallkyrionxd-ops",
  "url": "https://github.com/vallkyrionxd-ops/RoB-Kit",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/vallkyrionxd-ops/RoB-Kit#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "scripts/admin/AdminCommands.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "scripts/core/LeaderboardSetup.lua"
   },
   {
    "id": "round_system",
    "file": "scripts/core/RoundSystem.lua"
   },
   {
    "id": "shop",
    "file": "scripts/core/ShopSystem.lua"
   },
   {
    "id": "dialogue",
    "file": "scripts/npc/DialogueNPC.lua"
   },
   {
    "id": "checkpoints",
    "file": "scripts/obby/BouncePad.lua"
   },
   {
    "id": "dropper",
    "file": "scripts/obby/ConveyorBrick.lua"
   },
   {
    "id": "killbricks",
    "file": "scripts/obby/KillBrick.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "LILRINO71/power-punch-simulator",
  "owner": "LILRINO71",
  "url": "https://github.com/LILRINO71/power-punch-simulator",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/LILRINO71/power-punch-simulator#license",
  "mechanics": [
   {
    "id": "rebirth",
    "file": "src/client/RebirthUi.luau"
   },
   {
    "id": "shop",
    "file": "src/client/ShopUi.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/server/GlobalLeaderboard.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "luciela77/Roblox-RPG-Skills",
  "owner": "luciela77",
  "url": "https://github.com/luciela77/Roblox-RPG-Skills",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/luciela77/Roblox-RPG-Skills#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/StarterPlayer/StarterPlayerScripts/Modules/Controllers/HotbarController.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "MuTEn-R0sHi/broblox",
  "owner": "MuTEn-R0sHi",
  "url": "https://github.com/MuTEn-R0sHi/broblox",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/MuTEn-R0sHi/broblox#license",
  "mechanics": [
   {
    "id": "checkpoints",
    "file": "games/obby/include/Promise.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()"
  ]
 },
 {
  "repo": "Diogo-S-Oliveira/CombatSystem-Roblox-MVP",
  "owner": "Diogo-S-Oliveira",
  "url": "https://github.com/Diogo-S-Oliveira/CombatSystem-Roblox-MVP",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Diogo-S-Oliveira/CombatSystem-Roblox-MVP#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "Server/CombatService.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "text21/SlotCore",
  "owner": "text21",
  "url": "https://github.com/text21/SlotCore",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/text21/SlotCore#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "src/SlotCore/server/AdminConfig.luau"
   },
   {
    "id": "currency",
    "file": "src/SlotCore/server/LeaderstatsBinder.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Drakkiosauro/Enterprise-AntiCheat-Roblox",
  "owner": "Drakkiosauro",
  "url": "https://github.com/Drakkiosauro/Enterprise-AntiCheat-Roblox",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Drakkiosauro/Enterprise-AntiCheat-Roblox#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "Enterprise Anti-Cheat Roblox.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "PythonCoders45/Roblox-Admin-Commands",
  "owner": "PythonCoders45",
  "url": "https://github.com/PythonCoders45/Roblox-Admin-Commands",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/PythonCoders45/Roblox-Admin-Commands#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "Cmdr/Cmdr.lua"
   },
   {
    "id": "currency",
    "file": "Cmdr/Commands/AdjestCurrencyServer.lua"
   },
   {
    "id": "ragdoll",
    "file": "Cmdr/Commands/jump_ragdoll.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "delay() is deprecated — use task.delay()"
  ]
 },
 {
  "repo": "mastershadow547/Advanced-Anticheat",
  "owner": "mastershadow547",
  "url": "https://github.com/mastershadow547/Advanced-Anticheat",
  "stars": 1,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/mastershadow547/Advanced-Anticheat#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "AntiCheat/ClientCore.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Distracted-Games/Remotes",
  "owner": "Distracted-Games",
  "url": "https://github.com/Distracted-Games/Remotes",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Distracted-Games/Remotes#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/Network/RemoteName/RemoteEventName.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Hinikaa/luaukit",
  "owner": "Hinikaa",
  "url": "https://github.com/Hinikaa/luaukit",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Hinikaa/luaukit#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/DataStore/DataStore.lua"
   },
   {
    "id": "anticheat",
    "file": "src/Net/RateLimiter.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "KiddyDevOfficial/Framework-v2",
  "owner": "KiddyDevOfficial",
  "url": "https://github.com/KiddyDevOfficial/Framework-v2",
  "stars": 1,
  "licence": "MIT",
  "licenceUrl": "https://github.com/KiddyDevOfficial/Framework-v2#license",
  "mechanics": [
   {
    "id": "currency",
    "file": "src/Atlas/Adapters/Leaderstats.luau"
   },
   {
    "id": "persistence",
    "file": "src/Atlas/Data/ProfileStore.luau"
   },
   {
    "id": "monetization",
    "file": "src/Atlas/Monetization/Client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Nirmini/NRC-OpenSource",
  "owner": "Nirmini",
  "url": "https://github.com/Nirmini/NRC-OpenSource",
  "stars": 0,
  "licence": "MPL-2.0",
  "licenceUrl": "https://github.com/Nirmini/NRC-OpenSource#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "HSRF-3-3-2025/src/ServerScriptService/CallAdmin.server.lua"
   },
   {
    "id": "persistence",
    "file": "HSRF-3-3-2025/src/ServerScriptService/DatastoreMngr.server.lua"
   },
   {
    "id": "badges",
    "file": "HSRF-3-3-2025/src/ServerScriptService/IndevParticipationBadgeManager.server.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "HSRF-3-3-2025/src/StarterGui/CustomLeaderboardGui/GuiManager.client.lua"
   },
   {
    "id": "teams",
    "file": "HSRF-3-3-2025/src/StarterGui/MainGui/MainMenu/Menu-Main/Sidebar/TeamSelect/LocalScript.client.lua"
   },
   {
    "id": "camera",
    "file": "HSRF-3-3-2025/src/StarterGui/StarterGUI/FreecamScript.client.lua"
   },
   {
    "id": "killbricks",
    "file": "HSRF-3-3-2025/src/Workspace/OpLight-Silo/Killbrick/Script.server.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "dankiq/feed-it-roblox",
  "owner": "dankiq",
  "url": "https://github.com/dankiq/feed-it-roblox",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/dankiq/feed-it-roblox#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/client/Controllers/InventoryController.luau"
   },
   {
    "id": "round_system",
    "file": "src/client/Controllers/RoundController.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ahnminjae08043-glitch/roblox-secure-inventory-sample",
  "owner": "ahnminjae08043-glitch",
  "url": "https://github.com/ahnminjae08043-glitch/roblox-secure-inventory-sample",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ahnminjae08043-glitch/roblox-secure-inventory-sample#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/client/InventoryClient.client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "lukedunwoody/inflate-every-second",
  "owner": "lukedunwoody",
  "url": "https://github.com/lukedunwoody/inflate-every-second",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/lukedunwoody/inflate-every-second#license",
  "mechanics": [
   {
    "id": "rebirth",
    "file": "src/ReplicatedStorage/Modules/RebirthConfig.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Sworddao/ascendant-mortal",
  "owner": "Sworddao",
  "url": "https://github.com/Sworddao/ascendant-mortal",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Sworddao/ascendant-mortal#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/Client/Network/NetworkClient.luau"
   },
   {
    "id": "camera",
    "file": "src/Client/Player/CameraController.luau"
   },
   {
    "id": "weapons",
    "file": "src/Client/Player/CombatController.luau"
   },
   {
    "id": "persistence",
    "file": "src/Server/Persistence/MemoryDataStore.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Khangaroooooo/studs",
  "owner": "Khangaroooooo",
  "url": "https://github.com/Khangaroooooo/studs",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Khangaroooooo/studs#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "src/ReplicatedStorage/MonetizationConfig.luau"
   },
   {
    "id": "anticheat",
    "file": "src/ReplicatedStorage/RateLimiter.luau"
   },
   {
    "id": "badges",
    "file": "src/ServerScriptService/BadgeSystem.server.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/ServerScriptService/LeaderboardSystem.server.luau"
   },
   {
    "id": "persistence",
    "file": "src/ServerScriptService/ProfileSystem.server.luau"
   },
   {
    "id": "quests",
    "file": "src/ServerScriptService/QuestSystem.server.luau"
   },
   {
    "id": "shop",
    "file": "src/ServerScriptService/ShopSystem.server.luau"
   },
   {
    "id": "inventory",
    "file": "src/StarterPlayerScripts/InventoryUI.client.luau"
   },
   {
    "id": "dialogue",
    "file": "src/StarterPlayerScripts/NPCDialogue.client.luau"
   },
   {
    "id": "remotes",
    "file": "src/StarterPlayerScripts/R6GaitRemote.client.luau"
   },
   {
    "id": "camera",
    "file": "src/StarterPlayerScripts/ShiftLockSetup.client.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "lukas-mikalainis/roblox-precision-framework",
  "owner": "lukas-mikalainis",
  "url": "https://github.com/lukas-mikalainis/roblox-precision-framework",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/lukas-mikalainis/roblox-precision-framework#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "src/server/WeaponService.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "jblaz6335/hacker-tycoon",
  "owner": "jblaz6335",
  "url": "https://github.com/jblaz6335/hacker-tycoon",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/jblaz6335/hacker-tycoon#license",
  "mechanics": [
   {
    "id": "dropper",
    "file": "src/ReplicatedStorage/HackerTycoon/AmbientConfig.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "src/ServerScriptService/HackerTycoon/LeaderboardService.lua"
   },
   {
    "id": "plots",
    "file": "src/ServerScriptService/HackerTycoon/PlotBuilder.lua"
   },
   {
    "id": "enemies",
    "file": "src/ServerScriptService/HackerTycoon/ZombieService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "thegamerbay/super-coin-world",
  "owner": "thegamerbay",
  "url": "https://github.com/thegamerbay/super-coin-world",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/thegamerbay/super-coin-world#license",
  "mechanics": [
   {
    "id": "leaderboard_global",
    "file": "src/ServerScriptService/GlobalLeaderboard.server.lua"
   },
   {
    "id": "currency",
    "file": "src/ServerScriptService/Modules/CoinManager.lua"
   },
   {
    "id": "enemies",
    "file": "src/ServerScriptService/Modules/NpcManager.lua"
   },
   {
    "id": "shop",
    "file": "src/ServerScriptService/Modules/ShopManager.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "kentiers/anvil",
  "owner": "kentiers",
  "url": "https://github.com/kentiers/anvil",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/kentiers/anvil#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "src/Adapters/ProfileStore.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "DLinacre/slime-factory-tycoon",
  "owner": "DLinacre",
  "url": "https://github.com/DLinacre/slime-factory-tycoon",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/DLinacre/slime-factory-tycoon#license",
  "mechanics": [
   {
    "id": "badges",
    "file": "src/server/Services/AchievementService.luau"
   },
   {
    "id": "customization",
    "file": "src/server/Services/CosmeticService.luau"
   },
   {
    "id": "daily_reward",
    "file": "src/server/Services/DailyRewardService.luau"
   },
   {
    "id": "currency",
    "file": "src/server/Services/EconomyService.luau"
   },
   {
    "id": "inventory",
    "file": "src/server/Services/InventoryService.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/server/Services/LeaderboardService.luau"
   },
   {
    "id": "monetization",
    "file": "src/server/Services/MonetizationService.luau"
   },
   {
    "id": "pets",
    "file": "src/server/Services/PetService.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Vasco888888/sword-duelists",
  "owner": "Vasco888888",
  "url": "https://github.com/Vasco888888/sword-duelists",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Vasco888888/sword-duelists#license",
  "mechanics": [
   {
    "id": "monetization",
    "file": "src/ServerScriptService/GamePassJump.server.luau"
   },
   {
    "id": "currency",
    "file": "src/ServerScriptService/Leaderstats.server.luau"
   },
   {
    "id": "weapons",
    "file": "src/ServerStorage/Sword/LocalSword.client.luau"
   },
   {
    "id": "remotes",
    "file": "src/ServerStorage/Sword/Resources/RemoteEventCreator.luau"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation"
  ]
 },
 {
  "repo": "mvvthw/roblox-claude-skills",
  "owner": "mvvthw",
  "url": "https://github.com/mvvthw/roblox-claude-skills",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/mvvthw/roblox-claude-skills#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "skills/roblox-datastore/references/PlayerDataManager.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "emiliancristea/roblox-dev-skills",
  "owner": "emiliancristea",
  "url": "https://github.com/emiliancristea/roblox-dev-skills",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/emiliancristea/roblox-dev-skills#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": ".agents/skills/roblox-game-developer/scripts/RemoteManager.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Naresh-x86/Mocap-Demo",
  "owner": "Naresh-x86",
  "url": "https://github.com/Naresh-x86/Mocap-Demo",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Naresh-x86/Mocap-Demo#license",
  "mechanics": [
   {
    "id": "camera",
    "file": "StarterGui/ManipulateCamera.LocalScript/ManipulateCamera.client.lua"
   },
   {
    "id": "dialogue",
    "file": "Workspace/VendingMachine.MeshPart/ProximityPrompt/Script/Script.server.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()"
  ]
 },
 {
  "repo": "derprofi1313/My-code-examples",
  "owner": "derprofi1313",
  "url": "https://github.com/derprofi1313/My-code-examples",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/derprofi1313/My-code-examples#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "CombatService.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation"
  ]
 },
 {
  "repo": "paulapeclat/primeiro-jogo-roblox",
  "owner": "paulapeclat",
  "url": "https://github.com/paulapeclat/primeiro-jogo-roblox",
  "stars": 0,
  "licence": "CC-BY-SA-4.0",
  "licenceUrl": "https://github.com/paulapeclat/primeiro-jogo-roblox#license",
  "mechanics": [
   {
    "id": "checkpoints",
    "file": "scripts/02-checkpoint.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "lowyabusa/roblox-server-leaderboard-system",
  "owner": "lowyabusa",
  "url": "https://github.com/lowyabusa/roblox-server-leaderboard-system",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/lowyabusa/roblox-server-leaderboard-system#license",
  "mechanics": [
   {
    "id": "leaderboard_global",
    "file": "commands/CreateWorkspaceLeaderboards.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Gzeu/roblox-procedural-worlds",
  "owner": "Gzeu",
  "url": "https://github.com/Gzeu/roblox-procedural-worlds",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Gzeu/roblox-procedural-worlds#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "src/AntiExploit.lua"
   },
   {
    "id": "procedural_terrain",
    "file": "src/ChunkHandler.lua"
   },
   {
    "id": "weapons",
    "file": "src/CombatSystem.lua"
   },
   {
    "id": "daily_reward",
    "file": "src/DailyRewards.lua"
   },
   {
    "id": "persistence",
    "file": "src/DataStoreManager.lua"
   },
   {
    "id": "monetization",
    "file": "src/DeveloperProductHandler.lua"
   },
   {
    "id": "dialogue",
    "file": "src/DialogueUI.client.lua"
   },
   {
    "id": "currency",
    "file": "src/EconomyManager.lua"
   },
   {
    "id": "inventory",
    "file": "src/InventoryUI.client.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "src/LeaderboardManager.lua"
   },
   {
    "id": "enemies",
    "file": "src/MobSpawner.lua"
   },
   {
    "id": "quests",
    "file": "src/QuestSystem.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "spavdigital/roblox-tycoon",
  "owner": "spavdigital",
  "url": "https://github.com/spavdigital/roblox-tycoon",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/spavdigital/roblox-tycoon#license",
  "mechanics": [
   {
    "id": "dropper",
    "file": "src/server/TycoonService.server.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "RiiK26/TycoonButBattle",
  "owner": "RiiK26",
  "url": "https://github.com/RiiK26/TycoonButBattle",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/RiiK26/TycoonButBattle#license",
  "mechanics": [
   {
    "id": "daily_reward",
    "file": "ReplicatedStorage/Modules/DailyRewards.luau"
   },
   {
    "id": "rebirth",
    "file": "ReplicatedStorage/Modules/Rebirths.luau"
   },
   {
    "id": "anticheat",
    "file": "ServerScriptService/AntiCheat/Main.luau"
   },
   {
    "id": "weapons",
    "file": "ServerScriptService/CombatSystem/CombatUtils.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "ServerScriptService/Leaderboard/Handler.luau"
   },
   {
    "id": "currency",
    "file": "ServerScriptService/Machines/CashGenerator/CashGenerator.luau"
   },
   {
    "id": "dropper",
    "file": "ServerScriptService/Machines/ClickDropper/Classes.luau"
   },
   {
    "id": "inventory",
    "file": "ServerScriptService/Machines/LoadoutLocker/ModuleScript.luau"
   },
   {
    "id": "towers",
    "file": "ServerScriptService/Machines/Turret/TurretSystem.luau"
   },
   {
    "id": "persistence",
    "file": "ServerScriptService/PlayerData/DataStore2/MainModule.luau"
   },
   {
    "id": "shop",
    "file": "ServerScriptService/ProductHandler/DiamondPurchase/ShopServerHandler.luau"
   },
   {
    "id": "monetization",
    "file": "ServerScriptService/TycoonSystem/PurchaseController.luau"
   },
   {
    "id": "upgrades",
    "file": "ServerScriptService/UpgradeSystem/UpgradeHandler.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "zodaz0/Horizon-Tycoon",
  "owner": "zodaz0",
  "url": "https://github.com/zodaz0/Horizon-Tycoon",
  "stars": 0,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/zodaz0/Horizon-Tycoon#license",
  "mechanics": [
   {
    "id": "dropper",
    "file": "ServerScriptService/Components/Conveyor.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "drburton/LearningRobloxGameDev_Obby",
  "owner": "drburton",
  "url": "https://github.com/drburton/LearningRobloxGameDev_Obby",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/drburton/LearningRobloxGameDev_Obby#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "Chapter 6/PlayerData.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "JonahLederman/ROBLOX-Obstacle-Tower",
  "owner": "JonahLederman",
  "url": "https://github.com/JonahLederman/ROBLOX-Obstacle-Tower",
  "stars": 0,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/JonahLederman/ROBLOX-Obstacle-Tower#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "ReplicatedStorage/PlayerData.luau"
   },
   {
    "id": "checkpoints",
    "file": "ServerScriptStorage/BackStageController.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "Workspace & Objects/Leaderboard.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Frantisek-Rados/obby-skripty",
  "owner": "Frantisek-Rados",
  "url": "https://github.com/Frantisek-Rados/obby-skripty",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Frantisek-Rados/obby-skripty#license",
  "mechanics": [
   {
    "id": "checkpoints",
    "file": "checkpoint.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "iqbaleff214/roblox-obby-base",
  "owner": "iqbaleff214",
  "url": "https://github.com/iqbaleff214/roblox-obby-base",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/iqbaleff214/roblox-obby-base#license",
  "mechanics": [
   {
    "id": "camera",
    "file": "src/client/CameraController.lua"
   },
   {
    "id": "inventory",
    "file": "src/client/InventoryUI.lua"
   },
   {
    "id": "leaderboard_global",
    "file": "src/client/LeaderboardCache.lua"
   },
   {
    "id": "rebirth",
    "file": "src/client/PrestigeUI.lua"
   },
   {
    "id": "shop",
    "file": "src/client/ShopUI.lua"
   },
   {
    "id": "currency",
    "file": "src/server/CoinService.lua"
   },
   {
    "id": "killbricks",
    "file": "src/server/HazardService.lua"
   },
   {
    "id": "dropper",
    "file": "src/server/Hazards/ConveyorHazard.lua"
   },
   {
    "id": "anticheat",
    "file": "src/server/MovementAntiCheat.lua"
   },
   {
    "id": "checkpoints",
    "file": "src/server/StageService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "MarioChao/pie-difficulty-chart",
  "owner": "MarioChao",
  "url": "https://github.com/MarioChao/pie-difficulty-chart",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/MarioChao/pie-difficulty-chart#license",
  "mechanics": [
   {
    "id": "currency",
    "file": "src/ServerScriptService/DifficultyChart_ServerScripts/Player_Leaderstats/init.luau"
   },
   {
    "id": "persistence",
    "file": "src/ServerScriptService/DifficultyChart_ServerScripts/Player_Profile/ProfileStore.luau"
   },
   {
    "id": "checkpoints",
    "file": "src/ServerScriptService/DifficultyChart_ServerScripts/StageModules/Stage_Config.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "jackdoe/roblox-forth-tower-defense",
  "owner": "jackdoe",
  "url": "https://github.com/jackdoe/roblox-forth-tower-defense",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/jackdoe/roblox-forth-tower-defense#license",
  "mechanics": [
   {
    "id": "enemies",
    "file": "src/server/EnemyManager.luau"
   },
   {
    "id": "waves",
    "file": "src/server/WaveManager.luau"
   },
   {
    "id": "tutorial",
    "file": "src/shared/TutorialData.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ProRobloxOP/Just_A_Tower_Defense--Roblox",
  "owner": "ProRobloxOP",
  "url": "https://github.com/ProRobloxOP/Just_A_Tower_Defense--Roblox",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ProRobloxOP/Just_A_Tower_Defense--Roblox#license",
  "mechanics": [
   {
    "id": "towers",
    "file": "Tower (Module)(Server).lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Anton-J-Castillo/Multiverse-Tower-Defense",
  "owner": "Anton-J-Castillo",
  "url": "https://github.com/Anton-J-Castillo/Multiverse-Tower-Defense",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Anton-J-Castillo/Multiverse-Tower-Defense#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "Game/Local Scripts/Cmdr.lua"
   },
   {
    "id": "inventory",
    "file": "Lobby/Local Scripts/InventoryHandler.lua"
   },
   {
    "id": "shop",
    "file": "Lobby/Local Scripts/ShopHandler.lua"
   },
   {
    "id": "round_system",
    "file": "Lobby/Module Scripts/CrateShop.lua"
   },
   {
    "id": "towers",
    "file": "Lobby/Module Scripts/TowerGenerator.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()",
   "wait() is deprecated — use task.wait()"
  ]
 },
 {
  "repo": "yami-qr/td-system",
  "owner": "yami-qr",
  "url": "https://github.com/yami-qr/td-system",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/yami-qr/td-system#license",
  "mechanics": [
   {
    "id": "enemies",
    "file": "src/ReplicatedStorage/Shared/EnemyConfig.luau"
   },
   {
    "id": "towers",
    "file": "src/ReplicatedStorage/Shared/TowerConfig.luau"
   },
   {
    "id": "waves",
    "file": "src/ReplicatedStorage/Shared/WaveConfig.luau"
   },
   {
    "id": "placement",
    "file": "src/StarterPlayer/StarterPlayerScripts/PlacementController.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "onyx-box/campfire-express",
  "owner": "onyx-box",
  "url": "https://github.com/onyx-box/campfire-express",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/onyx-box/campfire-express#license",
  "mechanics": [
   {
    "id": "placement",
    "file": "src/client/Controllers/CampfirePlacementController.lua"
   },
   {
    "id": "inventory",
    "file": "src/client/Controllers/InventoryController.lua"
   },
   {
    "id": "enemies",
    "file": "src/server/Services/EnemyService.lua"
   },
   {
    "id": "waves",
    "file": "src/server/Services/WaveService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "hpagni/cryptlings",
  "owner": "hpagni",
  "url": "https://github.com/hpagni/cryptlings",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/hpagni/cryptlings#license",
  "mechanics": [
   {
    "id": "tutorial",
    "file": "src/client/Controllers/OnboardingController.luau"
   },
   {
    "id": "pets",
    "file": "src/client/Controllers/PetUI.luau"
   },
   {
    "id": "shop",
    "file": "src/client/Controllers/ShopUI.luau"
   },
   {
    "id": "admin_commands",
    "file": "src/server/Services/AdminCommands.luau"
   },
   {
    "id": "weapons",
    "file": "src/server/Services/CombatService.luau"
   },
   {
    "id": "plots",
    "file": "src/server/Services/LobbyPlotService.luau"
   },
   {
    "id": "monetization",
    "file": "src/server/Services/MonetizationService.luau"
   },
   {
    "id": "persistence",
    "file": "src/server/Services/PlayerDataService.luau"
   },
   {
    "id": "remotes",
    "file": "src/shared/Net/Remotes.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "tralfa42real/roblox-rpg-core-systems",
  "owner": "tralfa42real",
  "url": "https://github.com/tralfa42real/roblox-rpg-core-systems",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/tralfa42real/roblox-rpg-core-systems#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "src/ReplicatedStorage/Shared/Net/RateLimiter.lua"
   },
   {
    "id": "weapons",
    "file": "src/ServerScriptService/Services/CombatService.lua"
   },
   {
    "id": "currency",
    "file": "src/ServerScriptService/Services/EconomyService.lua"
   },
   {
    "id": "enemies",
    "file": "src/ServerScriptService/Services/EnemyAIService.lua"
   },
   {
    "id": "inventory",
    "file": "src/ServerScriptService/Services/InventoryService.lua"
   },
   {
    "id": "pets",
    "file": "src/ServerScriptService/Services/PetService.lua"
   },
   {
    "id": "persistence",
    "file": "src/ServerScriptService/Services/ProfileService.lua"
   },
   {
    "id": "shop",
    "file": "src/ServerScriptService/Services/VendorService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "c0nf1ux/brisingr-realms",
  "owner": "c0nf1ux",
  "url": "https://github.com/c0nf1ux/brisingr-realms",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/c0nf1ux/brisingr-realms#license",
  "mechanics": [
   {
    "id": "checkpoints",
    "file": "src/ServerScriptService/RacingCheckpoints.lua"
   },
   {
    "id": "procedural_terrain",
    "file": "src/ServerScriptService/TerrainGenerator.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Devon-ODell/paintball-insanity",
  "owner": "Devon-ODell",
  "url": "https://github.com/Devon-ODell/paintball-insanity",
  "stars": 0,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/Devon-ODell/paintball-insanity#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/ReplicatedStorage/Net/Remotes.luau"
   },
   {
    "id": "inventory",
    "file": "src/ReplicatedStorage/Shared/Loadout.luau"
   },
   {
    "id": "dialogue",
    "file": "src/ServerScriptService/Dialogue/DialogueService.luau"
   },
   {
    "id": "leaderboard_global",
    "file": "src/ServerScriptService/Leaderboard/Leaderboard.luau"
   },
   {
    "id": "round_system",
    "file": "src/ServerScriptService/Match/MatchService.luau"
   },
   {
    "id": "shop",
    "file": "src/StarterPlayer/Client/ShopUi.luau"
   },
   {
    "id": "weapons",
    "file": "tools/probe-hitbox.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "marsupiter43-collab/shadow-sector-roblox",
  "owner": "marsupiter43-collab",
  "url": "https://github.com/marsupiter43-collab/shadow-sector-roblox",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/marsupiter43-collab/shadow-sector-roblox#license",
  "mechanics": [
   {
    "id": "quests",
    "file": "src/Modules/QuestSystem.lua"
   },
   {
    "id": "round_system",
    "file": "src/Server/GameLoop.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "wait() is deprecated — use task.wait()"
  ]
 },
 {
  "repo": "njtsb1/Survival_Game_Roblox",
  "owner": "njtsb1",
  "url": "https://github.com/njtsb1/Survival_Game_Roblox",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/njtsb1/Survival_Game_Roblox#license",
  "mechanics": [
   {
    "id": "enemies",
    "file": "scripts_lua/ZombieSpawner.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation",
   "spawn() is deprecated — use task.spawn()"
  ]
 },
 {
  "repo": "njtsb1/Game_on_Roblox",
  "owner": "njtsb1",
  "url": "https://github.com/njtsb1/Game_on_Roblox",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/njtsb1/Game_on_Roblox#license",
  "mechanics": [
   {
    "id": "enemies",
    "file": "scripts_lua/ZombieSpawner.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation",
   "spawn() is deprecated — use task.spawn()"
  ]
 },
 {
  "repo": "K3N0V3RL0RD/zed-alpha",
  "owner": "K3N0V3RL0RD",
  "url": "https://github.com/K3N0V3RL0RD/zed-alpha",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/K3N0V3RL0RD/zed-alpha#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "gun-system/client.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "heylogscript/grow-stars",
  "owner": "heylogscript",
  "url": "https://github.com/heylogscript/grow-stars",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/heylogscript/grow-stars#license",
  "mechanics": [
   {
    "id": "persistence",
    "file": "ReplicatedStorage/PlayerData.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "SavFil/platformer-roblox-project",
  "owner": "SavFil",
  "url": "https://github.com/SavFil/platformer-roblox-project",
  "stars": 0,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/SavFil/platformer-roblox-project#license",
  "mechanics": [
   {
    "id": "camera",
    "file": "src/ReplicatedStorage/CameraModule.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "17sync/Vertis",
  "owner": "17sync",
  "url": "https://github.com/17sync/Vertis",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/17sync/Vertis#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "src/replicatedstorage/remotes/hello.client.luau"
   },
   {
    "id": "camera",
    "file": "src/starterplayerscripts/controllers/cameracontroller/init.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "realrrsripts/Roblox-Inventory-Equipment-Framework",
  "owner": "realrrsripts",
  "url": "https://github.com/realrrsripts/Roblox-Inventory-Equipment-Framework",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/realrrsripts/Roblox-Inventory-Equipment-Framework#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "Roblox Inventory & Equipment Framework/src/Client/Inventory/InventoryController.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "tralfa42real/roblox-secure-inventory-system",
  "owner": "tralfa42real",
  "url": "https://github.com/tralfa42real/roblox-secure-inventory-system",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/tralfa42real/roblox-secure-inventory-system#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "src/ReplicatedStorage/Shared/Net/RateLimiter.lua"
   },
   {
    "id": "inventory",
    "file": "src/ServerScriptService/Services/InventoryService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Diogo-S-Oliveira/Roblox-Inventory-System",
  "owner": "Diogo-S-Oliveira",
  "url": "https://github.com/Diogo-S-Oliveira/Roblox-Inventory-System",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Diogo-S-Oliveira/Roblox-Inventory-System#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "InventoryManager.lua"
   },
   {
    "id": "persistence",
    "file": "PlayerData.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "kpackk/roblox-gameplay-systems",
  "owner": "kpackk",
  "url": "https://github.com/kpackk/roblox-gameplay-systems",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/kpackk/roblox-gameplay-systems#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "combat-system/src/CombatInput.client.luau"
   },
   {
    "id": "inventory",
    "file": "inventory-system/src/DataAdapter.module.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Tristan886/Pet-System",
  "owner": "Tristan886",
  "url": "https://github.com/Tristan886/Pet-System",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/Tristan886/Pet-System#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "InventoryHandler.lua"
   },
   {
    "id": "pets",
    "file": "ServerPetHandler.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "victor12082024/Combat_System",
  "owner": "victor12082024",
  "url": "https://github.com/victor12082024/Combat_System",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/victor12082024/Combat_System#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "src/client_StarterPlayerScripts/ClientServices/Controllers/CombatController.client.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "yashveer-singh-speaks/velmora",
  "owner": "yashveer-singh-speaks",
  "url": "https://github.com/yashveer-singh-speaks/velmora",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/yashveer-singh-speaks/velmora#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "src/client/Combat/CombatClient.luau"
   },
   {
    "id": "inventory",
    "file": "src/client/Loadout/WeaponSelect.luau"
   },
   {
    "id": "pets",
    "file": "src/client/Pets/PetClient.luau"
   },
   {
    "id": "shop",
    "file": "src/client/Shop/ShopClient.luau"
   },
   {
    "id": "anticheat",
    "file": "src/server/Combat/CombatAntiCheat.luau"
   },
   {
    "id": "persistence",
    "file": "src/server/Data/SaveService.luau"
   },
   {
    "id": "zones",
    "file": "src/server/Hazards/DamageZoneService.luau"
   },
   {
    "id": "round_system",
    "file": "src/server/Match/MatchService.luau"
   },
   {
    "id": "enemies",
    "file": "src/server/NPC/NpcService.luau"
   },
   {
    "id": "remotes",
    "file": "src/shared/Barrier/BarrierRemotes.luau"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "BodyMovers are deprecated — use LinearVelocity / AlignPosition / AlignOrientation"
  ]
 },
 {
  "repo": "MarioChao/backpack-ui",
  "owner": "MarioChao",
  "url": "https://github.com/MarioChao/backpack-ui",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/MarioChao/backpack-ui#license",
  "mechanics": [
   {
    "id": "inventory",
    "file": "src/BackpackUI/Main.server.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "tralfa42real/roblox-quest-dialogue-system",
  "owner": "tralfa42real",
  "url": "https://github.com/tralfa42real/roblox-quest-dialogue-system",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/tralfa42real/roblox-quest-dialogue-system#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "src/ReplicatedStorage/Shared/Net/RateLimiter.lua"
   },
   {
    "id": "quests",
    "file": "src/ServerScriptService/Services/QuestService.lua"
   },
   {
    "id": "dialogue",
    "file": "src/StarterPlayer/StarterPlayerScripts/DialogueClient.client.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "ryanleem/Roblox-Building-and-Placement-System",
  "owner": "ryanleem",
  "url": "https://github.com/ryanleem/Roblox-Building-and-Placement-System",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/ryanleem/Roblox-Building-and-Placement-System#license",
  "mechanics": [
   {
    "id": "placement",
    "file": "src/client/PlacementController.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "Kaminoan-Engineers/repulsyn",
  "owner": "Kaminoan-Engineers",
  "url": "https://github.com/Kaminoan-Engineers/repulsyn",
  "stars": 0,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/Kaminoan-Engineers/repulsyn#license",
  "mechanics": [
   {
    "id": "vehicles",
    "file": "Repulsyn_Engine/Components/BaseVehicle.module.luau"
   },
   {
    "id": "camera",
    "file": "Repulsyn_Engine/Configuration/CameraConfig.module.luau"
   },
   {
    "id": "remotes",
    "file": "Repulsyn_Engine/Configuration/NetworkConfig.module.luau"
   },
   {
    "id": "weapons",
    "file": "Repulsyn_Engine/Controllers/GunController.module.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "rivinstudios/Rivin-AntiCheat",
  "owner": "rivinstudios",
  "url": "https://github.com/rivinstudios/Rivin-AntiCheat",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/rivinstudios/Rivin-AntiCheat#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "RivinAntiCheat.lua"
   }
  ],
  "currency": "deprecated-calls-present",
  "deprecated": [
   "spawn() is deprecated — use task.spawn()"
  ]
 },
 {
  "repo": "Alex-Tech-Incorporated/OspryOS-Anticheat",
  "owner": "Alex-Tech-Incorporated",
  "url": "https://github.com/Alex-Tech-Incorporated/OspryOS-Anticheat",
  "stars": 0,
  "licence": "AGPL-3.0",
  "licenceUrl": "https://github.com/Alex-Tech-Incorporated/OspryOS-Anticheat#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "MainModule/Dependencies/Anticheat_Server.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "keaxx/Roblox-AntiCheat",
  "owner": "keaxx",
  "url": "https://github.com/keaxx/Roblox-AntiCheat",
  "stars": 0,
  "licence": "GPL-3.0",
  "licenceUrl": "https://github.com/keaxx/Roblox-AntiCheat#license",
  "mechanics": [
   {
    "id": "weapons",
    "file": "Scripts/HitboxChanger.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "kyrosdev/Synapse",
  "owner": "kyrosdev",
  "url": "https://github.com/kyrosdev/Synapse",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/kyrosdev/Synapse#license",
  "mechanics": [
   {
    "id": "anticheat",
    "file": "src/Synapse/Public/Sides/Server/RateLimiter.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "orange451/SkinnedMeshRagdoll",
  "owner": "orange451",
  "url": "https://github.com/orange451/SkinnedMeshRagdoll",
  "stars": 0,
  "licence": "Apache-2.0",
  "licenceUrl": "https://github.com/orange451/SkinnedMeshRagdoll#license",
  "mechanics": [
   {
    "id": "ragdoll",
    "file": "SkinnedMeshRagdoll.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "errorinmysyntax/Roblox-Ragdoll-Service",
  "owner": "errorinmysyntax",
  "url": "https://github.com/errorinmysyntax/Roblox-Ragdoll-Service",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/errorinmysyntax/Roblox-Ragdoll-Service#license",
  "mechanics": [
   {
    "id": "ragdoll",
    "file": "src/SimpleRagdollService.lua"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "akmalriyas/easy-ragdoll",
  "owner": "akmalriyas",
  "url": "https://github.com/akmalriyas/easy-ragdoll",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/akmalriyas/easy-ragdoll#license",
  "mechanics": [
   {
    "id": "ragdoll",
    "file": "EasyRagdoll.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "gordxn-rbx/utilities",
  "owner": "gordxn-rbx",
  "url": "https://github.com/gordxn-rbx/utilities",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/gordxn-rbx/utilities#license",
  "mechanics": [
   {
    "id": "remotes",
    "file": "modules/RemoteService/init.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 },
 {
  "repo": "horsenuggets/discord-luau",
  "owner": "horsenuggets",
  "url": "https://github.com/horsenuggets/discord-luau",
  "stars": 0,
  "licence": "MIT",
  "licenceUrl": "https://github.com/horsenuggets/discord-luau#license",
  "mechanics": [
   {
    "id": "admin_commands",
    "file": "Source/DiscordLuau/Structures/SlashCommandBuilder.luau"
   }
  ],
  "currency": "clean",
  "deprecated": []
 }
];
