/**
 * WHERE GENERATED BYTES LIVE.
 *
 * THE DEFECT THIS REPLACES. Generated images, generated audio and chat attachments were stored as
 * base64 strings in KV with `expirationTtl: 3600`. An image the product made for someone was gone
 * an hour later — and the retention page published "1 hour" as the policy, because it was true.
 * KV is a key-value store with a 25 MiB ceiling, no lifecycle and a per-key cost model; bytes were
 * never its job. R2 is, and on this account it is free at this volume: 10 GB-month of storage,
 * 1,000,000 Class A and 10,000,000 Class B operations a month, deletes and egress free.
 *
 * WHAT THIS MODULE IS. One place that answers "is there an object store, and what is this object's
 * key", so that question is answered once rather than at each call site. It deliberately does NOT
 * wrap R2's API: callers that need a stream, a range or conditional headers should reach the bucket
 * directly. What they must not do is invent a second key convention.
 *
 * THE KEY IS THE ERASURE CONTRACT. Every object is `<kind>/<projectId>/<id>`, projectId second, so
 * a project's media is one `list({ prefix })` away. `erasure.ts` deletes a user's data by listing
 * KV by prefix; if media moved to R2 without that path learning R2, account deletion would silently
 * stop covering images, audio and attachments. That is a legal hole rather than a bug, which is why
 * `eraseProjectMedia` ships in the same file as the writer instead of being a follow-up.
 *
 * DEGRADES RATHER THAN THROWS. `env.MEDIA` is optional: a `wrangler dev` without R2, or a
 * deployment from an older config, gets `null` from `mediaStore()` and the caller keeps its KV
 * path. A store that throws on the first write in an environment that never had it would turn a
 * missing binding into an outage.
 */
import type { Env } from './env';

export const MEDIA_KINDS = ['image', 'audio', 'attachment'] as const;
export type MediaKind = (typeof MEDIA_KINDS)[number];

/** R2 keys are opaque to the store but not to us: this is the shape erasure relies on. */
export function mediaKey(kind: MediaKind, projectId: string, id: string): string {
  return `${kind}/${projectId}/${id}`;
}

/** The bucket, or null when this deployment has none. Ask; never assume. */
export function mediaStore(env: Pick<Env, 'MEDIA'>): R2Bucket | null {
  return env.MEDIA ?? null;
}

export interface StoredMedia {
  key: string;
  size: number;
}

/**
 * Write bytes and return the key, or null when there is no bucket.
 *
 * `httpMetadata.contentType` is set at write time because R2 serves it back on GET, so a reader
 * does not need a sidecar to know what it holds — which is exactly the thing the KV path needed a
 * metadata blob for.
 */
export async function putMedia(
  env: Pick<Env, 'MEDIA'>,
  kind: MediaKind,
  projectId: string,
  id: string,
  body: ArrayBuffer | Uint8Array,
  contentType: string,
  extra?: Readonly<Record<string, string>>,
): Promise<StoredMedia | null> {
  const bucket = mediaStore(env);
  if (!bucket) return null;
  const key = mediaKey(kind, projectId, id);
  const bytes = body instanceof Uint8Array ? body : new Uint8Array(body);
  await bucket.put(key, bytes, {
    httpMetadata: { contentType },
    // The project id is on the object as well as in the key. The key is what erasure sweeps; this
    // is what makes an object auditable when someone is holding it and not its path.
    //
    // `extra` is for facts that belong to the object and have nowhere else to live — audio has no
    // index table, so its duration would otherwise be lost the moment it left the writer. It is
    // spread FIRST so nothing a caller passes can overwrite the project id or the kind: those two
    // are the audit trail and are not a caller's to set.
    customMetadata: { ...extra, projectId, kind },
  });
  return { key, size: bytes.byteLength };
}

/**
 * Read bytes back, or null for "no bucket" AND for "no such object" — the caller falls back.
 *
 * `contentType` COMES BACK AS STORED, which means it is a value a writer chose, and a caller that
 * puts it in a response header is echoing storage at a browser. Every caller here runs it through
 * its own allowlist first; this function reports what is there rather than deciding what is safe.
 */
export async function getMedia(
  env: Pick<Env, 'MEDIA'>,
  kind: MediaKind,
  projectId: string,
  id: string,
): Promise<{ body: ArrayBuffer; contentType: string | null; custom: Record<string, string> } | null> {
  const bucket = mediaStore(env);
  if (!bucket) return null;
  const object = await bucket.get(mediaKey(kind, projectId, id));
  if (!object) return null;
  return {
    body: await object.arrayBuffer(),
    contentType: object.httpMetadata?.contentType ?? null,
    custom: object.customMetadata ?? {},
  };
}

/** How many objects one sweep will delete before reporting that it did not finish. */
export const MEDIA_SWEEP_MAX = 5_000;

export interface MediaErasure {
  status: 'erased' | 'partial' | 'unavailable';
  objects: number;
  detail?: string;
}

/**
 * Every media object belonging to one project.
 *
 * Re-lists from the start each round rather than paging with a cursor: a cursor taken before a
 * delete describes a listing that no longer exists, and the failure mode of getting that wrong is
 * "some of the user's data survived a deletion they asked for". Bounded, and it SAYS when it ran out
 * of budget instead of reporting a clean sweep — a partial erasure reported as complete is the
 * worst answer this function can give.
 */
export async function eraseProjectMedia(env: Pick<Env, 'MEDIA'>, projectId: string): Promise<MediaErasure> {
  const bucket = mediaStore(env);
  if (!bucket) {
    return { status: 'unavailable', objects: 0, detail: 'this deployment has no media bucket bound' };
  }
  let deleted = 0;
  for (const kind of MEDIA_KINDS) {
    const prefix = `${kind}/${projectId}/`;
    for (;;) {
      const listed = await bucket.list({ prefix, limit: 1000 });
      if (listed.objects.length === 0) break;
      const keys = listed.objects.map((o) => o.key).slice(0, Math.max(0, MEDIA_SWEEP_MAX - deleted));
      if (keys.length === 0) {
        return {
          status: 'partial',
          objects: deleted,
          detail: `stopped at the ${MEDIA_SWEEP_MAX}-object sweep limit; run it again`,
        };
      }
      await bucket.delete(keys);
      deleted += keys.length;
    }
  }
  return { status: 'erased', objects: deleted };
}
