// insert_ui_component: the ONLY way Apple puts game UI in a place (D-UIONLY-1).
//
// Every visible pixel is a stored library file. The component catalogue
// (packages/asset-library/ui-components.json, generated by build-ui-components.mjs) says which
// file plays which role in which genre skin, with the 9-slice margins, text ink and outline colour
// measured off the PNG and the font taken from the sources list. This module only arranges those
// pieces: it emits transparent layout frames, ImageLabels/ImageButtons whose Image is an uploaded
// library file, and TextLabels whose colour is a sampled library pixel. It never names a colour,
// an image or a font of its own.
//
// Image ids come from, in order: the shared table packages/asset-library/roblox-ids.json, the
// user's own cache (KV), then an upload of the stored file into the user's own Roblox account
// (uploadLibraryAsset, their key, Robux ceiling 0). An image that cannot be resolved stops the
// insert: a component with a blank square where its panel should be is not inserted.
import lib from '../../../packages/asset-library/ui-components.json';
import shared from '../../../packages/asset-library/roblox-ids.json';
import type { GatewayToolDef, InstanceSpec, PropValue, StudioOp } from '@golem/shared';
import type { Env } from './env';
import type { LibraryRule } from './library-guard';
import type { OpCall } from './phase-a-tools';
import { libraryAsset, uploadLibraryAsset, type UploadDeps } from './asset-library';
import { uiStoreImage } from './ui-store-search';

type Spec = Omit<InstanceSpec, 'parent'>;
type P = Record<string, PropValue>;
type Args = Record<string, unknown>;
interface Img { w: number; h: number; slice: number[]; centre: number[]; edge: number[]; text: 'light' | 'dark' }
interface Skin { title: string; genres: string[]; font: string; colours: string[]; roles: Record<string, Record<string, string>> }
interface Component { id: string; title: string; group: string; genres: string[]; roles: string[]; icons: string[] }
interface Lib { ink: { ink_light: number[]; ink_dark: number[] }; skins: Record<string, Skin>; icons: Record<string, string>; images: Record<string, Img>; components: Component[] }

const L = lib as unknown as Lib;
const SHARED_IDS = (shared as unknown as { ids: Record<string, string> }).ids;
const COMPONENTS = new Map(L.components.map((c) => [c.id, c]));
export const UI_COMPONENT_IDS = L.components.map((c) => c.id);
const GENRE_OF = new Map<string, string>();
for (const [id, s] of Object.entries(L.skins)) { GENRE_OF.set(id, id); for (const g of s.genres) GENRE_OF.set(g, id); }
const ANCHORS = ['top_left', 'top', 'top_right', 'left', 'center', 'right', 'bottom_left', 'bottom', 'bottom_right'] as const;
type Anchor = (typeof ANCHORS)[number];
const ANCHOR_POINTS: Record<Anchor, [number, number]> = {
  top_left: [0, 0], top: [0.5, 0], top_right: [1, 0], left: [0, 0.5], center: [0.5, 0.5], right: [1, 0.5],
  bottom_left: [0, 1], bottom: [0.5, 1], bottom_right: [1, 1],
};
const MARGIN = 0.02;
const WORLD = new Set(['billboard_tag', 'surface_sign']);

/* ------------------------------------------------------------------ wire values --- */

const udim2 = (xs: number, xo: number, ys: number, yo: number): PropValue => ({ t: 'UDim2', v: [xs, xo, ys, yo] }) as PropValue;
const udim = (s: number, o: number): PropValue => ({ t: 'UDim', v: [s, o] }) as PropValue;
const vec2 = (x: number, y: number): PropValue => ({ t: 'Vector2', v: [x, y] }) as PropValue;
const vec3 = (x: number, y: number, z: number): PropValue => ({ t: 'Vector3', v: [x, y, z] }) as PropValue;
const num = (v: number): PropValue => ({ t: 'number', v }) as PropValue;
const bool = (v: boolean): PropValue => ({ t: 'bool', v }) as PropValue;
const str = (v: string): PropValue => ({ t: 'string', v }) as PropValue;
const enumItem = (v: string): PropValue => ({ t: 'EnumItem', v }) as PropValue;
const rect = (r: number[]): PropValue => ({ t: 'Rect', v: r }) as PropValue;
const rgb = (c: number[]): PropValue => ({ t: 'Color3', v: c.map((x) => Math.round((x / 255) * 1000) / 1000) }) as PropValue;
const r3 = (n: number) => Math.round(n * 1000) / 1000;
const at = (xs: number, ys: number, ax = 0, ay = 0): P => ({ Position: udim2(xs, 0, ys, 0), AnchorPoint: vec2(ax, ay) });
const sized = (w: number, h: number): P => ({ Size: udim2(w, 0, h, 0) });
const box = (x: number, y: number, w: number, h: number, ax = 0, ay = 0): P => ({ ...at(x, y, ax, ay), ...sized(w, h) });

/* --------------------------------------------------------------------- builder --- */

interface Item { name?: string; value?: number | string | boolean; price?: number | string; icon?: string; locked?: boolean; kind?: string; options?: string[] }
interface Input {
  component: Component; skin: string; colour: string; name: string;
  title?: string; text?: string; value?: number | string | boolean; items?: Item[]; icon?: string;
}

class Builder {
  count = 0;
  readonly assets = new Set<string>();
  readonly roles: Record<string, string>;
  readonly font: string;
  constructor(readonly input: Input, readonly idOf: (asset: string) => string) {
    const s = L.skins[input.skin]!;
    this.roles = s.roles[input.colour]!;
    this.font = s.font;
  }

  spec(className: string, name: string, props: P, children: Spec[] = []): Spec {
    this.count += 1;
    return children.length ? { className, name, props, children } : { className, name, props };
  }
  frame(name: string, place: P, children: Spec[] = []): Spec {
    return this.spec('Frame', name, { ...place, BackgroundTransparency: num(1) }, children);
  }
  aspect(ratio: number): Spec {
    return this.spec('UIAspectRatioConstraint', 'Aspect', { AspectRatio: num(r3(ratio)) });
  }
  role(role: string): string {
    const asset = this.roles[role];
    if (!asset) throw new Error(`${this.input.component.id} used role ${role}, which skin ${this.input.skin} does not have`);
    return asset;
  }
  picture(asset: string): P {
    this.assets.add(asset);
    return { Image: str(`rbxassetid://${this.idOf(asset)}`), BackgroundTransparency: num(1) };
  }
  /** A 9-slice library image, stretched to `place` without distorting its corners. */
  slice(name: string, role: string, place: P, children: Spec[] = [], button = false): Spec {
    const asset = this.role(role);
    return this.spec(button ? 'ImageButton' : 'ImageLabel', name, {
      ...place, ...this.picture(asset),
      ScaleType: enumItem('Enum.ScaleType.Slice'), SliceCenter: rect(L.images[asset]!.slice),
    }, children);
  }
  /** A library image drawn whole at its own aspect (icons, round buttons, rings). */
  fit(name: string, asset: string, place: P, children: Spec[] = [], button = false): Spec {
    return this.spec(button ? 'ImageButton' : 'ImageLabel', name, { ...place, ...this.picture(asset), ScaleType: enumItem('Enum.ScaleType.Fit') }, children);
  }
  icon(name: string, key: string, place: P): Spec {
    return this.fit(name, iconAsset(key)!, place);
  }
  /** Text in the skin's font, inked for the surface it sits on (the surface's own measured verdict). */
  label(name: string, text: string, on: string | null, place: P, max = 30): Spec {
    const surface = on ? L.images[on]! : null;
    const light = !surface || surface.text === 'light';
    return this.spec('TextLabel', name, {
      ...place,
      BackgroundTransparency: num(1),
      Text: str(text),
      Font: enumItem(this.font),
      TextColor3: rgb(light ? L.ink.ink_light : L.ink.ink_dark),
      TextScaled: bool(true),
      TextWrapped: bool(true),
      ...(light ? { TextStrokeTransparency: num(0), TextStrokeColor3: rgb(surface ? surface.edge : L.ink.ink_dark) } : {}),
    }, [this.spec('UITextSizeConstraint', 'TextLimit', { MinTextSize: num(10), MaxTextSize: num(max) })]);
  }

  /* -------- shared pieces -------- */

  /** A chip: rounded pill with an icon on the left and one line of text. */
  chip(name: string, iconKey: string, text: string, place: P): Spec {
    const chip = this.role('chip');
    return this.slice(name, 'chip', place, [
      this.icon('Icon', iconKey, box(0.04, 0.5, 0.26, 0.8, 0, 0.5)),
      this.label('Value', text, chip, box(0.32, 0.5, 0.64, 0.7, 0, 0.5)),
    ]);
  }
  button(name: string, role: 'button_primary' | 'button_secondary', text: string, place: P, iconKey?: string): Spec {
    const asset = this.role(role);
    const kids = iconKey
      ? [this.icon('Icon', iconKey, box(0.06, 0.5, 0.22, 0.7, 0, 0.5)), this.label('Label', text, asset, box(0.3, 0.5, 0.64, 0.62, 0, 0.5))]
      : [this.label('Label', text, asset, box(0.5, 0.5, 0.86, 0.62, 0.5, 0.5))];
    return this.slice(name, role, place, kids, true);
  }
  bar(name: string, fillRole: 'bar_fill' | 'bar_health', value: number, text: string | null, place: P): Spec {
    const track = this.role('bar_track');
    const v = Math.max(0, Math.min(1, value));
    return this.slice(name, 'bar_track', place, [
      this.slice('Fill', fillRole, box(0, 0, v, 1)),
      ...(text !== null ? [this.label('Value', text, track, box(0.5, 0.5, 0.9, 0.7, 0.5, 0.5))] : []),
    ]);
  }
  close(place: P): Spec {
    const asset = this.role('button_close');
    // Some packs draw the X into the close button itself; only a plain button gets the cross icon.
    const drawn = /close|cross/i.test(asset.slice(asset.lastIndexOf('/')));
    return this.fit('Close', asset, place, [...(drawn ? [] : [this.icon('Icon', 'cross', box(0.5, 0.45, 0.5, 0.5, 0.5, 0.5))]), this.aspect(1)], true);
  }
  /** Panel + header title (+ optional header icon) + close button; `content` fills the body. */
  window(title: string, content: Spec[], opts: { close?: boolean; headerIcon?: string } = {}): Spec {
    const header = this.role('header');
    const head = this.slice('Header', 'header', box(0.5, 0.025, 0.62, 0.13, 0.5, 0), [
      ...(opts.headerIcon ? [this.icon('Icon', opts.headerIcon, box(0.05, 0.5, 0.14, 0.78, 0, 0.5))] : []),
      this.label('Title', title, header, opts.headerIcon ? box(0.2, 0.5, 0.74, 0.7, 0, 0.5) : box(0.5, 0.5, 0.9, 0.7, 0.5, 0.5), 40),
    ]);
    return this.slice(this.input.name, 'panel', {}, [
      head,
      ...(opts.close === false ? [] : [this.close(box(0.975, 0.025, 0.1, 0.13, 1, 0))]),
      this.frame('Content', box(0.5, 0.19, 0.9, 0.77, 0.5, 0), content),
    ]);
  }
  /** A scrolling grid of cells, three across, two rows visible. */
  grid(cells: Spec[], cols = 3, visibleRows = 2): Spec {
    const rows = Math.max(visibleRows, Math.ceil(cells.length / cols));
    return this.spec('ScrollingFrame', 'Grid', {
      ...box(0, 0, 1, 1), BackgroundTransparency: num(1), BorderSizePixel: num(0), ScrollBarThickness: num(6),
      CanvasSize: udim2(0, 0, r3(rows / visibleRows), 0),
    }, [
      this.spec('UIGridLayout', 'Layout', {
        CellSize: udim2(r3(0.94 / cols), 0, r3(0.9 / rows), 0), CellPadding: udim2(r3(0.05 / cols), 0, r3(0.08 / rows), 0),
        SortOrder: enumItem('Enum.SortOrder.LayoutOrder'), HorizontalAlignment: enumItem('Enum.HorizontalAlignment.Center'),
      }),
      ...cells,
    ]);
  }
  /** Rows stacked top to bottom. */
  rows(children: Spec[], gap = 0.02): Spec {
    return this.frame('Rows', box(0, 0, 1, 1), [
      this.spec('UIListLayout', 'Layout', {
        FillDirection: enumItem('Enum.FillDirection.Vertical'), HorizontalAlignment: enumItem('Enum.HorizontalAlignment.Center'),
        SortOrder: enumItem('Enum.SortOrder.LayoutOrder'), Padding: udim(gap, 0),
      }),
      ...children.map((c, i) => ({ ...c, props: { ...c.props, LayoutOrder: num(i + 1) } })),
    ]);
  }
  toggle(name: string, on: boolean, place: P): Spec {
    const onA = this.role('toggle_on');
    const offA = this.role('toggle_off');
    this.picture(onA); this.picture(offA);
    const t = this.fit(name, on ? onA : offA, place, [], true);
    // A script flips it with btn.Image = btn:GetAttribute(on and "OnImage" or "OffImage"): both
    // states stay library files, and the script never names an image.
    t.attributes = { OnImage: str(`rbxassetid://${this.idOf(onA)}`), OffImage: str(`rbxassetid://${this.idOf(offA)}`), On: bool(on) };
    return t;
  }
  slider(name: string, value: number, place: P): Spec {
    const v = Math.max(0, Math.min(1, value));
    return this.slice(name, 'slider_track', place, [
      this.fit('Handle', this.role('slider_handle'), box(v, 0.5, 1.6, 1.6, 0.5, 0.5), [this.aspect(1)], true),
    ]);
  }
  dropdown(name: string, options: string[], selected: number, place: P): Spec {
    const input = this.role('input');
    return this.slice(name, 'input', place, [
      this.label('Value', options[selected] ?? options[0] ?? '', input, box(0.06, 0.5, 0.7, 0.62, 0, 0.5)),
      this.fit('Arrow', this.role('dropdown_arrow'), box(0.95, 0.5, 0.16, 0.6, 1, 0.5), [this.aspect(1)], true),
      this.frame('Options', { ...box(0, 1.05, 1, options.length, 0, 0), Visible: bool(false) }, [
        this.spec('UIListLayout', 'Layout', { FillDirection: enumItem('Enum.FillDirection.Vertical'), SortOrder: enumItem('Enum.SortOrder.LayoutOrder') }),
        ...options.map((o, i) => this.slice(`Option${i + 1}`, 'input', { ...sized(1, r3(1 / options.length)), LayoutOrder: num(i + 1) }, [
          this.label('Label', o, input, box(0.06, 0.5, 0.88, 0.62, 0, 0.5)),
        ], true)),
      ]),
    ]);
  }
}

/* ------------------------------------------------------------------- components --- */

const n = (v: unknown, d: number): number => (typeof v === 'number' && Number.isFinite(v) ? v : d);
const s = (v: unknown, d: string): string => (typeof v === 'string' && v.length ? v : typeof v === 'number' ? String(v) : d);
const items = (a: Input, d: Item[]): Item[] => (a.items && a.items.length ? a.items : d);

/** Each component's tree (root props without placement) and its default screen size and anchor. */
const BUILD: Record<string, { size: [number, number]; anchor: Anchor; build: (b: Builder, a: Input) => Spec }> = {
  currency_counter: { size: [0.17, 0.075], anchor: 'top_left', build: (b, a) => b.chip(a.name, a.icon ?? 'coin', s(a.value, '0'), {}) },
  stat_counter: { size: [0.17, 0.075], anchor: 'left', build: (b, a) => b.chip(a.name, a.icon ?? 'star', `${s(a.text, 'Level')}: ${s(a.value, '1')}`, {}) },
  health_bar: {
    size: [0.3, 0.06], anchor: 'bottom',
    build: (b, a) => b.frame(a.name, {}, [
      b.icon('Icon', a.icon ?? 'heart', box(0, 0.5, 0.14, 1.2, 0, 0.5)),
      b.bar('Bar', 'bar_health', n(a.value, 1), s(a.text, `${Math.round(n(a.value, 1) * 100)} / 100`), box(1, 0.5, 0.84, 1, 1, 0.5)),
    ]),
  },
  progress_bar: { size: [0.4, 0.055], anchor: 'top', build: (b, a) => b.bar(a.name, 'bar_fill', n(a.value, 0.5), s(a.text, 'Progress'), {}) },
  level_bar: {
    size: [0.36, 0.08], anchor: 'top',
    build: (b, a) => b.frame(a.name, {}, [
      b.fit('Level', b.role('button_icon'), box(0, 0.5, 0.2, 1, 0, 0.5), [b.label('Value', s(a.text, '1'), b.role('button_icon'), box(0.5, 0.45, 0.7, 0.6, 0.5, 0.5)), b.aspect(1)]),
      b.bar('Bar', 'bar_fill', n(a.value, 0.4), `XP ${Math.round(n(a.value, 0.4) * 100)}%`, box(1, 0.5, 0.8, 0.7, 1, 0.5)),
    ]),
  },
  timer: { size: [0.15, 0.075], anchor: 'top', build: (b, a) => b.chip(a.name, a.icon ?? 'timer', s(a.text ?? a.value, '01:30'), {}) },
  minimap_frame: {
    size: [0.17, 0.3], anchor: 'top_right',
    build: (b, a) => b.fit(a.name, b.role('minimap_ring'), {}, [b.fit('Player', b.role('minimap_arrow'), box(0.5, 0.5, 0.14, 0.14, 0.5, 0.5)), b.aspect(1)]),
  },
  notification_toast: {
    size: [0.36, 0.085], anchor: 'top',
    build: (b, a) => b.slice(a.name, 'toast', {}, [
      b.icon('Icon', a.icon ?? 'info', box(0.03, 0.5, 0.12, 0.7, 0, 0.5)),
      b.label('Value', s(a.text, 'Reward claimed!'), b.role('toast'), box(0.17, 0.5, 0.8, 0.62, 0, 0.5)),
    ]),
  },
  tooltip: { size: [0.22, 0.08], anchor: 'center', build: (b, a) => b.slice(a.name, 'tooltip', {}, [b.label('Value', s(a.text, 'Tap to collect'), b.role('tooltip'), box(0.5, 0.5, 0.88, 0.62, 0.5, 0.5))]) },
  button_primary: { size: [0.2, 0.1], anchor: 'bottom', build: (b, a) => b.button(a.name, 'button_primary', s(a.text, 'Play'), {}, a.icon) },
  button_secondary: { size: [0.2, 0.1], anchor: 'bottom', build: (b, a) => b.button(a.name, 'button_secondary', s(a.text, 'Back'), {}, a.icon) },
  button_icon: {
    size: [0.07, 0.125], anchor: 'right',
    build: (b, a) => b.fit(a.name, b.role('button_icon'), {}, [b.icon('Icon', a.icon ?? 'gear', box(0.5, 0.45, 0.56, 0.56, 0.5, 0.5)), b.aspect(1)], true),
  },
  button_close: { size: [0.06, 0.105], anchor: 'top_right', build: (b, a) => ({ ...b.close({}), name: a.name }) },
  tab_bar: {
    size: [0.42, 0.085], anchor: 'top',
    build: (b, a) => {
      const tabs = items(a, [{ name: 'Shop' }, { name: 'Pets' }, { name: 'Codes' }]);
      const sel = n(a.value, 0);
      return b.frame(a.name, {}, [
        b.spec('UIListLayout', 'Layout', { FillDirection: enumItem('Enum.FillDirection.Horizontal'), HorizontalAlignment: enumItem('Enum.HorizontalAlignment.Center'), SortOrder: enumItem('Enum.SortOrder.LayoutOrder'), Padding: udim(0.02, 0) }),
        ...tabs.map((t, i) => {
          const role = i === sel ? 'tab_on' : 'tab_off';
          const tab = b.slice(`Tab${i + 1}`, role, { ...sized(r3(0.96 / tabs.length - 0.02), 1), LayoutOrder: num(i + 1) }, [b.label('Label', s(t.name, `Tab ${i + 1}`), b.role(role), box(0.5, 0.5, 0.86, 0.6, 0.5, 0.5))], true);
          b.picture(b.role('tab_on')); b.picture(b.role('tab_off'));
          tab.attributes = { OnImage: str(`rbxassetid://${b.idOf(b.role('tab_on'))}`), OffImage: str(`rbxassetid://${b.idOf(b.role('tab_off'))}`) };
          return tab;
        }),
      ]);
    },
  },
  item_card: { size: [0.16, 0.38], anchor: 'center', build: (b, a) => card(b, a.name, { name: s(a.text, 'Speed Boost'), price: s(a.value, '100'), icon: a.icon }) },
  shop_window: {
    size: [0.62, 0.74], anchor: 'center',
    build: (b, a) => {
      const def = ['Speed Boost', 'Jump Boost', 'Lucky Egg', 'Coin Magnet', 'Double Coins', 'VIP'].map((name, i) => ({ name, price: [100, 250, 500, 1000, 2500, 5000][i] }));
      return b.window(s(a.title, 'Shop'), [b.grid(items(a, def).map((it, i) => card(b, `Item${i + 1}`, it, { LayoutOrder: num(i + 1) })))]);
    },
  },
  inventory_grid: {
    size: [0.62, 0.74], anchor: 'center',
    build: (b, a) => {
      const def = Array.from({ length: 8 }, (_, i) => ({ name: `Pet ${i + 1}`, locked: i >= 5 }));
      const cardA = b.role('card');
      return b.window(s(a.title, 'Pets'), [b.grid(items(a, def).map((it, i) => b.slice(`Slot${i + 1}`, 'card', { LayoutOrder: num(i + 1) }, [
        b.icon('Icon', it.icon ?? 'pet', box(0.5, 0.1, 0.6, 0.55, 0.5, 0)),
        b.label('Label', s(it.name, `Slot ${i + 1}`), cardA, box(0.5, 0.94, 0.9, 0.22, 0.5, 1)),
        ...(it.locked ? [b.icon('Locked', 'lock', box(0.94, 0.06, 0.28, 0.28, 1, 0))] : []),
      ], true)), 4)]);
    },
  },
  toggle: {
    size: [0.26, 0.075], anchor: 'center',
    build: (b, a) => b.frame(a.name, {}, [b.label('Label', s(a.text, 'Music'), null, box(0, 0.5, 0.62, 0.8, 0, 0.5)), b.toggle('Toggle', a.value !== false, box(1, 0.5, 0.34, 1, 1, 0.5))]),
  },
  slider: {
    size: [0.34, 0.07], anchor: 'center',
    build: (b, a) => b.frame(a.name, {}, [b.label('Label', s(a.text, 'Volume'), null, box(0, 0.5, 0.34, 0.8, 0, 0.5)), b.slider('Slider', n(a.value, 0.5), box(1, 0.5, 0.6, 0.45, 1, 0.5))]),
  },
  dropdown: {
    size: [0.34, 0.075], anchor: 'center',
    build: (b, a) => b.frame(a.name, {}, [
      b.label('Label', s(a.text, 'Graphics'), null, box(0, 0.5, 0.36, 0.8, 0, 0.5)),
      b.dropdown('Dropdown', (a.items ?? []).map((i) => s(i.name, '')).filter(Boolean).concat(a.items?.length ? [] : ['Low', 'Medium', 'High']), n(a.value, 0), box(1, 0.5, 0.6, 1, 1, 0.5)),
    ]),
  },
  settings_window: {
    size: [0.5, 0.68], anchor: 'center',
    build: (b, a) => {
      const def: Item[] = [{ name: 'Music', kind: 'toggle', value: true }, { name: 'Sound effects', kind: 'toggle', value: true }, { name: 'Volume', kind: 'slider', value: 0.7 }, { name: 'Graphics', kind: 'dropdown', options: ['Low', 'Medium', 'High'] }];
      const list = items(a, def);
      const h = r3(Math.min(0.2, 0.9 / list.length));
      return b.window(s(a.title, 'Settings'), [b.rows(list.map((it, i) => {
        const control = it.kind === 'slider' ? b.slider('Control', n(it.value, 0.5), box(1, 0.5, 0.45, 0.4, 1, 0.5))
          : it.kind === 'dropdown' ? b.dropdown('Control', it.options?.length ? it.options : ['Low', 'Medium', 'High'], n(it.value, 0), box(1, 0.5, 0.45, 0.8, 1, 0.5))
            : b.toggle('Control', it.value !== false, box(1, 0.5, 0.22, 0.8, 1, 0.5));
        return b.frame(`Row${i + 1}`, sized(1, h), [b.label('Label', s(it.name, `Option ${i + 1}`), b.role('panel'), box(0, 0.5, 0.5, 0.6, 0, 0.5)), control]);
      }))]);
    },
  },
  dialog_confirm: {
    size: [0.42, 0.42], anchor: 'center',
    build: (b, a) => {
      const [yes, no] = items(a, [{ name: 'Yes' }, { name: 'No' }]);
      return b.window(s(a.title, 'Confirm'), [
        b.label('Message', s(a.text, 'Are you sure?'), b.role('panel'), box(0.5, 0, 0.94, 0.5, 0.5, 0)),
        b.button('Confirm', 'button_primary', s(yes?.name, 'Yes'), box(0.26, 0.96, 0.42, 0.3, 0.5, 1)),
        b.button('Cancel', 'button_secondary', s(no?.name, 'No'), box(0.74, 0.96, 0.42, 0.3, 0.5, 1)),
      ], { close: false });
    },
  },
  rebirth_panel: {
    size: [0.44, 0.58], anchor: 'center',
    build: (b, a) => b.window(s(a.title, 'Rebirth'), [
      b.chip('Reward', 'rebirth', s(a.text, 'x2 coins forever'), box(0.5, 0.04, 0.8, 0.22, 0.5, 0)),
      b.chip('Cost', 'coin', s(a.value, '1M'), box(0.5, 0.34, 0.6, 0.22, 0.5, 0)),
      b.button('Rebirth', 'button_primary', 'Rebirth', box(0.5, 0.97, 0.6, 0.26, 0.5, 1)),
    ]),
  },
  daily_reward: {
    size: [0.62, 0.62], anchor: 'center',
    build: (b, a) => {
      const claimed = n(a.value, 2);
      const days = items(a, Array.from({ length: 7 }, (_, i) => ({ name: `Day ${i + 1}` })));
      const cardA = b.role('card');
      return b.window(s(a.title, 'Daily Rewards'), [
        b.frame('Days', box(0, 0, 1, 0.72), [
          b.spec('UIGridLayout', 'Layout', { CellSize: udim2(0.22, 0, 0.46, 0), CellPadding: udim2(0.03, 0, 0.06, 0), SortOrder: enumItem('Enum.SortOrder.LayoutOrder'), HorizontalAlignment: enumItem('Enum.HorizontalAlignment.Center') }),
          ...days.map((d, i) => b.slice(`Day${i + 1}`, 'card', { LayoutOrder: num(i + 1) }, [
            b.icon('Icon', d.icon ?? 'gift', box(0.5, 0.12, 0.6, 0.5, 0.5, 0)),
            b.label('Label', s(d.name, `Day ${i + 1}`), cardA, box(0.5, 0.94, 0.9, 0.24, 0.5, 1)),
            ...(i < claimed ? [b.icon('Claimed', 'check', box(0.94, 0.06, 0.3, 0.3, 1, 0))] : []),
          ])),
        ]),
        b.button('Claim', 'button_primary', 'Claim', box(0.5, 1, 0.4, 0.22, 0.5, 1)),
      ]);
    },
  },
  codes_entry: {
    size: [0.42, 0.44], anchor: 'center',
    build: (b, a) => b.window(s(a.title, 'Codes'), [
      b.slice('Input', 'input', box(0.5, 0.08, 0.94, 0.3, 0.5, 0), [
        b.icon('Icon', 'key', box(0.03, 0.5, 0.12, 0.7, 0, 0.5)),
        b.spec('TextBox', 'Code', {
          ...box(0.17, 0.5, 0.8, 0.62, 0, 0.5), BackgroundTransparency: num(1), Text: str(''), PlaceholderText: str(s(a.text, 'Enter code')),
          ClearTextOnFocus: bool(false), Font: enumItem(b.font), TextColor3: rgb(L.images[b.role('input')]!.text === 'light' ? L.ink.ink_light : L.ink.ink_dark), TextScaled: bool(true),
        }, [b.spec('UITextSizeConstraint', 'TextLimit', { MinTextSize: num(10), MaxTextSize: num(28) })]),
      ]),
      b.button('Redeem', 'button_primary', 'Redeem', box(0.5, 0.96, 0.5, 0.32, 0.5, 1)),
    ]),
  },
  leaderboard: {
    size: [0.26, 0.52], anchor: 'right',
    build: (b, a) => {
      const def = ['Player1', 'Player2', 'Player3', 'Player4', 'Player5'].map((name, i) => ({ name, value: 5000 - i * 900 }));
      const list = items(a, def).slice(0, 10);
      const cardA = b.role('card');
      return b.window(s(a.title, 'Leaderboard'), [b.rows(list.map((it, i) => b.slice(`Row${i + 1}`, 'card', sized(1, r3(0.9 / Math.max(5, list.length))), [
        i === 0 ? b.icon('Rank', 'crown', box(0.03, 0.5, 0.14, 0.8, 0, 0.5)) : b.label('Rank', `#${i + 1}`, cardA, box(0.03, 0.5, 0.14, 0.6, 0, 0.5)),
        b.label('Name', s(it.name, `Player${i + 1}`), cardA, box(0.2, 0.5, 0.5, 0.6, 0, 0.5)),
        b.label('Value', s(it.value, '0'), cardA, box(0.97, 0.5, 0.28, 0.6, 1, 0.5)),
      ])), 0.015)], { close: false, headerIcon: 'trophy' });
    },
  },
  quest_list: {
    size: [0.28, 0.48], anchor: 'left',
    build: (b, a) => {
      const def = [{ name: 'Collect 100 coins', value: 0.6 }, { name: 'Hatch 3 pets', value: 1 }, { name: 'Reach zone 2', value: 0.2 }];
      const list = items(a, def).slice(0, 8);
      const cardA = b.role('card');
      return b.window(s(a.title, 'Quests'), [b.rows(list.map((it, i) => b.slice(`Quest${i + 1}`, 'card', sized(1, r3(0.9 / Math.max(3, list.length))), [
        b.label('Name', s(it.name, `Quest ${i + 1}`), cardA, box(0.05, 0.08, 0.74, 0.42, 0, 0)),
        b.bar('Progress', 'bar_fill', n(it.value, 0), null, box(0.05, 0.9, 0.74, 0.3, 0, 1)),
        ...(n(it.value, 0) >= 1 ? [b.icon('Done', 'check', box(0.96, 0.5, 0.16, 0.7, 1, 0.5))] : []),
      ])), 0.02)], { close: false, headerIcon: 'quest' });
    },
  },
  loading_screen: {
    size: [1, 1], anchor: 'center',
    build: (b, a) => b.slice(a.name, 'panel', {}, [
      b.label('Title', s(a.title ?? a.text, 'Loading...'), b.role('panel'), box(0.5, 0.42, 0.6, 0.12, 0.5, 0.5), 64),
      b.bar('Bar', 'bar_fill', n(a.value, 0.3), null, box(0.5, 0.6, 0.5, 0.05, 0.5, 0.5)),
    ]),
  },
  main_menu: {
    size: [0.4, 0.72], anchor: 'center',
    build: (b, a) => {
      const list = items(a, [{ name: 'Play' }, { name: 'Shop' }, { name: 'Settings' }]).slice(0, 5);
      return b.frame(a.name, {}, [
        b.slice('Header', 'header', box(0.5, 0, 1, 0.24, 0.5, 0), [b.label('Title', s(a.title, 'My Game'), b.role('header'), box(0.5, 0.5, 0.9, 0.7, 0.5, 0.5), 64)]),
        b.frame('Buttons', box(0.5, 0.3, 0.8, 0.7, 0.5, 0), [
          b.spec('UIListLayout', 'Layout', { FillDirection: enumItem('Enum.FillDirection.Vertical'), HorizontalAlignment: enumItem('Enum.HorizontalAlignment.Center'), SortOrder: enumItem('Enum.SortOrder.LayoutOrder'), Padding: udim(0.04, 0) }),
          ...list.map((it, i) => b.button(s(it.name, '').replace(/\W+/g, '') || `Button${i + 1}`, i === 0 ? 'button_primary' : 'button_secondary', s(it.name, `Button ${i + 1}`), { ...sized(1, 0.2), LayoutOrder: num(i + 1) })),
        ]),
      ]);
    },
  },
  mobile_action_buttons: {
    size: [0.26, 0.4], anchor: 'bottom_right',
    build: (b, a) => {
      const keys = (a.items?.length ? a.items.map((i) => s(i.icon ?? i.name, '')) : ['jump', 'sword', 'fist']).slice(0, 4);
      const spots: [number, number, number][] = [[1, 1, 0.46], [0.5, 1, 0.34], [1, 0.48, 0.34], [0.5, 0.5, 0.28]];
      const icon = b.role('button_icon');
      return b.frame(a.name, {}, [
        ...keys.map((k, i) => {
          const [x, y, sz] = spots[i]!;
          return b.fit(`${k[0]?.toUpperCase() ?? 'B'}${k.slice(1).replace(/\W+/g, '')}Button`, icon, box(x, y, sz, sz * 0.66, 1, 1), [b.icon('Icon', k, box(0.5, 0.45, 0.56, 0.56, 0.5, 0.5)), b.aspect(1)], true);
        }),
      ]);
    },
  },
  crosshair: { size: [0.045, 0.08], anchor: 'center', build: (b, a) => b.fit(a.name, b.role('crosshair'), {}, [b.aspect(1)]) },
  ammo_counter: { size: [0.17, 0.08], anchor: 'bottom_right', build: (b, a) => b.chip(a.name, a.icon ?? 'target', s(a.text ?? a.value, '30 / 90'), {}) },
  billboard_tag: {
    size: [1, 1], anchor: 'center',
    build: (b, a) => b.spec('BillboardGui', a.name, {
      Size: udim2(5, 0, 1.4, 0), StudsOffset: vec3(0, 3, 0), AlwaysOnTop: bool(true), MaxDistance: num(120), LightInfluence: num(0),
    }, [b.chip('Tag', a.icon ?? 'coin', s(a.text ?? a.value, '100'), box(0, 0, 1, 1))]),
  },
  surface_sign: {
    size: [1, 1], anchor: 'center',
    build: (b, a) => b.spec('SurfaceGui', a.name, {
      SizingMode: enumItem('Enum.SurfaceGuiSizingMode.PixelsPerStud'), PixelsPerStud: num(50), LightInfluence: num(0),
    }, [b.slice('Sign', 'panel', box(0, 0, 1, 1), [
      b.slice('Header', 'header', box(0.5, 0.06, 0.8, 0.3, 0.5, 0), [b.label('Title', s(a.title, 'Welcome'), b.role('header'), box(0.5, 0.5, 0.9, 0.7, 0.5, 0.5), 100)]),
      b.label('Body', s(a.text, 'Touch to play'), b.role('panel'), box(0.5, 0.9, 0.86, 0.4, 0.5, 1), 80),
    ])]),
  },
};

function card(b: Builder, name: string, it: Item, place: P = {}): Spec {
  const cardA = b.role('card');
  return b.slice(name, 'card', place, [
    b.icon('Icon', it.icon ?? 'gift', box(0.5, 0.06, 0.62, 0.42, 0.5, 0)),
    b.label('Name', s(it.name, 'Item'), cardA, box(0.5, 0.52, 0.9, 0.14, 0.5, 0)),
    b.button('Buy', 'button_primary', s(it.price ?? it.value, 'Free'), box(0.5, 0.95, 0.86, 0.24, 0.5, 1), 'coin'),
  ]);
}

/* ------------------------------------------------------------------ arguments --- */

function iconAsset(key: string): string | null {
  if (L.icons[key]) return L.icons[key]!;
  // Any other library file may stand in for an icon, but only one the index names — a CC0 pack
  // file, or a Creator Store image already on Roblox (D-UISTORE-1).
  return libraryAsset(key)?.asset ?? uiStoreImage(key)?.image ?? null;
}

export interface Compiled {
  component: Component;
  skin: string;
  colour: string;
  name: string;
  world: boolean;
  item: Spec;
  assets: string[];
  count: number;
  size: [number, number];
  anchor: Anchor;
}

const refuse = (message: string) => ({ error: `${message} Nothing was sent to Studio.` });

function readInput(a: Args): Input | { error: string } {
  const component = COMPONENTS.get(String(a.component ?? ''));
  if (!component) return refuse(`component must be one of: ${UI_COMPONENT_IDS.join(', ')}.`);
  const genre = String(a.genre ?? '').toLowerCase().trim();
  const skin = GENRE_OF.get(genre);
  if (!skin) return refuse(`genre "${genre}" has no skin; use one of: ${[...GENRE_OF.keys()].join(', ')}.`);
  if (!component.genres.includes(skin)) {
    return refuse(`${component.id} is not in the ${skin} skin (it is in ${component.genres.join(', ')}). Use another component or genre.`);
  }
  const colours = L.skins[skin]!.colours;
  const colour = a.colour === undefined ? colours[0]! : String(a.colour).toLowerCase();
  if (!colours.includes(colour)) return refuse(`colour must be one of ${colours.join(', ')} for the ${skin} skin.`);
  const name = a.name === undefined ? component.id.split('_').map((w) => w[0]!.toUpperCase() + w.slice(1)).join('') : String(a.name);
  if (!/^[A-Za-z][A-Za-z0-9_]{0,49}$/.test(name)) return refuse('name must be 1-50 letters, digits or _, starting with a letter.');
  const text = (v: unknown, label: string, max: number): string | undefined | { error: string } => {
    if (v === undefined) return undefined;
    if (typeof v !== 'string' && typeof v !== 'number') return refuse(`${label} must be text.`);
    const t = String(v);
    return t.length > max ? refuse(`${label} is longer than ${max} characters.`) : t;
  };
  const title = text(a.title, 'title', 40);
  const body = text(a.text, 'text', 120);
  for (const t of [title, body]) if (t && typeof t === 'object') return t;
  if (a.icon !== undefined && !iconAsset(String(a.icon))) return refuse(`icon must be one of ${Object.keys(L.icons).join(', ')}, or a library asset from find_ui_asset.`);
  let list: Item[] | undefined;
  if (a.items !== undefined) {
    if (!Array.isArray(a.items) || a.items.length > 12) return refuse('items must be a list of at most 12 entries.');
    list = [];
    for (const [i, raw] of a.items.entries()) {
      const it: Item = typeof raw === 'string' || typeof raw === 'number' ? { name: String(raw) } : raw && typeof raw === 'object' ? { ...(raw as Item) } : {};
      if (it.name !== undefined && String(it.name).length > 40) return refuse(`items[${i}].name is longer than 40 characters.`);
      if (it.icon !== undefined && !iconAsset(String(it.icon))) return refuse(`items[${i}].icon must be one of ${Object.keys(L.icons).join(', ')}, or a library asset from find_ui_asset.`);
      if (it.options !== undefined && (!Array.isArray(it.options) || it.options.length > 8)) return refuse(`items[${i}].options must be at most 8 strings.`);
      list.push(it);
    }
    if (component.id === 'mobile_action_buttons') {
      for (const [i, it] of list.entries()) if (!iconAsset(s(it.icon ?? it.name, ''))) return refuse(`items[${i}] must name an icon (${Object.keys(L.icons).join(', ')}).`);
    }
  }
  const value = a.value;
  if (value !== undefined && !['number', 'string', 'boolean'].includes(typeof value)) return refuse('value must be a number, text or true/false.');
  return {
    component, skin, colour, name,
    title: title as string | undefined, text: body as string | undefined,
    value: value as Input['value'], items: list, icon: a.icon === undefined ? undefined : String(a.icon),
  };
}

function vecArg(v: unknown, label: string, lo: number): [number, number] | undefined | { error: string } {
  if (v === undefined) return undefined;
  if (!Array.isArray(v) || v.length !== 2 || !v.every((x) => typeof x === 'number' && x >= lo && x <= 1)) return refuse(`${label} must be [x, y], two fractions of the screen from ${lo} to 1.`);
  return v as [number, number];
}

/** Arguments -> one create_instances item (no parent yet), or what is wrong. `idOf` maps a library file to its Roblox id. */
export function compileComponent(a: Args, idOf: (asset: string) => string = () => '0'): Compiled | { error: string } {
  const input = readInput(a);
  if ('error' in input) return input;
  const recipe = BUILD[input.component.id]!;
  const size = vecArg(a.size, 'size', 0.02);
  if (size && 'error' in size) return size;
  const position = vecArg(a.position, 'position', 0);
  if (position && 'error' in position) return position;
  const anchor = (a.anchor === undefined ? recipe.anchor : String(a.anchor)) as Anchor;
  if (!ANCHORS.includes(anchor)) return refuse(`anchor must be one of ${ANCHORS.join(', ')}.`);
  const b = new Builder(input, idOf);
  const root = recipe.build(b, input);
  const world = WORLD.has(input.component.id);
  if (!world) {
    const [w, h] = (size as [number, number] | undefined) ?? recipe.size;
    const [ax, ay] = ANCHOR_POINTS[anchor];
    const [px, py] = (position as [number, number] | undefined) ?? [ax === 0 ? MARGIN : ax === 1 ? 1 - MARGIN : 0.5, ay === 0 ? MARGIN : ay === 1 ? 1 - MARGIN : 0.5];
    root.props = { ...root.props, ...box(px, py, w, h, ax, ay) };
    // The component keeps the shape it was drawn at on a 16:9 screen, whatever the device.
    if (!(w === 1 && h === 1) && !root.children?.some((c) => c.className === 'UIAspectRatioConstraint')) {
      root.children = [...(root.children ?? []), b.aspect((w * 16) / (h * 9))];
    }
  }
  return {
    component: input.component, skin: input.skin, colour: input.colour, name: input.name, world,
    item: root, assets: [...b.assets].sort(), count: b.count,
    size: (size as [number, number] | undefined) ?? recipe.size, anchor,
  };
}

/* --------------------------------------------------------------- image ids --- */

export type ResolveIds = (assets: string[]) => Promise<{ ids: Record<string, string>; missing: { asset: string; why: string }[] }>;

/** Shared table, then the user's cache, then an upload into the user's own account. */
export function uiImageResolver(env: Env, userId: string | undefined, deps: UploadDeps = {}): ResolveIds {
  return async (assets) => {
    const ids: Record<string, string> = {};
    const missing: { asset: string; why: string }[] = [];
    await Promise.all(assets.map(async (asset) => {
      if (SHARED_IDS[asset]) { ids[asset] = SHARED_IDS[asset]!; return; }
      // A Creator Store image is on Roblox already: its id is set as it is, never uploaded.
      const store = uiStoreImage(asset);
      if (store) { ids[asset] = String(store.imageId); return; }
      const key = userId ? `ui-image:${userId}:${asset}` : null;
      const cached = key ? await env.KV?.get(key).catch(() => null) : null;
      if (cached && /^\d+$/.test(cached)) { ids[asset] = cached; return; }
      const up = await uploadLibraryAsset(env, userId, { asset }, deps);
      if (typeof up.assetId === 'string' || typeof up.assetId === 'number') {
        ids[asset] = String(up.assetId);
        if (key) await env.KV?.put(key, ids[asset]!).catch(() => undefined);
        return;
      }
      missing.push({ asset, why: String(up.error ?? up.note ?? 'no id yet') });
    }));
    return { ids, missing };
  };
}

/* -------------------------------------------------------------------- the tool --- */

const GUI_CONTAINERS = new Set(['ScreenGui', 'Frame', 'ImageLabel', 'ImageButton', 'ScrollingFrame', 'CanvasGroup', 'SurfaceGui', 'BillboardGui']);

export const insertUiComponent = {
  def: {
    name: 'insert_ui_component',
    description:
      'The ONLY way to put game UI in the place (D-UIONLY-1): inserts one ready-made component from Apple\'s UI library, drawn entirely from stored library images (9-slice panels, buttons, bars, icons) in a genre skin, with the skin\'s font. ' +
      `component: ${UI_COMPONENT_IDS.join(', ')}. genre picks the skin: simulator/tycoon/clicker/pet, obby/parkour/tower, adventure/horror/rpg/survival, shooter/fps/fighting. ` +
      'colour picks the skin colour; title/text/value/items fill it in (items: strings, or {name, value, price, icon, locked, kind: toggle|slider|dropdown, options}); icon is an icon key (coin, gem, star, heart, gear, trophy, cart, lock, timer, rebirth, quest, key, gift, crown, sword, shield, jump, target, pet, ...). ' +
      'Without parent it becomes a new ScreenGui named `name` in StarterGui; parent may be an existing ScreenGui/Frame to nest it. billboard_tag and surface_sign need parent = the part. anchor/position/size are screen fractions. ' +
      'Afterwards change text/position/visibility with set_properties; wire behaviour in a LocalScript that finds the inserted instances by path. Creating Frames, buttons, labels or images any other way is refused.',
    parameters: {
      type: 'object',
      properties: {
        component: { type: 'string', enum: UI_COMPONENT_IDS },
        genre: { type: 'string', description: 'the game genre, e.g. simulator, obby, horror, shooter' },
        colour: { type: 'string', description: 'a colour of the skin (simulator/obby/shooter: green, blue, yellow, red; adventure: brown, grey)' },
        name: { type: 'string', description: 'instance name, e.g. "ShopGui"; must be free where it goes' },
        parent: { type: 'string', description: 'existing ScreenGui/Frame path to nest into, or the part for billboard_tag/surface_sign' },
        title: { type: 'string' },
        text: { type: 'string' },
        value: { description: 'number (bars 0-1, counters), text, or true/false (toggle)' },
        items: { type: 'array', maxItems: 12, items: {} },
        icon: { type: 'string' },
        anchor: { type: 'string', enum: [...ANCHORS] },
        position: { type: 'array', items: { type: 'number' }, minItems: 2, maxItems: 2 },
        size: { type: 'array', items: { type: 'number' }, minItems: 2, maxItems: 2 },
      },
      required: ['component', 'genre'],
    },
  } satisfies GatewayToolDef,

  run: async (call: OpCall, a: Args, resolve: ResolveIds): Promise<unknown> => {
    const plan = compileComponent(a);
    if ('error' in plan) return plan;
    const parent = a.parent === undefined ? null : String(a.parent).trim();
    if (parent !== null && !/^[A-Za-z0-9_.]+$/.test(parent)) return refuse(`"${parent}" is not an instance path.`);
    if (plan.world && !parent) return refuse(`${plan.component.id} goes on a part: pass parent, e.g. "game.Workspace.Shop.Sign".`);

    // Where it goes is checked before anything is uploaded or built.
    if (parent) {
      const where = await call({ op: 'get_instance', path: parent });
      const cls = where && typeof where === 'object' && !('error' in where) ? String((where as Args).class ?? '') : null;
      if (cls === null) return { ...(where as object), note: `Could not read ${parent}, so nothing was built.` };
      if (!plan.world && !GUI_CONTAINERS.has(cls)) return refuse(`${parent} is a ${cls}; a screen component nests only in ${[...GUI_CONTAINERS].join(', ')}. Leave parent out to make a new ScreenGui.`);
      if (plan.world && GUI_CONTAINERS.has(cls)) return refuse(`${parent} is a ${cls}; ${plan.component.id} goes on a part in the world.`);
      const clash = await call({ op: 'get_instance', path: `${parent}.${plan.name}` });
      const err = clash && typeof clash === 'object' && 'error' in clash ? String((clash as Args).error) : null;
      if (err === null) return refuse(`${parent}.${plan.name} already exists. Pick another name.`);
      if (!/\bnot found\b/i.test(err)) return { error: `Could not check whether ${parent}.${plan.name} is free (${err}), so nothing was built.` };
    } else {
      const existing = await call({ op: 'query_instances', root: 'game.StarterGui', className: 'ScreenGui', name: plan.name, limit: 50 });
      if (existing && typeof existing === 'object' && 'error' in existing) return { ...(existing as object), note: 'Could not check whether the screen name is free, so nothing was built.' };
      const taken = (((existing as Args).matches as Array<{ path?: unknown }> | undefined) ?? [])
        .some((m) => typeof m.path === 'string' && m.path.endsWith(`StarterGui.${plan.name}`));
      if (taken) return refuse(`game.StarterGui.${plan.name} already exists. Choose another name, or nest this component in it with parent.`);
    }

    const { ids, missing } = await resolve(plan.assets);
    if (missing.length) {
      return {
        error: `The component needs ${plan.assets.length} library images and ${missing.length} have no Roblox id yet, so nothing was built: ${missing.slice(0, 4).map((m) => `${m.asset} (${m.why})`).join('; ')}.`,
        missing: missing.map((m) => m.asset),
      };
    }
    const built = compileComponent(a, (asset) => ids[asset]!);
    if ('error' in built) return built;

    const full = !built.world && built.size[0] === 1 && built.size[1] === 1;
    const item: InstanceSpec = parent
      ? { ...built.item, parent }
      : {
        className: 'ScreenGui', name: built.name, parent: 'game.StarterGui',
        props: {
          ResetOnSpawn: bool(false), ZIndexBehavior: enumItem('Enum.ZIndexBehavior.Sibling'),
          ...(full ? { IgnoreGuiInset: bool(true), DisplayOrder: num(100) } : { ScreenInsets: enumItem('Enum.ScreenInsets.CoreUISafeInsets') }),
        },
        children: [built.item],
      };
    const made = await call({ op: 'create_instances', items: [item] } as StudioOp, 60_000);
    if (made && typeof made === 'object' && 'error' in made) return made;
    const created = (made as Args).created;
    const top = Array.isArray(created) && typeof created[0] === 'string' ? created[0] : parent ? `${parent}.${built.name}` : `game.StarterGui.${built.name}`;
    const root = parent ? top : `${top}.${built.name}`;
    const screen = parent ? (/^game\.StarterGui\.[A-Za-z0-9_]+/.exec(parent)?.[0] ?? null) : top;
    const layout = screen && !built.world ? await call({ op: 'ui_layout_check', screen }, 60_000) : null;
    return {
      inserted: root,
      component: built.component.id,
      skin: built.skin,
      colour: built.colour,
      instances: built.count + (parent ? 0 : 1),
      parts: partsOf(built.item, root),
      images: built.assets.map((asset) => ({ asset, id: ids[asset] })),
      projectMutated: true,
      ...(layout ? { layout: layout && typeof layout === 'object' && !('error' in layout) ? { verdict: (layout as Args).verdict, issues: (layout as Args).issues } : { notChecked: (layout as Args).error } } : {}),
      next: 'Change text, value and visibility with set_properties on the paths in `parts`; wire behaviour in a LocalScript that finds them by path. Toggles and tabs carry OnImage/OffImage attributes to swap Image with.',
      ...(made && typeof made === 'object' && 'propIssues' in made ? { propIssues: (made as Args).propIssues } : {}),
    };
  },
};

/** The paths a script or set_properties call needs: buttons, inputs, and the Value/Fill/Title pieces. */
function partsOf(root: Spec, rootPath: string): string[] {
  const out: string[] = [];
  const walk = (s: Spec, path: string) => {
    if (s.className === 'ImageButton' || s.className === 'TextBox' || ['Value', 'Fill', 'Title', 'Message', 'Body'].includes(s.name)) out.push(path);
    for (const c of s.children ?? []) walk(c, `${path}.${c.name}`);
  };
  walk(root, rootPath);
  return out.slice(0, 40);
}

/* ------------------------------------------------------------------ the rule --- */

/** GuiObjects, LayerCollectors and the styling objects that make a look: built by insert_ui_component only. */
export const UI_CLASSES: ReadonlySet<string> = new Set([
  'ScreenGui', 'SurfaceGui', 'BillboardGui', 'Frame', 'CanvasGroup', 'ScrollingFrame', 'TextLabel', 'TextButton', 'TextBox',
  'ImageLabel', 'ImageButton', 'ViewportFrame', 'VideoFrame', 'UIStroke', 'UICorner', 'UIGradient',
]);

const SUGGEST: Record<string, string> = {
  TextButton: 'button_primary', ImageButton: 'button_icon', TextLabel: 'stat_counter', ImageLabel: 'currency_counter', TextBox: 'codes_entry',
  ScrollingFrame: 'inventory_grid', BillboardGui: 'billboard_tag', SurfaceGui: 'surface_sign',
};

export const UI_RULE: LibraryRule = {
  decision: 'D-UIONLY-1',
  what: 'game UI',
  classes: UI_CLASSES,
  suggest: (cls) => {
    const id = SUGGEST[cls];
    if (cls === 'BillboardGui' || cls === 'SurfaceGui') return `insert_ui_component({"component":"${id}","genre":"<game genre>","parent":"<the part>"})`;
    if (id) return `insert_ui_component({"component":"${id}","genre":"<game genre>"})`;
    if (cls === 'UIStroke' || cls === 'UICorner' || cls === 'UIGradient') return 'nothing: a component\'s corners, outline and fill are its library images; pick another colour or genre skin in insert_ui_component instead';
    return `insert_ui_component({"component":"<one of ${UI_COMPONENT_IDS.join(', ')}>","genre":"<game genre>"})`;
  },
};

/** Properties that set how UI LOOKS. On inserted UI they come from the library, so they are not set by hand. */
export const UI_LOOK_PROPS: ReadonlySet<string> = new Set([
  'Image', 'HoverImage', 'PressedImage', 'ImageContent', 'ImageColor3', 'ImageRectOffset', 'ImageRectSize', 'SliceCenter', 'SliceScale', 'ScaleType', 'TileSize', 'ResampleMode',
  'BackgroundColor3', 'BorderColor3', 'TextColor3', 'TextStrokeColor3', 'PlaceholderColor3', 'Font', 'FontFace',
]);
const STYLE_CLASSES = new Set(['UIStroke', 'UICorner', 'UIGradient']);

/** A set_properties / set_properties_bulk that restyles UI by hand, or null. `className` when it is known. */
export function refuseUiLook(props: unknown, className?: string): { error: string } | null {
  if (!props || typeof props !== 'object') return null;
  const keys = Object.keys(props as object);
  const bad = className && STYLE_CLASSES.has(className) ? keys : keys.filter((k) => UI_LOOK_PROPS.has(k));
  if (!bad.length) return null;
  return {
    error:
      `Refused (D-UIONLY-1): ${bad.join(', ')} set how UI looks, and every look comes from the UI library. ` +
      'Pick a different colour or genre skin with insert_ui_component (and delete the old one); set_properties may still change Text, Position, Size, Visible, LayoutOrder and the like. Nothing was changed.',
  };
}
