// Behavioural boundary tests: no live Roblox requests, providers, D1, or asset uploads.
import test, { beforeEach, afterEach, mock } from 'node:test';
import assert from 'node:assert/strict';
import * as esbuild from 'esbuild';
import { mkdtempSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const TMP = mkdtempSync(join(tmpdir(), 'apple-preview-helper-'));
process.on('exit', () => rmSync(TMP, { force: true, recursive: true }));
const out = join(TMP, 'previews.mjs');
await esbuild.build({
  entryPoints: [join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'asset-catalog-previews.ts')],
  outfile: out, bundle: true, format: 'esm', platform: 'node', target: 'es2022',
});
const P = await import(pathToFileURL(out).href);
const NONE = { state: 'unavailable', url: null };
const previewUrl = (id) => `https://tr.rbxcdn.com/asset-${id}/150/150/Model/Png/noFilter`;
const row = (targetId, state = 'Completed', imageUrl = previewUrl(targetId)) => ({ targetId, state, imageUrl, version: 'TN3' });
const json = (data) => new Response(JSON.stringify({ data }), { headers: { 'Content-Type': 'application/json' } });
const hits = (...ids) => ids.map((robloxAssetId) => ({ robloxAssetId }));
const requested = [];
let reply;
let unexpected;
beforeEach(() => {
  requested.length = 0;
  unexpected = 0;
  reply = undefined;
  mock.method(globalThis, 'fetch', async (input, init) => {
    requested.push({ input, init });
    if (!reply) { unexpected++; throw new Error('unmocked network request'); }
    return reply(input, init);
  });
});
afterEach(() => {
  mock.restoreAll();
  assert.equal(unexpected, 0, 'caught fetch exceptions must not hide accidental network calls');
});

test('preview helper defaults off; no IDs, invalid IDs and explicit false make no requests', async () => {
  for (const enabled of [undefined, false]) {
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), enabled), [NONE]);
  }
  assert.deepEqual(await P.resolveAssetCatalogPreviews([], true), []);
  const invalid = hits(null, undefined, 0, -1, 1.5, NaN, Infinity, Number.MAX_SAFE_INTEGER + 1, '123', true);
  assert.deepEqual(await P.resolveAssetCatalogPreviews(invalid, true), invalid.map(() => NONE));
  assert.equal(requested.length, 0);
});

test('one fixed-origin GET batches at most 20 unique positive safe integers and omits credentials', async () => {
  const input = hits(null, -1, '23', 1, 1, ...Array.from({ length: 25 }, (_, i) => i + 2));
  reply = (input) => {
    const url = new URL(input);
    const ids = url.searchParams.get('assetIds').split(',').map(Number);
    assert.deepEqual(ids, Array.from({ length: 20 }, (_, i) => i + 1));
    return json(ids.reverse().map((id) => row(id)));
  };
  const previews = await P.resolveAssetCatalogPreviews(input, true);
  assert.equal(previews.length, input.length);
  for (let i = 0; i < input.length; i++) {
    const id = input[i].robloxAssetId;
    assert.deepEqual(previews[i], typeof id === 'number' && id >= 1 && id <= 20
      ? { state: 'ready', url: previewUrl(id) } : NONE);
  }
  assert.equal(requested.length, 1, 'not one request per hit or unbounded batches');
  const { input: target, init } = requested[0];
  const url = new URL(target);
  assert.equal(url.origin + url.pathname, 'https://thumbnails.roblox.com/v1/assets');
  assert.equal(url.searchParams.get('format'), 'Png');
  assert.equal(url.searchParams.get('size'), '150x150');
  assert.equal(url.searchParams.get('isCircular'), 'false');
  assert.ok(!/Force|AutoGenerated/.test(url.searchParams.get('returnPolicy') ?? ''));
  assert.equal(init.method, 'GET');
  assert.equal(init.credentials, 'omit');
  assert.equal(init.redirect, 'error');
  assert.equal(init.body, undefined);
  assert.ok(init.signal instanceof AbortSignal);
  assert.deepEqual([...new Headers(init.headers).keys()], ['accept']);
});

test('documented states map honestly; only Completed with a trusted URL becomes ready', async () => {
  const states = ['Completed', 'Pending', 'InReview', 'Blocked', 'Error', 'TemporarilyUnavailable', 'unknown'];
  reply = () => json(states.map((state, i) => row(i + 1, state)));
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(...states.map((_, i) => i + 1)), true), [
    { state: 'ready', url: previewUrl(1) },
    { state: 'pending', url: null }, { state: 'pending', url: null },
    { state: 'blocked', url: null }, NONE, NONE, NONE,
  ]);
});

test('missing/foreign targets and duplicate IDs cannot attach someone else\'s thumbnail', async () => {
  reply = () => json([row(999), row(3), row(1), row(1, 'Blocked')]);
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1, 2, 3), true), [NONE, NONE, { state: 'ready', url: previewUrl(3) }]);
  reply = () => json([row(1, 123), row(1)]);
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE], 'malformed first duplicate is still ambiguous');
});

test('malformed response envelopes and malformed consumed fields fail closed', async () => {
  for (const envelope of [null, [], {}, { data: null }, { data: {} }, { data: Array.from({ length: 21 }, (_, i) => row(i + 1)) }]) {
    reply = () => new Response(JSON.stringify(envelope), { headers: { 'Content-Type': 'application/json' } });
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  }
  for (const item of [null, [], 1, {}, row('1'), row(0), row(-1), row(1.1), row(1, 1), row(1, 'completed'),
    row(1, 'Completed', null), { ...row(1), imageUrl: undefined }, row(1, 'Completed', 123),
    { ...row(1), imageUrl: { url: previewUrl(1) } }, { ...row(1), version: {} }]) {
    reply = () => json([item]);
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE], JSON.stringify(item));
  }
});

test('URL boundary rejects HTTP, root/lookalike domains, credentials, ports, fragments, controls and normalization tricks', async () => {
  const invalid = [
    'http://tr.rbxcdn.com/a.png', '//tr.rbxcdn.com/a.png', 'data:image/png;base64,a',
    'https://rbxcdn.com/a.png', 'https://evilrbxcdn.com/a.png', 'https://tr.rbxcdn.com.evil.test/a.png',
    'https://rbxcdn.com@evil.test/a.png', 'https://user@tr.rbxcdn.com/a.png', 'https://:pass@tr.rbxcdn.com/a.png',
    'https://@tr.rbxcdn.com/a.png', 'https://tr.rbxcdn.com:443/a.png', 'https://tr.rbxcdn.com:/a.png',
    'https://tr.rbxcdn.com:8443/a.png', 'https://tr.rbxcdn.com/a.png#fragment', 'https://tr.rbxcdn.com/a.png#',
    'https://tr.rbxcdn.com./a.png', 'https://.rbxcdn.com/a.png', 'https://tr..rbxcdn.com/a.png',
    'https://-tr.rbxcdn.com/a.png', 'https://tr_.rbxcdn.com/a.png', 'https://%74r.rbxcdn.com/a.png',
    ' https://tr.rbxcdn.com/a.png', 'https://tr.rbxcdn.com/a.png ', 'https://tr.rbxcdn.com/a\nb.png',
    'https://tr.rbxcdn.com\\@evil.test/a.png', `https://tr.rbxcdn.com/${'x'.repeat(2050)}`,
  ];
  for (const imageUrl of invalid) {
    reply = () => json([row(1, 'Completed', imageUrl)]);
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE], imageUrl);
  }
  for (const imageUrl of [previewUrl(1), 'https://t7.rbxcdn.com/a.png', 'https://one.two.rbxcdn.com/a.png?size=150']) {
    reply = () => json([row(1, 'Completed', imageUrl)]);
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [{ state: 'ready', url: imageUrl }]);
  }
});

test('HTTP errors, redirects, wrong content type, parse failures and network rejection never escape or retry', async () => {
  const failures = [
    () => { throw new Error('network private-detail'); },
    () => new Response('rate limited', { status: 429 }),
    () => new Response(null, { status: 302, headers: { Location: 'https://evil.test/' } }),
    () => new Response(JSON.stringify({ data: [row(1)] }), { headers: { 'Content-Type': 'text/html' } }),
    () => new Response('{broken', { headers: { 'Content-Type': 'application/json' } }),
    () => new Response(null, { headers: { 'Content-Type': 'application/json' } }),
  ];
  for (const failure of failures) {
    reply = failure;
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  }
  assert.equal(requested.length, failures.length);
});

test('byte cap rejects declared and streamed overflow, including a lying small Content-Length', async () => {
  for (const declared of ['65537', '9007199254740993', '-1', 'not-a-number']) {
    reply = () => new Response(JSON.stringify({ data: [row(1)] }), {
      headers: { 'Content-Type': 'application/json', 'Content-Length': declared },
    });
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  }
  for (const declared of [undefined, '2']) {
    let cancelled = false;
    let chunks = 0;
    reply = () => new Response(new ReadableStream({
      pull(controller) { chunks++; controller.enqueue(new Uint8Array(8192).fill(32)); },
      cancel() { cancelled = true; },
    }), { headers: { 'Content-Type': 'application/json', ...(declared ? { 'Content-Length': declared } : {}) } });
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
    assert.equal(cancelled, true);
    assert.ok(chunks <= 11, `unbounded stream consumed ${chunks} chunks`);
  }
});

test('timeout covers a stalled fetch and aborts it; timeout is capped and its timer is cleared', async () => {
  let fire;
  let duration;
  let timerCleared = false;
  const token = {};
  mock.method(globalThis, 'setTimeout', (fn, ms) => { fire = fn; duration = ms; return token; });
  mock.method(globalThis, 'clearTimeout', (timer) => { if (timer === token) timerCleared = true; });
  let signal;
  reply = (_input, init) => { signal = init.signal; return new Promise(() => {}); };
  const pending = P.resolveAssetCatalogPreviews(hits(1), true);
  await Promise.resolve();
  assert.equal(typeof fire, 'function');
  assert.ok(duration > 0 && duration <= 3000);
  fire();
  assert.deepEqual(await pending, [NONE]);
  assert.equal(signal.aborted, true);
  assert.equal(timerCleared, true);
});

test('timeout also covers a stalled body after headers, cancelling the reader', async () => {
  let fire;
  let cancelled = false;
  let pullStarted;
  const pulling = new Promise((resolve) => { pullStarted = resolve; });
  mock.method(globalThis, 'setTimeout', (fn) => { fire = fn; return 1; });
  mock.method(globalThis, 'clearTimeout', () => {});
  reply = () => new Response(new ReadableStream({
    pull() { pullStarted(); return new Promise(() => {}); },
    cancel() { cancelled = true; },
  }), { headers: { 'Content-Type': 'application/json' } });
  const pending = P.resolveAssetCatalogPreviews(hits(1), true);
  await pulling;
  fire();
  assert.deepEqual(await pending, [NONE]);
  assert.equal(requested[0].init.signal.aborted, true);
  assert.equal(cancelled, true);
});

test('metadata keeps known values without mutation and bounds/sanitizes tags', () => {
  const value = { tags: [' crate ', 'crate', 'CRATE', '<b>low-poly</b>', 'a\u0000b', '\u202e', ...Array.from({ length: 30 }, (_, i) => `${i}-${'x'.repeat(100)}`)], triangles: 432, boundsStuds: [2, 3, 4] };
  const snapshot = structuredClone(value);
  const result = P.catalogAssetMetadata(value);
  assert.equal(result.triangles, 432);
  assert.deepEqual(result.boundsStuds, [2, 3, 4]);
  assert.ok(result.tags.length > 0 && result.tags.length <= 12);
  assert.deepEqual(result.tags.slice(0, 3), ['crate', 'low-poly', 'a b']);
  assert.ok(result.tags.every((tag) => tag.length <= 48 && tag.length > 0 && !/[<>\p{Cc}\p{Cf}]/u.test(tag)));
  assert.deepEqual(value, snapshot);
});

test('metadata treats malformed counts/dimensions as unknown, never coerces strings', () => {
  for (const triangles of [undefined, null, Infinity, NaN, -1, 0.1, '432', {}, Number.MAX_SAFE_INTEGER + 1]) {
    assert.equal(P.catalogAssetMetadata({ triangles }).triangles, null);
  }
  assert.equal(P.catalogAssetMetadata({ triangles: 0 }).triangles, 0);
  for (const boundsStuds of [undefined, null, [], [1, 2], [1, 2, 3, 4], [0, 1, 2], [0.01, 2, 3], [-1, 2, 3], [NaN, 2, 3], [Infinity, 2, 3], ['1', 2, 3], {}]) {
    assert.equal(P.catalogAssetMetadata({ boundsStuds }).boundsStuds, null);
  }
  for (const tags of [undefined, null, {}, 'tag', [null, 1, '', '<>', '\u202e']]) {
    assert.deepEqual(P.catalogAssetMetadata({ tags }).tags, []);
  }
});

test('body decoder handles split UTF-8 and rejects invalid encoding/read errors', async () => {
  const bytes = new TextEncoder().encode(JSON.stringify({ data: [row(1)], ignored: 'אב' }));
  reply = () => new Response(new ReadableStream({
    start(controller) {
      for (const byte of bytes) controller.enqueue(new Uint8Array([byte]));
      controller.close();
    },
  }), { headers: { 'Content-Type': 'application/json' } });
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [{ state: 'ready', url: previewUrl(1) }]);
  // The replacement character from permissive UTF-8 decoding would otherwise hide invalid bytes.
  const prefix = new TextEncoder().encode(`{"data":[${JSON.stringify(row(1))}],"ignored":"`);
  const invalidUtf8 = new Uint8Array([...prefix, 0xff, 34, 125]);
  reply = () => new Response(invalidUtf8, { headers: { 'Content-Type': 'application/json' } });
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  reply = () => new Response(new ReadableStream({
    pull(controller) { controller.error(new Error('private stream failure')); },
  }), { headers: { 'Content-Type': 'application/json' } });
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
});

test('empty-chunk stream cannot busy-loop past the byte/deadline guards', async () => {
  let chunks = 0;
  let cancelled = false;
  reply = () => new Response(new ReadableStream({
    pull(controller) { chunks++; controller.enqueue(new Uint8Array()); },
    cancel() { cancelled = true; },
  }), { headers: { 'Content-Type': 'application/json' } });
  assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  assert.ok(chunks <= 1025, `empty stream consumed ${chunks} chunks`);
  assert.equal(cancelled, true);
});

test('redirected responses and unexpected response origins cannot publish trusted-looking URLs', async () => {
  for (const metadata of [
    { redirected: true },
    { url: 'https://evil.example/v1/assets' },
    { url: 'https://thumbnails.roblox.com/v1/other' },
  ]) {
    reply = () => {
      const response = json([row(1)]);
      for (const [key, value] of Object.entries(metadata)) Object.defineProperty(response, key, { value });
      return response;
    };
    assert.deepEqual(await P.resolveAssetCatalogPreviews(hits(1), true), [NONE]);
  }
});

test('only literal true opts in and returned previews cannot mutate input hits or each other', async () => {
  const input = Object.freeze(hits(1, null).map(Object.freeze));
  assert.deepEqual(await P.resolveAssetCatalogPreviews(input, 'true'), [NONE, NONE]);
  assert.equal(requested.length, 0);
  reply = () => json([]);
  const result = await P.resolveAssetCatalogPreviews(input, true);
  result[0].state = 'ready';
  assert.deepEqual(result[1], NONE);
  assert.ok(input.every((hit) => !Object.hasOwn(hit, 'preview')));
});
