// THE CURATION ONLY COUNTS AT THE PLACE THE AGENT TOUCHES IT.
//
// tests/template-curation.test.mjs proves the curator excludes macros, executors and account
// generators. That is a test of a script that runs on a laptop. The thing a customer can reach is
// `find_mechanic` in the worker, and between the two sits a generated table — so a rule that fires
// correctly in the curator and a table built before that rule existed would both be "passing".
//
// This is the test at the boundary: every repository REACHABLE THROUGH THE TOOL is re-judged here,
// live, against the same rules, from the committed harvest. If the exclusion is weakened, or the
// table is regenerated by a curator that lost a rule, or someone hand-edits a row back in, this
// goes red and names the repository.
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { curate } from '../../../scripts/lib/template-curation.mjs';

const WORKER = join(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = join(WORKER, '..', '..');
const tmp = mkdtempSync(join(tmpdir(), 'mech-'));
const bundle = async (entry) => {
  const out = join(tmp, `${entry}.mjs`);
  execFileSync(join(WORKER, 'node_modules', '.bin', 'esbuild'),
    [join(WORKER, 'src', `${entry}.ts`), '--bundle', '--format=esm', '--target=es2022', '--outfile=' + out],
    { cwd: WORKER, stdio: 'pipe' });
  return import(`file://${out}`);
};
// tools.ts for the registry and the tool; mechanics.ts for the pattern table it reads. Bundled
// apart so proving the library's shape does not require tools.ts to re-export it.
const T = await bundle('tools');
const M = await bundle('mechanics');

const HARVEST = JSON.parse(readFileSync(join(ROOT, 'packages', 'corpus', 'data', 'template-seeds.json'), 'utf8'));
const harvested = new Map(HARVEST.templates.map((t) => [t.fullName, t]));
const CITATIONS = JSON.parse(
  readFileSync(join(WORKER, 'src', 'mechanic-citations.ts'), 'utf8')
    .replace(/[\s\S]*MECHANIC_CITATIONS: readonly MechanicCitation\[\] = /, '')
    .replace(/;\s*$/, ''),
);

const call = (args) => T.TOOLS.find_mechanic.run({}, args);

/* -------------------------------------------------------------- the tool exists and is offered --- */

test('find_mechanic is registered, and offered when Studio is not connected', () => {
  assert.ok(T.toolNames().includes('find_mechanic'),
    `not registered. Registered: ${T.toolNames().join(', ')}`);
  const unpaired = T.toolDefs(false).map((d) => d.name);
  assert.ok(unpaired.includes('find_mechanic'),
    'reading how someone else built a round system needs no Studio — a planning session must be able to ask');
});

/* ------------------------------------------------------------------------- the abuse boundary --- */

test('NOT ONE repository reachable through find_mechanic is a macro, an executor or an account generator', () => {
  assert.ok(CITATIONS.length > 20, `the citation table parsed to ${CITATIONS.length} rows — the test is reading the wrong thing`);
  const reachable = new Set();
  for (const p of M.MECHANIC_PATTERNS) {
    const answer = M.answerFor(p, 1000);
    for (const impl of answer.implementations) reachable.add(impl.repo);
  }
  assert.ok(reachable.size > 20, `only ${reachable.size} repositories are reachable — nothing was measured`);

  for (const repo of reachable) {
    const row = harvested.get(repo);
    assert.ok(row, `${repo} is offered by the tool but is not in the committed harvest — it came from somewhere unaudited`);
    const verdict = curate(row);
    assert.notEqual(verdict.exclusion?.class, 'abuse',
      `${repo} is REACHABLE BY THE AGENT and the curator calls it ${verdict.exclusion?.rule}: ${verdict.exclusion?.matched}`);
  }
});

test('a customer asking for the thing by its own name gets a mechanic, never the exploit that shares the word', async () => {
  // These are queries a real builder types. Each contains a word that appears in the harvest
  // attached to an exploit: "aim" (aimbot), "farm" (autofarm), "speed" (speed hack).
  for (const query of ['an anticheat for walkspeed', 'a farming tycoon dropper', 'aim down sights weapon']) {
    const res = await call({ mechanic: query });
    const repos = (res.mechanics ?? []).flatMap((m) => m.implementations.map((i) => i.repo));
    for (const repo of repos) {
      assert.notEqual(curate(harvested.get(repo)).exclusion?.class, 'abuse', `"${query}" surfaced ${repo}`);
    }
  }
});

/* ---------------------------------------------------------- what the agent actually gets back --- */

test('the answer is the PATTERN — what it is, where authority lives, the current calls, the ways it breaks', async () => {
  const res = await call({ mechanic: 'save player coins between sessions' });
  const top = res.mechanics?.[0];
  assert.ok(top, `nothing matched: ${JSON.stringify(res).slice(0, 300)}`);
  assert.match(top.mechanic, /sav|data/i);
  assert.ok(top.what.length > 40, 'a mechanic with no description is a repository name again');
  assert.match(top.authority, /server/i, 'a save the client can dictate is not a save');
  assert.ok(top.currentApi.some((c) => /UpdateAsync/.test(c)), `the current call is missing: ${top.currentApi}`);
  assert.ok(top.pitfalls.length >= 3, 'the pitfalls are the part a repository name cannot carry');
});

test('the licence and the author travel with every implementation, and the answer forbids copying', async () => {
  const res = await call({ mechanic: 'a shop that sells with gamepasses' });
  const impls = res.mechanics.flatMap((m) => m.implementations);
  assert.ok(impls.length, 'no implementation cited for a shop');
  for (const i of impls) {
    assert.ok(i.author && i.url && i.licence, `${i.repo} is cited without author, url or licence`);
    assert.ok(i.licenceGuidance.length > 30, `${i.repo} carries a licence nobody is told what to do with`);
    assert.match(i.evidence, /\.(lua|luau)$|\.(lua|luau) /i, `${i.repo}'s evidence is "${i.evidence}" — not a path in its tree`);
  }
  assert.match(res.mechanics[0].vendoring, /not copy|do not copy/i);
});

test('a copyleft citation says what copying it would cost, in the customer\'s terms', () => {
  assert.match(M.licenceGuidance('GPL-3.0'), /whole game/i);
  assert.match(M.licenceGuidance('MIT'), /permissive/i);
  assert.match(M.licenceGuidance('NOASSERTION'), /Do not copy/i);
});

test('NOTHING IS VENDORED: the shipped table carries no Luau', () => {
  const src = readFileSync(join(WORKER, 'src', 'mechanic-citations.ts'), 'utf8');
  for (const tell of [/\blocal\s+\w+\s*=/, /\bfunction\s*\(/, /:GetService\(/, /\bend\b\s*\)/]) {
    assert.doesNotMatch(src, tell, `the citation table contains Luau (${tell}) — this file is a bibliography`);
  }
});

/* ------------------------------------------------------------ a failure to find is not silence --- */

test('an unknown mechanic returns the MENU, not an empty list that reads like "none exist"', async () => {
  const res = await call({ mechanic: 'a holographic pachinko machine' });
  assert.equal(res.mechanics, undefined);
  assert.ok(res.noMatch, `${JSON.stringify(res).slice(0, 200)}`);
  assert.ok(res.known.length > 20, 'the agent has to be told what it CAN ask for');
});

test('a mechanic with no surviving implementation says so, with the number searched', async () => {
  // racing_track is the one pattern the curation left with zero repositories. An empty list that
  // did not say "I read 131 and none of them had this" would read as a lookup that failed.
  const pattern = M.MECHANIC_PATTERNS.find((p) => p.id === 'racing_track');
  assert.ok(pattern, 'racing_track is gone — pick another empty mechanic or delete this test');
  const answer = M.answerFor(pattern);
  assert.equal(answer.implementations.length, 0);
  assert.ok(answer.searchedRepositories > 100, 'the denominator is the whole point of an empty answer');
  assert.ok(answer.what.length > 40, 'and the pattern is still delivered — no citation is not no answer');
});
