import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'owner-evidence-'));test.after(()=>rmSync(dir,{recursive:true,force:true}));await build({entryPoints:['src/tools.ts'],bundle:true,format:'esm',platform:'node',outfile:join(dir,'tools.mjs'),alias:{'@golem/shared':'../../packages/shared/src/index.ts'}});const T=await import(pathToFileURL(join(dir,'tools.mjs')));const source='a'.repeat(64),id='owner-local:'+source+':585',code=Buffer.from('\uFEFF-- exact owner\r\nreturn "source"\r\n');const sha=b=>createHash('sha256').update(b).digest('hex');const page=b=>({encoding:'base64',data:b.toString('base64'),sha256:sha(b),chunkSha256:sha(b),offset:0,totalBytes:b.length,nextOffset:null,execution:'never'});
const ctx=reply=>({userId:'owner',localOwnerGateway:true,studioConnected:()=>true,env:{},execStudioOp:async op=>({ok:true,data:await reply(op)})});const run=async(c,name,a)=>{const out=await T.runTool(c,name,JSON.stringify(a));return {out,data:JSON.parse(out.resultForLlm)}};
test('assembly exact source is readable inert data and operation source scoped',async()=>{let op;const r=await run(ctx(o=>{op=o;return page(code)}),'query_owner_assembly',{sourceSHA:source,section:'code',codeSHA:sha(code)});assert.equal(r.out.ok,true);assert.equal(op.op,'query_owner_assembly');assert.equal(r.data.text,code.toString());assert.equal(r.data.normalizedNodeMappingProved,false);assert.equal(r.data.sourceExecuted,false);assert.equal(r.out.detail,undefined)});
test('media bytes preserve actual hash and do not claim native loading or pixels',async()=>{let op;const b=Buffer.from('actual media container bytes');const r=await run(ctx(o=>{op=o;return page(b)}),'read_owner_media',{id,property:'TextureContent'});assert.equal(r.out.ok,true);assert.equal(op.op,'query_owner_media');assert.equal(op.id,source+':585');assert.equal(r.data.data,b.toString('base64'));assert.equal(r.data.nativeLoadingVerified,false);assert.equal(r.data.visualInspectionVerified,false);assert.equal(r.out.detail,undefined)});
test('code hash, byte cursor, source execution and corruption are refused',async()=>{for(const patch of [{data:Buffer.from('changed').toString('base64')},{offset:1},{execution:'run'},{sha256:'b'.repeat(64)},{nextOffset:1}]){const r=await run(ctx(()=>({...page(code),...patch})),'query_owner_assembly',{sourceSHA:source,section:'code',codeSHA:sha(code)});assert.equal(r.out.ok,false,JSON.stringify(patch));assert.equal(r.data.text,undefined)}});
test('authentication, binary/normalized selector distinction and page bounds before plugin',async()=>{let n=0;const c=ctx(()=>{n++;return page(code)});for(const a of [{id:'owner-local:'+source+':binary:42',property:'Source'},{id,property:'Texture',limit:3001},{id,property:'Texture',offset:-1}])assert.equal((await run(c,'read_owner_media',a)).out.ok,false);c.userId=undefined;assert.equal((await run(c,'query_owner_assembly',{})).out.ok,false);assert.equal(n,0)});
test('registry SHA cursor, bounded summaries and full context byte paging remain accessible',async()=>{const calls=[];const c=ctx(op=>{calls.push(op);return {sourceSHA:source,rootCandidates:[{id:source+':binary:0'}],recipes:[{mechanic:'shop',scriptIds:['s1','s2'],seedScriptIds:['s1']}],items:[{id:source+':binary:42',sourceCodeSHA:sha(code),dependencies:[{kind:'require'}],functions:['Init'],mechanicEvidence:{shop:['actual evidence']}}],nextAfter:1}});let r=await run(c,'query_owner_assembly',{after:source});assert.equal(calls[0].after,source);assert.equal(r.out.ok,true);r=await run(c,'query_owner_assembly',{sourceSHA:source,mechanic:'shop'});assert.equal(r.data.recipes[0].selectedScriptCount,2);assert.equal(r.data.items[0].dependencyCount,1);assert.equal(r.data.fullContextSection,'record');assert.equal(r.data.items[0].dependencies,undefined);const full=Buffer.from(JSON.stringify({dependencies:[{expression:'require(script.Parent.Exact)',bindingProved:false}]}));r=await run(ctx(()=>page(full)),'query_owner_assembly',{sourceSHA:source,mechanic:'shop',section:'record'});assert.equal(r.out.ok,true);assert.match(r.data.text,/require\(script.Parent.Exact\)/);assert.equal(r.data.sourceExecuted,false)});
test('media inspection rejects containers before any paid/provider call',async()=>{const r=await run(ctx(()=>page(Buffer.from('not PNG; actual mesh container'))),'read_owner_media',{id,property:'TextureContent',inspect:true});assert.equal(r.out.ok,true);assert.equal(r.data.judged,false);assert.equal(r.data.neurons,0);assert.equal(r.data.visualInspectionVerified,false)});
