/**
 * THE LIBRARY HAS TO BE READ BY SOMETHING THE MODEL CAN CALL.
 *
 * `packages/corpus/data/ui-references/` is the only record in this repository of what a shipped
 * Roblox interface is actually shaped like. Commit 7ba141e found that nothing read it — ui-kit.ts
 * mentioned it twice, in comments — and answered that with a test contract over the hand-written
 * kit. That keeps ONE hand-written genre honest. It never reaches the model, so a genre nobody
 * hand-wrote is still invented at generation time.
 *
 * These tests pin the other half: the corpus is bundled, a generator can reach it, and the three
 * ways this could quietly stop working all turn something red.
 *   - the bundle going stale against the source files      -> the --check test
 *   - a lookup answering nothing for an unknown id          -> the miss test
 *   - rules degrading into adjectives a generator can't use -> the applicable-rules test
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';

const HERE = dirname(fileURLToPath(import.meta.url));
const WORKER = join(HERE, '..');
const ROOT = join(WORKER, '..', '..');

const out = join(mkdtempSync(join(tmpdir(), 'apple-uicon-')), 'guide.mjs');
execFileSync(join(WORKER, 'node_modules', '.bin', 'esbuild'),
  [join(WORKER, 'src', 'ui-construction-guide.ts'), '--bundle', '--format=esm', '--target=es2022', '--outfile=' + out],
  { stdio: 'pipe', cwd: WORKER });
const { getUIConstruction, UI_CONSTRUCTION_GENRE_IDS, UI_CONSTRUCTION_SCREEN_IDS } = await import(out);

test('the bundle is not stale against the reference files it is built from', () => {
  // A bundle regenerated by hand and never re-committed is a corpus that silently stops matching
  // the library it claims to carry.
  execFileSync('node', [join(ROOT, 'scripts', 'build-ui-construction.mjs'), '--check'], { stdio: 'pipe' });
});

test('the corpus actually reached the bundle', () => {
  const total = UI_CONSTRUCTION_GENRE_IDS.length + UI_CONSTRUCTION_SCREEN_IDS.length;
  assert.ok(total > 0, 'nothing was bundled — the guide would answer "not covered" to everything');
  assert.ok(UI_CONSTRUCTION_GENRE_IDS.includes('simulator'),
    `simulator is the one complete genre and must be present; got ${UI_CONSTRUCTION_GENRE_IDS.join(', ')}`);
});

test('a known id returns construction a generator can apply, with its provenance', () => {
  const a = getUIConstruction({ id: 'simulator' });
  assert.equal(a.found, true);
  assert.equal(a.id, 'simulator');
  assert.ok(a.guide.includes('RULES'), 'the rules are the part a generator applies');
  assert.ok(Array.isArray(a.sources) && a.sources.length > 0, 'provenance travels so a claim stays checkable');
  // The construction, not the palette: the README records that the palette was already right and
  // the design still looked wrong. A guide that only carried colour would be the same near-miss.
  assert.match(a.guide, /stroke|radius|overhang|grid|bevel/i);
});

test('an unknown id SAYS it is unknown, and lists what does exist', () => {
  const a = getUIConstruction({ id: 'battle-royale-sushi-tycoon' });
  assert.equal(a.found, false);
  assert.match(a.notCovered, /battle-royale-sushi-tycoon/);
  // The sentence has to tell the model the look is its own judgement. A silent empty answer is the
  // failure the genre guide already records: "what a model does with no signal is proceed as
  // though it knew."
  assert.match(a.notCovered, /your own judgement|own judgement/i);
  assert.ok(a.available.genres.length + a.available.screens.length > 0);
});

test('a bare screen name resolves to its screen entry when one exists', () => {
  // Only assert the resolution rule if a screen-* entry has actually been harvested; otherwise this
  // would pin behaviour on an empty corpus and pass for the wrong reason.
  if (!UI_CONSTRUCTION_SCREEN_IDS.length) return;
  const bare = UI_CONSTRUCTION_SCREEN_IDS[0].replace(/^screen-/, '');
  const a = getUIConstruction({ id: bare });
  assert.equal(a.found, true, `"${bare}" should resolve to "screen-${bare}"`);
  assert.equal(a.kind, 'screen');
});

test('the answer is budgeted, so one lookup cannot crowd out the step that uses it', () => {
  const a = getUIConstruction({ id: 'simulator', maxChars: 700 });
  assert.ok(a.guide.length <= 700, `guide was ${a.guide.length} chars against a 700 budget`);
});

test('no image, asset or third-party source rides along in the bundle', () => {
  const raw = readFileSync(join(ROOT, 'packages/corpus/data/ui-construction.json'), 'utf8');
  assert.ok(!/data:image\//.test(raw), 'an embedded image would be a reproduction of somebody else\'s work');
  assert.ok(!/\bgame\.Workspace\b|\bInstance\.new\(/.test(raw), 'Luau source does not belong in a corpus of observations');
});
