/**
 * THE LIBRARY HAS TO BE READ BY SOMETHING THE MODEL CAN CALL.
 *
 * `packages/corpus/data/ui-references/` is the only record in this repository of what a shipped
 * Roblox interface is actually shaped like. Commit 7ba141e found that nothing read it — ui-kit.ts
 * mentioned it twice, in comments — and answered that with a test contract over the hand-written
 * kit. That keeps ONE hand-written genre honest. It never reaches the model, so a genre nobody
 * hand-wrote is still invented at generation time.
 *
 * These tests pin the other half: the corpus is bundled, a generator can reach it, and the three
 * ways this could quietly stop working all turn something red.
 *   - the bundle going stale against the source files      -> the --check test
 *   - a lookup answering nothing for an unknown id          -> the miss test
 *   - rules degrading into adjectives a generator can't use -> the applicable-rules test
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';

const HERE = dirname(fileURLToPath(import.meta.url));
const WORKER = join(HERE, '..');
const ROOT = join(WORKER, '..', '..');

const out = join(mkdtempSync(join(tmpdir(), 'apple-uicon-')), 'guide.mjs');
execFileSync(join(WORKER, 'node_modules', '.bin', 'esbuild'),
  [join(WORKER, 'src', 'ui-construction-guide.ts'), '--bundle', '--format=esm', '--target=es2022', '--outfile=' + out],
  { stdio: 'pipe', cwd: WORKER });
const { getUIConstruction, UI_CONSTRUCTION_GENRE_IDS, UI_CONSTRUCTION_SCREEN_IDS } = await import(out);

test('the bundle is not stale against the reference files it is built from', () => {
  // A bundle regenerated by hand and never re-committed is a corpus that silently stops matching
  // the library it claims to carry.
  execFileSync('node', [join(ROOT, 'scripts', 'build-ui-construction.mjs'), '--check'], { stdio: 'pipe' });
});

test('the corpus actually reached the bundle', () => {
  const total = UI_CONSTRUCTION_GENRE_IDS.length + UI_CONSTRUCTION_SCREEN_IDS.length;
  assert.ok(total > 0, 'nothing was bundled — the guide would answer "not covered" to everything');
  assert.ok(UI_CONSTRUCTION_GENRE_IDS.includes('simulator'),
    `simulator is the one complete genre and must be present; got ${UI_CONSTRUCTION_GENRE_IDS.join(', ')}`);
});

test('a known id returns construction a generator can apply, with its provenance', () => {
  const a = getUIConstruction({ id: 'simulator' });
  assert.equal(a.found, true);
  assert.equal(a.id, 'simulator');
  assert.ok(a.guide.includes('RULES'), 'the rules are the part a generator applies');
  assert.ok(Array.isArray(a.sources) && a.sources.length > 0, 'provenance travels so a claim stays checkable');
  // The construction, not the palette: the README records that the palette was already right and
  // the design still looked wrong. A guide that only carried colour would be the same near-miss.
  assert.match(a.guide, /stroke|radius|overhang|grid|bevel/i);
});

test('an unknown id SAYS it is unknown, and lists what does exist', () => {
  const a = getUIConstruction({ id: 'battle-royale-sushi-tycoon' });
  assert.equal(a.found, false);
  assert.match(a.notCovered, /battle-royale-sushi-tycoon/);
  // The sentence has to tell the model the look is its own judgement. A silent empty answer is the
  // failure the genre guide already records: "what a model does with no signal is proceed as
  // though it knew."
  assert.match(a.notCovered, /your own judgement|own judgement/i);
  assert.ok(a.available.genres.length + a.available.screens.length > 0);
});

test('a bare screen name resolves to its screen entry when one exists', () => {
  // Only assert the resolution rule if a screen-* entry has actually been harvested; otherwise this
  // would pin behaviour on an empty corpus and pass for the wrong reason.
  if (!UI_CONSTRUCTION_SCREEN_IDS.length) return;
  const bare = UI_CONSTRUCTION_SCREEN_IDS[0].replace(/^screen-/, '');
  const a = getUIConstruction({ id: bare });
  assert.equal(a.found, true, `"${bare}" should resolve to "screen-${bare}"`);
  assert.equal(a.kind, 'screen');
});

test('the answer is budgeted, so one lookup cannot crowd out the step that uses it', () => {
  const a = getUIConstruction({ id: 'simulator', maxChars: 700 });
  assert.ok(a.guide.length <= 700, `guide was ${a.guide.length} chars against a 700 budget`);
});

test('no image, asset or third-party source rides along in the bundle', () => {
  const raw = readFileSync(join(ROOT, 'packages/corpus/data/ui-construction.json'), 'utf8');
  assert.ok(!/data:image\//.test(raw), 'an embedded image would be a reproduction of somebody else\'s work');
  assert.ok(!/\bgame\.Workspace\b|\bInstance\.new\(/.test(raw), 'Luau source does not belong in a corpus of observations');
});

// ---------------------------------------------------------------------------
// THE DOOR AND THE KEY TAPED TO IT.
//
// Everything above this line passed on 2026-09-20 while four of the thirteen advertised genres were
// unreachable by their own names. The suite only ever asked for `simulator`, which is one of the
// nine ids with no underscore in it, so it had no way to see the defect. These are the cases that
// would have.
// ---------------------------------------------------------------------------

test('EVERY advertised id resolves to itself — the tool description is not a list of dead keys', () => {
  // tools.ts builds this tool's description by interpolating UI_CONSTRUCTION_GENRE_IDS verbatim, and
  // get_genre_kit constrains the same vocabulary with a JSON-schema enum, so the model is TOLD to
  // say "tower_defense" and could not spell it any other way. Before the fix, `tower_defense`,
  // `fps_arena`, `anime_battle` and `pet_simulator` each answered "Nobody has inspected shipped
  // Roblox UI for it" when asked by the exact string the tool advertises.
  const advertised = [...UI_CONSTRUCTION_GENRE_IDS, ...UI_CONSTRUCTION_SCREEN_IDS];
  const dead = advertised.filter((id) => {
    const a = getUIConstruction({ id });
    return !(a.found === true && a.id === id);
  });
  assert.deepEqual(dead, [], `advertised ids that do not find their own row: ${dead.join(', ')}`);
});

test('underscore, hyphen and space are the same character on both sides', () => {
  const underscored = UI_CONSTRUCTION_GENRE_IDS.filter((g) => g.includes('_'));
  if (!underscored.length) return; // nothing to prove if the corpus stops using underscores
  for (const id of underscored) {
    for (const spelling of [id, id.replace(/_/g, '-'), id.replace(/_/g, ' '), id.toUpperCase()]) {
      const a = getUIConstruction({ id: spelling });
      assert.equal(a.found, true, `"${spelling}" should reach ${id}`);
      assert.equal(a.id, id);
    }
  }
});

test('a meaningless fragment gets a MISS, not a confident sourced answer for something else', () => {
  // The old fallback was `rows.find(r => r.genre.includes(want))` — unranked, first row in readdir
  // order. Measured: "sim" returned pet_simulator rather than simulator, "er" returned
  // tower_defense, "a" returned anime_battle, "in" returned racing. Each answered found:true with
  // real sources attached, which is this module's contract broken in the direction that does more
  // damage: the model cannot tell a confident wrong answer from a right one.
  for (const junk of ['a', 'er', 'or', 'in', 'ing', 'sim']) {
    const a = getUIConstruction({ id: junk });
    assert.equal(a.found, false, `"${junk}" returned ${a.id} as a confident hit`);
  }
});

test('a fragment that IS a whole word of an id reaches it, and says how it got there', () => {
  if (!UI_CONSTRUCTION_GENRE_IDS.includes('tower_defense')) return;
  const a = getUIConstruction({ id: 'tower' });
  assert.equal(a.found, true);
  assert.equal(a.id, 'tower_defense');
  assert.equal(a.resolvedFrom, 'token', 'a non-verbatim hit must say it was non-verbatim');
  // …while a verbatim hit says nothing, because there is nothing to disclose.
  assert.equal(getUIConstruction({ id: 'tower_defense' }).resolvedFrom, undefined);
});

test('the British spelling finds the American row', () => {
  if (!UI_CONSTRUCTION_GENRE_IDS.includes('tower_defense')) return;
  const a = getUIConstruction({ id: 'tower_defence' });
  assert.equal(a.found, true, 'tower_defence must reach tower_defense');
  assert.equal(a.id, 'tower_defense');
});

test('resolution is deterministic, not a function of directory listing order', () => {
  const once = getUIConstruction({ id: 'shop' });
  const twice = getUIConstruction({ id: 'shop' });
  assert.equal(once.id, twice.id);
  // "simulator" must reach the genre named simulator, never pet_simulator, which is what the
  // unranked fallback did for the prefix "sim".
  if (UI_CONSTRUCTION_GENRE_IDS.includes('simulator')) {
    assert.equal(getUIConstruction({ id: 'simulator' }).id, 'simulator');
  }
});
