/**
 * AN INDEX BUILT BY LOOKING AT THE TEST MEASURES COPYING.
 *
 * packages/training/data/need-index.json is the whole of one retrieval approach: for each of the 80
 * verified modules it records the words a customer would use, and apps/worker/src/need-index-search.ts
 * ranks against them. The approach is then scored on 80 hand-written customer-phrased queries in
 * customer-queries.mjs.
 *
 * Those two files must never have met. If a benchmark query — or a distinctive span of one, or even
 * one benchmark-only word demonstrated in the instructions — reached the generator, the reported
 * top-1 would describe an index that had seen its own exam. It would be far too high, and it would
 * collapse the first time a real customer typed something nobody had written down. That is this
 * repository's standing failure shape wearing new clothes: a number about the measurement apparatus
 * rather than about the product.
 *
 * So blindness is not a claim in a comment. It is these assertions, and they run in `pnpm test`.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CUSTOMER_QUERIES } from './customer-queries.mjs';
import { vocabularyOf, tokenise, GENERATOR_STOP, promptFor } from './build-need-index.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const GENERATOR = join(HERE, 'build-need-index.mjs');
const INDEX = join(HERE, '..', 'data', 'need-index.json');

const source = readFileSync(GENERATOR, 'utf8');
const bundle = existsSync(INDEX) ? JSON.parse(readFileSync(INDEX, 'utf8')) : null;
const MODULES = JSON.parse(readFileSync(join(HERE, '..', '..', 'corpus', 'data', 'verified-modules.json'), 'utf8')).modules;
const notGenerated = bundle ? false : 'packages/training/data/need-index.json has not been generated';

/** The instruction text only — not the module fields interpolated into it. */
const promptTemplate = () => {
  const t = source.slice(source.indexOf('export const promptFor'));
  return t.slice(0, t.indexOf('export const GENERATOR_STOP'));
};

test('the generator cannot reach the benchmark queries', () => {
  // An import, a dynamic import, a require, a readFileSync of that path — any is a channel. Checked
  // as patterns rather than as a substring, because the generator's own prose NAMES the file it must
  // not read, and a substring test would flag the sentence that documents the rule.
  const channels = [
    /from\s+['"][^'"]*customer-queries/,
    /import\s*\(\s*['"][^'"]*customer-queries/,
    /require\s*\(\s*['"][^'"]*customer-queries/,
    /readFileSync\s*\([^)]*customer-queries/,
    /\bCUSTOMER_QUERIES\b/,
  ];
  for (const re of channels) {
    assert.equal(re.test(source), false, `build-need-index.mjs matches ${re} — the index could have seen its own exam`);
  }
});

test('the generator prompt demonstrates no benchmark vocabulary that could reach the index', () => {
  // The subtler leak is not an import but an instruction: "if one line says range, say slot" hands
  // the generator a benchmark token and then scores it for returning that token.
  //
  // The words that could do damage are exactly the ones a benchmark query uses and NO module
  // contract does — the vocabulary the index has no other honest way to learn. A word the
  // generator's own STOP list discards reaches the index with frequency zero and cannot move a
  // ranking, so it is allowed; anything else is not. The first draft failed this on "different",
  // which had entered seven modules' vocabulary, and the index was regenerated rather than excused.
  const corpus = new Set();
  for (const m of MODULES) for (const w of tokenise(`${m.id} ${m.family} ${m.contract}`)) corpus.add(w);
  const benchmarkOnly = new Set();
  for (const q of Object.values(CUSTOMER_QUERIES)) {
    for (const w of tokenise(q)) if (w.length > 3 && !corpus.has(w)) benchmarkOnly.add(w);
  }
  assert.ok(benchmarkOnly.size > 50, 'the benchmark-only vocabulary should be large; this test is vacuous otherwise');

  const leaked = [...new Set(tokenise(promptTemplate()))]
    .filter((w) => benchmarkOnly.has(w) && !GENERATOR_STOP.has(w));
  assert.deepEqual(leaked, [],
    `the generator prompt demonstrates benchmark-only vocabulary that would survive into the index: ${leaked.join(', ')}`);
});

test('the committed index was generated by the prompt this file now holds', { skip: notGenerated }, () => {
  // A prompt edited after the index was built leaves the two disagreeing, and every blindness
  // assertion above would be about a prompt that produced nothing.
  const hash = createHash('sha256').update(promptFor(MODULES[0])).digest('hex').slice(0, 16);
  assert.equal(bundle.settings.promptHash, hash,
    'need-index.json was generated by a different prompt than build-need-index.mjs now contains — regenerate it');
});

/**
 * TWO PLACES WHERE THE BLIND GENERATOR AND THE HAND-WRITTEN BENCHMARK WROTE NEARLY THE SAME SENTENCE.
 *
 * Neither is a leak — no channel exists, and the test above proves there is none — and convergence
 * is the very mechanism this approach bets on: if two describers who have never met reach for the
 * same words, an index built from one of them finds the other. But a long identical span is exactly
 * what copying would also look like, so each one is named here with what it is, rather than the
 * threshold being quietly raised until the suite goes green.
 *
 * measure-need-index.mjs reports the variant with both of these lines deleted; the headline top-1 is
 * unchanged by their removal, which is the part that settles it.
 */
const CONVERGENT = [
  { id: 'stamina-regen', span: 'come back after they stop sprinting for a bit' },
  { id: 'visible-ui-rows', span: 'scrolling list are on screen' },
];

test('no generated line reproduces a benchmark query', { skip: notGenerated }, () => {
  const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  const queries = Object.values(CUSTOMER_QUERIES).map(norm);
  const unexplained = [];
  for (const [id, entry] of Object.entries(bundle.modules)) {
    for (const line of entry.lines) {
      const n = norm(line);
      assert.equal(queries.includes(n), false, `${id}: a generated line IS a benchmark query verbatim`);
      // A long shared span is the same leak with a word changed at each end.
      for (const q of queries) {
        for (let i = 0; i + 40 <= q.length; i += 8) {
          const span = q.slice(i, i + 40);
          if (!n.includes(span)) continue;
          const named = CONVERGENT.some((c) => c.id === id && (span.includes(c.span) || c.span.includes(span.trim())));
          if (!named) unexplained.push({ id, span, line });
        }
      }
    }
  }
  assert.deepEqual(unexplained, [],
    'a generated line shares a long span with a benchmark query and is not one of the two recorded convergences — either the generator gained a channel to the queries, or a third convergence needs naming and measuring');
});

test('the recorded convergences are still there, so the allowance cannot outlive what it excuses', { skip: notGenerated }, () => {
  // An exception list that stops matching anything is an exception list nobody will ever delete.
  const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  for (const { id, span } of CONVERGENT) {
    const lines = (bundle.modules[id]?.lines ?? []).map(norm);
    assert.ok(lines.some((l) => l.includes(span)),
      `${id} no longer contains the span this list excuses — remove the entry`);
  }
});

test('the index records what produced it, so a number can name its settings', { skip: notGenerated }, () => {
  assert.ok(bundle.settings.model, 'no lane recorded');
  //[[ `stone` is a gateway config name, not a product and not a model. The served id is what a
  //   reader can check. ]]
  assert.ok(bundle.settings.servedBy, 'no served model id recorded');
  assert.ok(bundle.settings.maxTokens > 0);
  assert.ok(bundle.generatedAt);
  assert.ok(bundle.cost.calls > 0);
  assert.ok(Array.isArray(bundle.failures));
});

test('every module has need text, and a gateway failure is named rather than silently dropped', { skip: notGenerated }, () => {
  // Ten of eighty were lost to transient HTTP 500s on the first run and the file was written anyway.
  // Ten modules with no need entry are ten modules the door still cannot find, and the retrieval
  // number would have described a 70-module index while being reported as an 80-module one.
  const missing = MODULES.map((m) => m.id).filter((id) => !bundle.modules[id]);
  assert.deepEqual(missing, [], `modules with no customer vocabulary: ${missing.join(', ')}`);
  assert.equal(bundle.failures.length, 0, `unrepaired generation failures: ${JSON.stringify(bundle.failures)}`);
});

test('vocabularyOf counts the LINES a word appeared in, not its occurrences', () => {
  const v = vocabularyOf(['coins coins coins spent', 'coins off the balance', 'nothing relevant']);
  const coins = v.find(([w]) => w === 'coins');
  assert.equal(coins[1], 2, 'a word repeated inside one line must not outrank a word two lines used');
});

test('the tokeniser keeps the numerals the shipped one destroys', () => {
  // The shipped tokeniser is split(/[^a-z0-9]+/) with length > 2, which turns "1.5K" into ['1','5k']
  // and drops both. Four of the eighty modules are identified by exactly such a token.
  assert.deepEqual(tokenise('show 1500 coins as 1.5K'), ['show', '1500', 'coins', 'as', '1.5k']);
  assert.deepEqual(tokenise('timer like 1:05'), ['timer', 'like', '1:05']);
  assert.deepEqual(tokenise('item number 14 in a grid'), ['item', 'number', '14', 'in', 'a', 'grid']);
});
