// WHAT A CUSTOMER SAYS, NOT WHAT THE CONTRACT SAYS.
//
// `askVerifiedModule({ need })` is the only door between eighty executed Luau modules and a
// customer's build. The model writes `need` in the customer's words, and the library is indexed on
// contract words. verified-modules.ts already records one measured collision of exactly that kind:
// "stop the player using an ability too often" ranked `cooldown-clock` nowhere, because its
// contract says "allow use exactly when elapsed time is at least delay" and never says "cooldown",
// "often" or "spam".
//
// That was one query. This is eighty, so the gap can be a number instead of an anecdote.
//
// HOW THESE WERE WRITTEN, stated so the measurement can be disputed rather than trusted. Each line
// was authored by hand for this measurement, in the voice of a Roblox creator describing a need,
// and deliberately AVOIDS the module's function name and the distinctive vocabulary of its
// contract. They are one session's judgement of how a person asks, not a sample of real traffic —
// which is the honest limitation of this whole file, and the reason the note at the bottom of the
// report says to replace them with logged prompts as soon as any exist.
export const CUSTOMER_QUERIES = {
  'purchase-transaction': 'when a player buys something take the coins off them but only if they can afford it and do not already own it',
  'bounded-reward': 'give coins for a win but never go over the maximum they can hold',
  'cooldown-clock': 'stop the player using an ability too often',
  'ordered-checkpoints': 'obby checkpoints have to be touched in order, do not let them skip ahead',
  'inventory-capacity': 'how many more items can fit in the backpack before it is full',
  'round-transitions': 'manage the game states, waiting then countdown then playing then results',
  'level-from-xp': 'work out what level someone is from their experience points',
  'unlock-prerequisites': 'only let them open this one if they finished the earlier ones',
  'finite-normalization': 'turn a health value into a 0 to 1 number for the bar',
  'stable-leaderboard': 'sort players by score for the leaderboard, ties should stay in the same order',
  'weighted-selection': 'pick a random prize where the rare ones come up less',
  'interval-overlap': 'check if two time slots clash',
  'merge-ranges': 'combine overlapping number ranges into one tidy list',
  'dependency-order': 'figure out what order to build things in when some need others first',
  'crafting-batches': 'how many of this recipe can they craft with what is in their bag',
  'seeded-shuffle': 'shuffle a list the same way every time from a seed',
  'turn-rotation': 'whose turn is next, skipping anyone who left',
  'damage-mitigation': 'reduce incoming damage by armour but always do at least a little',
  'route-cost': 'add up the cost of walking a path over different ground types',
  'team-balance': 'put a joining player on the team that has fewer people',
  'fit-ui-aspect': 'scale an image to fit inside a box without stretching it',
  'visible-ui-rows': 'which rows of a scrolling list are on screen right now',
  'ui-grid-columns': 'how many columns fit across depending on the width',
  'escape-ui-richtext': 'stop player typed text breaking my rich text label',
  'session-window': 'is the event running right now, it starts at a time and lasts a while',
  'dense-sample-mean': 'average a list of numbers safely',
  'meter-band': 'colour the meter green yellow or red depending on the value',
  'compact-under-ceiling': 'drop anything above a limit out of a list and keep the rest in order',
  'radial-damage-falloff': 'explosion does less damage the further away you are',
  'due-respawns': 'which dead enemies are ready to come back now',
  'rating-bracket': 'put a player into a skill bracket from their rating',
  'loot-budget': 'share out a loot budget between the drops',
  'stamina-regen': 'stamina should come back after they stop sprinting for a bit',
  'hunger-drain': 'hunger goes down over time',
  'prestige-conversion': 'reset them to level 1 and give a prestige star when they max out',
  'quest-step': 'which step of the quest are they on based on what they have done',
  'ability-charges': 'the ability has 3 charges that refill one at a time',
  'projectile-lead': 'aim ahead of a moving target so the shot actually hits',
  'grid-snap': 'snap a placed block to the build grid',
  'grid-route-cost': 'cheapest way across a grid of tiles from one tile to another',
  'stack-into-slots': 'put picked up items into stacks in the inventory slots',
  'trade-offer-check': 'check a trade is legit before it goes through',
  'auction-bid': 'handle bidding on an auction including last second bids',
  'token-bucket-spend': 'rate limit how often a player can fire a remote',
  'speed-audit': 'detect someone moving faster than they should be',
  'seat-assignment': 'sit a player in a free seat in the car',
  'elevator-next-floor': 'which floor should the lift go to next',
  'day-night-phase': 'is it day or night and how far through',
  'wave-difficulty': 'each wave gets harder and every fifth one has a boss',
  'combo-multiplier': 'combo multiplier that goes up on hits and drops if you stop',
  'leaderboard-insert': 'keep a top ten list of high scores',
  'spawn-clearance': 'pick a spawn point that is not too close to another player',
  'chest-respawn': 'chest refills a while after it is looted',
  'tool-durability': 'pickaxe wears out after so many swings',
  'buff-stacks': 'buffs that expire and only stack so many times',
  'abbreviate-counter': 'show 1500 coins as 1.5K',
  'format-duration': 'show the seconds left as a timer like 1:05',
  'ordinal-suffix': 'show 1st 2nd 3rd next to the place number',
  'truncate-display-name': 'cut a long username with dots so it fits',
  'wrap-label-text': 'wrap text onto lines of a set width',
  'paginate-list': 'split a list into pages with next and back',
  'grid-cell-position': 'work out the row and column for item number 14 in a grid',
  'scrollbar-thumb': 'size and position of the scrollbar handle',
  'anchor-inside-bounds': 'keep a popup fully on screen',
  'progress-segments': 'a progress bar made of ten chunks, how many are lit',
  'honest-percent': 'show a percentage for the bar',
  'remap-range': 'convert a number from one range to another',
  'smoothstep-between': 'ease a value between two numbers smoothly',
  'parse-hex-colour': 'turn a hex colour string into a Color3',
  'deep-table-equality': 'compare two tables to see if they are the same',
  'merge-settings': 'apply the player saved settings on top of the defaults',
  'validate-action-payload': 'check what the client sent me has the right shape',
  'filter-by-search': 'filter a list as they type in a search box',
  'sort-inventory-rows': 'sort the inventory by rarity then name',
  'tooltip-placement': 'put a tooltip next to the cursor but flip it near the edge',
  'zoom-notches': 'zoom in and out by steps with the scroll wheel',
  'snap-slider-value': 'make a slider snap to steps',
  'notification-queue': 'show notifications one after another and only keep the last few',
  'project-client-fields': 'only send the fields the client is allowed to see',
  'distribute-column-widths': 'split a row width between columns by weight',
};
