// A single row count describes something four times larger than this corpus holds.
//
// WHY THIS EXISTS. `tijnepema/lucide-roblox` contributes 8,187 rows and **18 distinct shapes**.
// Eight thousand one hundred and eighty-seven files; eighteen programs. The other 8,169 differ only
// in the numbers inside a `Vector2.new(...)` and the icon name in a string. Every one is MIT, every
// one is a real file, and a card that reported 8,187 as a contribution to a training corpus would
// be overstating that repository by a factor of 455.
//
// This is the failure mode the whole dataset track keeps hitting from a different angle each time:
// the largest number available, quoted as though it answered the question being asked. 4,851 leads
// of which 4,269 had never been opened. 5.45 GB that was 248 MiB of Luau. 845,351 rows behind an
// `odc-by` tag that were 95.6% unlicensed. Every one of them was a real measurement of the wrong
// thing.
//
// WHAT THIS PROVES, STATED NARROWLY: that the generated/hand-written split partitions the rows with
// nothing lost or double-counted; that the hand-written shape count is computed from hand-written
// rows alone; that a tally of nothing is nothing rather than a plausible-looking default; and that
// the card keeps carrying the paragraph saying what it does not establish, including that nothing
// here approves anything for training.
//
// It proves nothing about whether the shapes that survive are good code.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { tally, splitRows } from './summarise-github-corpus.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CARD = join(ROOT, 'data/roblox-github-v1/dataset-card.json');

const row = (over = {}) => ({ generated: false, shape_sha256: 'a'.repeat(64), bytes: 10, ...over });

test('the generated split partitions the rows, losing and duplicating nothing', () => {
  const rows = [
    row({ generated: true, shape_sha256: 'g1', bytes: 5 }),
    row({ generated: true, shape_sha256: 'g1', bytes: 5 }),
    row({ generated: true, shape_sha256: 'g2', bytes: 5 }),
    row({ generated: false, shape_sha256: 'h1', bytes: 100 }),
    row({ generated: false, shape_sha256: 'h2', bytes: 200 }),
  ];
  const s = splitRows(rows);
  assert.equal(s.rows_total, 5);
  assert.equal(s.rows_machine_generated, 3);
  assert.equal(s.rows_hand_written, 2);
  assert.equal(s.rows_machine_generated + s.rows_hand_written, s.rows_total,
    'the split lost or double-counted rows');
  assert.equal(s.bytes_total, 315);
  assert.equal(s.bytes_hand_written, 300, 'generated bytes leaked into the hand-written byte total');
});

test('the hand-written shape count is computed from hand-written rows alone', () => {
  // The case that matters: a generated shape that ALSO appears hand-written must not inflate the
  // hand-written figure, and generated shapes must not be counted into it at all.
  const rows = [
    row({ generated: true, shape_sha256: 'g' }),
    row({ generated: true, shape_sha256: 'g' }),
    row({ generated: true, shape_sha256: 'g' }),
    row({ generated: false, shape_sha256: 'h' }),
  ];
  const s = splitRows(rows);
  assert.equal(s.distinct_shapes_total, 2);
  assert.equal(s.distinct_shapes_hand_written, 1,
    'generated shapes were counted into the hand-written shape total');

  // The lucide-roblox proportion, in miniature: many rows, one shape.
  const stubs = Array.from({ length: 500 }, () => row({ generated: true, shape_sha256: 'one' }));
  const one = splitRows(stubs);
  assert.equal(one.rows_total, 500);
  assert.equal(one.distinct_shapes_total, 1,
    'five hundred instances of one template were reported as more than one program');
});

test('a tally of nothing is nothing, and a tally is ordered by size', () => {
  assert.deepEqual(tally([], (r) => r.k), {}, 'an empty input produced a non-empty tally');
  const t = tally([{ k: 'MIT' }, { k: 'Apache-2.0' }, { k: 'MIT' }, { k: 'MIT' }, { k: null }, { k: undefined }], (r) => r.k);
  assert.deepEqual(Object.keys(t), ['MIT', 'Apache-2.0'], 'the tally is not biggest-first, or swallowed a null as a key');
  assert.deepEqual(t, { MIT: 3, 'Apache-2.0': 1 });
});

test('the card keeps saying what it does not establish',
  { skip: !existsSync(CARD) && 'the card has not been generated' }, () => {
    const card = JSON.parse(readFileSync(CARD, 'utf8'));

    assert.ok(Array.isArray(card.what_this_does_not_establish) && card.what_this_does_not_establish.length >= 3,
      'the limits paragraph was emptied out');
    const limits = card.what_this_does_not_establish.join(' ');
    assert.match(limits, /training_approved is false/,
      'the card stopped saying that nothing here approves anything for training');
    assert.match(limits, /held the rights they granted/,
      'the card stopped saying a retrieved LICENSE is the publisher speaking, not a chain of title');

    // The split must be present and must reconcile. A card carrying one total is the defect.
    const v = card.volume;
    assert.equal(v.rows_machine_generated + v.rows_hand_written, v.rows_total, 'the card’s split does not reconcile');
    assert.ok(v.distinct_shapes_total <= v.rows_total, 'more distinct shapes than rows');
    assert.ok(v.distinct_shapes_hand_written <= v.distinct_shapes_total);
    assert.match(String(card.volume_note), /distinct programs/,
      'the note that a row count is not a program count was removed');

    // Validation must stay honest: nothing was run.
    assert.equal(card.validation.engine_execution, 'not_run');
    assert.equal(card.validation.human_review, 'not_performed');
    assert.equal(card.validation.semantic_quality, 'not_measured');

    // And the card must be traceable to the ledger it was derived from.
    assert.match(card.derived_from['repos.jsonl'].sha256, /^[0-9a-f]{64}$/,
      'the card does not record the sha256 of the ledger it was derived from');
    assert.equal(card.rights.evidence_tier, 'licence_text');
  });
