// GENERATED by apps/studio/scripts/gen-tools.mjs from apps/worker/src/tools.ts. Do not edit by hand.
import * as v from 'valibot';

export interface StudioToolSpec {
  name: string;
  /** Changes the place: the gate takes a checkpoint first, so the change can be undone. */
  writes: boolean;
  description: string;
  input?: v.ObjectSchema<v.ObjectEntries, undefined>;
}

export const STUDIO_TOOL_SPECS: readonly StudioToolSpec[] = [
  {
    name: "get_project_tree",
    writes: false,
    description: "Snapshot of the game instance tree with names, classes, measured part positions/sizes/anchoring when available, and duplicate-name warnings. Start here to understand a project. Siblings that share a name are marked: a plain path cannot select one of them, so never guess which is meant. Where the outline shows a readRef for one, that readRef is its address.",
    input: v.object({ "root": v.optional(v.pipe(v.string(), v.description("Path to start from, e.g. \"game.Workspace\". Default: whole game (key services)."))), "maxDepth": v.optional(v.pipe(v.number(), v.description("Depth limit, default 4"))) }),
  },
  {
    name: "list_scripts",
    writes: false,
    description: "List all scripts in the project with paths, class and line counts.",
    input: v.object({ "root": v.optional(v.string()) }),
  },
  {
    name: "read_script",
    writes: false,
    description: "Read script source by path. Normal scripts are returned completely; large scripts return an explicit line page with nextStartLine. Follow it with start_line until null before replacing the whole script. complete means this response contains the entire script. Every page carries the whole-file baseHash: pass it as base_hash on edit_script to reject concurrent edits.",
    input: v.object({ "path": v.string(), "start_line": v.optional(v.pipe(v.number(), v.minValue(1), v.integer(), v.description("First line, one-based; follow nextStartLine when the source is paged."))), "max_lines": v.optional(v.pipe(v.number(), v.maxValue(1000), v.minValue(1), v.integer())) }),
  },
  {
    name: "search_scripts",
    writes: false,
    description: "Search all script sources for a string. Returns matches with paths and line numbers. For a NAME rather than a substring, find_symbol resolves scope and search_scripts does not.",
    input: v.object({ "query": v.string() }),
  },
  {
    name: "get_instance",
    writes: false,
    description: "Read one instance back: its class, child count, common properties and attributes. Use it to VERIFY a change you just made, and quote what you actually saw rather than what you intended. Cheaper and more reliable than a run_luau that returns the same value. When a tree provides readRef for a duplicate-named instance, pass that exact readRef as path to read it; references expire and cannot authorize writes.",
    input: v.object({ "path": v.pipe(v.string(), v.description("Full path, e.g. game.Workspace.Lobby.Floor")) }),
  },
  {
    name: "get_output_logs",
    writes: false,
    description: "Read recent Studio output/console logs (errors, warnings, prints).",
  },
  {
    name: "edit_script",
    writes: true,
    description: "Create or edit a script. Provide exactly one of `source` (full new content), `edits` (find/replace list, exact match), or `source_file` (an exact saved .lua/.luau workspace version). One exact edit: edits:[{find:\"exact old text\",replace:\"new text\"}]; top-level find + replace is the same shorthand, never combined with another input. A new script: set `create_class` + `create_parent`. The result is parsed BEFORE it is written: a body that does not compile is refused, nothing changed. A script that newly assembles a Model from Parts waits until the library was tried (find_library_model). `base_hash` from read_script also refuses a write over a concurrent Studio edit.",
    input: v.object({ "path": v.pipe(v.string(), v.description("Full path, e.g. game.ServerScriptService.RoundManager")), "source": v.optional(v.string()), "find": v.optional(v.pipe(v.string(), v.description("Single-edit shorthand: non-empty exact old text. Requires replace; omit source, edits and source_file."))), "replace": v.optional(v.pipe(v.string(), v.description("Single-edit shorthand: replacement text, including an empty string for deletion. Requires find."))), "all": v.optional(v.pipe(v.boolean(), v.description("For the single-edit shorthand only: replace all exact occurrences."))), "baseHash": v.optional(v.pipe(v.string(), v.description("Alias for base_hash; both must match."))), "edits": v.optional(v.array(v.object({ "find": v.string(), "replace": v.string(), "all": v.optional(v.boolean()) }))), "source_file": v.optional(v.object({ "path": v.pipe(v.string(), v.description("Project workspace path ending in .lua or .luau.")), "version": v.pipe(v.number(), v.description("Exact saved workspace version to use. No latest-version fallback.")) })), "create_class": v.optional(v.picklist(["Script","LocalScript","ModuleScript"])), "create_parent": v.optional(v.pipe(v.string(), v.description("Parent path when creating"))), "base_hash": v.optional(v.pipe(v.string(), v.description("The `baseHash` read_script returned for this path. The edit is refused if the file has changed since."))) }),
  },
  {
    name: "create_instances",
    writes: true,
    description: "Create instances (parts, models, lights...). Props are typed: {\"Position\":{\"t\":\"Vector3\",\"v\":[0,5,0]}, \"Material\":{\"t\":\"EnumItem\",\"v\":\"Enum.Material.Neon\"}, \"Color\":{\"t\":\"Color3\",\"v\":[1,0.5,0]}}. Types: string,number,bool,Vector3,Vector2,CFrame,Color3,UDim2,UDim,EnumItem,BrickColor,Content,NumberRange,NumberSequence,ColorSequence,Rect,Instance,nil. A propIssues result means the instances WERE created: fix them with set_properties. Per call: 120 items, 400 instances, 40 children each, 12 levels, 48 props each (longer lists are split for you). origin {at:[x,y,z], yaw?} builds in local space around (0,0,0) and places the batch; group {className:\"Model\"|\"Folder\", name, primaryPart?} wraps it (up to 120 items); build once, repeat with clone_instances. Plain parts (Part, WedgePart, CornerWedgePart, TrussPart) are Anchored unless Anchored is false; bare Size/Position/Orientation/Color arrays and Material/Shape names on parts are typed for you. Also creates AudioPlayer (Asset: a library sound id), AudioEmitter, Wire (SourceInstance/TargetInstance: paths of existing instances), the Audio effects, Animator, Animation, IKControl and Explosion (BlastPressure and DestroyJointRadiusPercent default to 0).",
    input: v.object({ "items": v.pipe(v.array(v.object({ "className": v.pipe(v.string(), v.description("Roblox class, e.g. \"Part\"")), "name": v.string(), "parent": v.optional(v.pipe(v.string(), v.description("Path of an existing instance, e.g. \"Workspace.StreetLamp\". Default \"Workspace\"."))), "props": v.optional(v.pipe(v.record(v.string(), v.unknown()), v.description("Typed properties"))), "attributes": v.optional(v.record(v.string(), v.unknown())), "children": v.optional(v.pipe(v.array(v.record(v.string(), v.unknown())), v.description("Nested items with the same fields (no parent)"))) })), v.minLength(1)), "origin": v.optional(v.record(v.string(), v.unknown())), "group": v.optional(v.record(v.string(), v.unknown())) }),
  },
  {
    name: "set_properties",
    writes: true,
    description: "Set properties/attributes on an existing instance. Same typed prop format as create_instances. Reports what each value WAS, so you can quote the change rather than the intention. path may be a readRef from get_project_tree to change one of several same-named siblings.",
    input: v.object({ "path": v.string(), "props": v.optional(v.record(v.string(), v.unknown())), "attributes": v.optional(v.record(v.string(), v.unknown())) }),
  },
  {
    name: "delete_instances",
    writes: true,
    description: "Delete instances by path only when the user asked for removal or after a replacement is already verified in Studio. A duplicate-name create error means the existing object should be inspected and edited or renamed; never delete working paths or props to make that name available. To remove one of several same-named copies, pass its readRef from get_project_tree in place of the path.",
    input: v.object({ "paths": v.array(v.string()) }),
  },
  {
    name: "move_instances",
    writes: true,
    description: "Reparent existing instances without recreating them. Each move is { path, newParent }; either may be a readRef from get_project_tree when siblings share a name. Paths stay inside StudPilot's writable place scope and Studio refuses cycles, duplicate targets and sibling-name collisions.",
    input: v.object({ "moves": v.pipe(v.array(v.object({ "path": v.pipe(v.string(), v.maxLength(320)), "newParent": v.pipe(v.string(), v.maxLength(320)) })), v.maxLength(120), v.minLength(1)) }),
  },
  {
    name: "clone_instances",
    writes: true,
    description: "Clone instances (collision-free names; optional parent). MANY COPIES IN ONE CALL: `paths` (a template, up to 8 cycled) plus exactly one of `at` [[x,y,z],...], `along` {points, spacing|count} or `within` {rect:{min:[x,z],max:[x,z]}|polygon, count, minSpacing?, y?}; optional yaw (number or [min,max]), scale, jitter, seed, name, parent. Up to 1000 copies; no scripts, parts anchored. `within` without y measures the ground once at its centre (scatter_instances drops each copy onto rolling terrain). Plain clones: list a source more than once or pass copies (each source that many times; <=120 per call); a source may be a get_project_tree readRef.",
    input: v.object({ "paths": v.pipe(v.array(v.pipe(v.string(), v.maxLength(320))), v.maxLength(120), v.minLength(1)), "copies": v.optional(v.pipe(v.number(), v.maxValue(120), v.minValue(1), v.description("Clones of each listed source. Default 1."))), "parent": v.optional(v.pipe(v.string(), v.maxLength(320))), "at": v.optional(v.pipe(v.array(v.pipe(v.array(v.number()), v.maxLength(3), v.minLength(3))), v.maxLength(1000))), "along": v.optional(v.record(v.string(), v.unknown())), "within": v.optional(v.record(v.string(), v.unknown())), "yaw": v.optional(v.unknown()), "scale": v.optional(v.unknown()), "jitter": v.optional(v.pipe(v.number(), v.maxValue(1000), v.minValue(0))), "seed": v.optional(v.pipe(v.number(), v.integer())), "name": v.optional(v.pipe(v.string(), v.maxLength(96))) }),
  },
  {
    name: "group_instances",
    writes: true,
    description: "Group existing instances into a new Model. The plugin checks nesting, destination scope and path-name collisions before mutating.",
    input: v.object({ "paths": v.pipe(v.array(v.pipe(v.string(), v.maxLength(320))), v.maxLength(120), v.minLength(1)), "name": v.optional(v.pipe(v.string(), v.maxLength(96))) }),
  },
  {
    name: "rename_instance",
    writes: true,
    description: "Rename one existing instance without recreating it. Studio refuses protected structures and sibling-name collisions. path may be a readRef from get_project_tree: renaming one of several same-named siblings is how they become addressable by plain paths.",
    input: v.object({ "path": v.pipe(v.string(), v.maxLength(320)), "name": v.pipe(v.string(), v.maxLength(96)) }),
  },
  {
    name: "play_check",
    writes: true,
    description: "Playtest AS A PLAYER: starts a real Studio Test session with one player, waits `seconds`, optionally walks the character onto each `touch` part (e.g. a coin), then reports what the player's screen actually shows (every ScreenGui in PlayerGui, enabled or not, and its visible text), the player's leaderstats before and after, and the errors from BOTH the client (LocalScripts) and the server. Use it before you say a counter, HUD, button or other on-screen UI works — run_and_check has no player and cannot see the screen or any LocalScript. It does not press buttons: to prove a button flow (Shop → Buy) use play_check_ui, which clicks each button and reports what the click changed. The session runs on a copy of the place; its temporary check scripts are removed afterwards. It takes Studio over for up to about a minute.",
    input: v.object({ "seconds": v.optional(v.pipe(v.number(), v.description("3-15, default 5: how long the player stays in before the touches and the screen read"))), "touch": v.optional(v.pipe(v.array(v.string()), v.description("up to 5 BasePart/Model paths inside game.Workspace to walk onto, in order, e.g. [\"game.Workspace.Coins.Coin1\"]"))) }),
  },
];
