// GENERATED by apps/studio/scripts/gen-tools.mjs from apps/worker/src/tools.ts. Do not edit by hand.
export interface StudioToolSpec {
  name: string;
  /** Changes the place: the gate takes a checkpoint first, so the change can be undone. */
  writes: boolean;
  description: string;
  /** JSON Schema of the arguments, exactly as the worker defines it. */
  parameters: Record<string, unknown>;
}

export const STUDIO_TOOL_SPECS: readonly StudioToolSpec[] = [
  {
    name: "get_project_tree",
    writes: false,
    description: "Snapshot of the game instance tree with names, classes, measured part positions/sizes/anchoring when available, and duplicate-name warnings. Start here to understand a project. Siblings that share a name are marked: a plain path cannot select one of them, so never guess which is meant. Where the outline shows a readRef for one, that readRef is its address.",
    parameters: {"type":"object","properties":{"root":{"type":"string","description":"Path to start from, e.g. \"game.Workspace\". Default: whole game (key services)."},"maxDepth":{"type":"number","description":"Depth limit, default 4"}}},
  },
  {
    name: "get_instance",
    writes: false,
    description: "Read one instance back: its class, child count, common properties and attributes. Use it to VERIFY a change you just made, and quote what you actually saw rather than what you intended. Cheaper and more reliable than a run_luau that returns the same value. When a tree provides readRef for a duplicate-named instance, pass that exact readRef as path to read it; references expire and cannot authorize writes.",
    parameters: {"type":"object","properties":{"path":{"type":"string","description":"Full path, e.g. game.Workspace.Lobby.Floor"}},"required":["path"]},
  },
  {
    name: "list_scripts",
    writes: false,
    description: "List all scripts in the project with paths, class and line counts.",
    parameters: {"type":"object","properties":{"root":{"type":"string"}}},
  },
  {
    name: "read_script",
    writes: false,
    description: "Read script source by path. Normal scripts are returned completely; large scripts return an explicit line page with nextStartLine. Follow it with start_line until null before replacing the whole script. complete means this response contains the entire script. Every page carries the whole-file baseHash: pass it as base_hash on edit_script to reject concurrent edits.",
    parameters: {"type":"object","properties":{"path":{"type":"string"},"start_line":{"type":"integer","minimum":1,"description":"First line, one-based; follow nextStartLine when the source is paged."},"max_lines":{"type":"integer","minimum":1,"maximum":1000}},"required":["path"]},
  },
  {
    name: "search_scripts",
    writes: false,
    description: "Search all script sources for a string. Returns matches with paths and line numbers. For a NAME rather than a substring, find_symbol resolves scope and search_scripts does not.",
    parameters: {"type":"object","properties":{"query":{"type":"string"}},"required":["query"]},
  },
  {
    name: "get_output_logs",
    writes: false,
    description: "Read recent Studio output/console logs (errors, warnings, prints).",
    parameters: {"type":"object","properties":{}},
  },
  {
    name: "model_anatomy",
    writes: false,
    description: "Read a placed model: its parts, joints, hinge candidates and which way a positive angle turns a part, what is already clickable, lit or playing. Use before add_behaviour. Pass part for one part's detail.",
    parameters: {"type":"object","properties":{"model":{"type":"string"},"part":{"type":"string"},"maxParts":{"type":"number"}},"required":["model"]},
  },
  {
    name: "create_instances",
    writes: true,
    description: "Create instances (parts, models, lights...). Props are typed: {\"Position\":{\"t\":\"Vector3\",\"v\":[0,5,0]}, \"Material\":{\"t\":\"EnumItem\",\"v\":\"Enum.Material.Neon\"}, \"Color\":{\"t\":\"Color3\",\"v\":[1,0.5,0]}}. Types: string,number,bool,Vector3,Vector2,CFrame,Color3,UDim2,UDim,EnumItem,BrickColor,Content,NumberRange,NumberSequence,ColorSequence,Rect,Instance,nil. A propIssues result means the instances WERE created: fix them with set_properties. Per call: 120 items, 400 instances, 40 children each, 12 levels, 48 props each (longer lists are split for you). origin {at:[x,y,z], yaw?} builds in local space around (0,0,0) and places the batch; group {className:\"Model\"|\"Folder\", name, primaryPart?} wraps it (up to 120 items); build once, repeat with clone_instances. Plain parts (Part, WedgePart, CornerWedgePart, TrussPart) are Anchored unless Anchored is false; bare Size/Position/Orientation/Color arrays and Material/Shape names on parts are typed for you. Also creates AudioPlayer (Asset: a library sound id), AudioEmitter, Wire (SourceInstance/TargetInstance: paths of existing instances), the Audio effects, Animator, Animation, IKControl and Explosion (BlastPressure and DestroyJointRadiusPercent default to 0).",
    parameters: {"type":"object","properties":{"items":{"type":"array","minItems":1,"items":{"type":"object","properties":{"className":{"type":"string","description":"Roblox class, e.g. \"Part\""},"name":{"type":"string"},"parent":{"type":"string","description":"Path of an existing instance, e.g. \"Workspace.StreetLamp\". Default \"Workspace\"."},"props":{"type":"object","description":"Typed properties"},"attributes":{"type":"object"},"children":{"type":"array","description":"Nested items with the same fields (no parent)","items":{"type":"object"}}},"required":["className","name"]}},"origin":{"type":"object"},"group":{"type":"object"}},"required":["items"]},
  },
  {
    name: "set_properties",
    writes: true,
    description: "Set properties/attributes on an existing instance. Same typed prop format as create_instances. Reports what each value WAS, so you can quote the change rather than the intention. path may be a readRef from get_project_tree to change one of several same-named siblings.",
    parameters: {"type":"object","properties":{"path":{"type":"string"},"props":{"type":"object"},"attributes":{"type":"object"}},"required":["path"]},
  },
  {
    name: "delete_instances",
    writes: true,
    description: "Delete instances by path only when the user asked for removal or after a replacement is already verified in Studio. A duplicate-name create error means the existing object should be inspected and edited or renamed; never delete working paths or props to make that name available. To remove one of several same-named copies, pass its readRef from get_project_tree in place of the path.",
    parameters: {"type":"object","properties":{"paths":{"type":"array","items":{"type":"string"}}},"required":["paths"]},
  },
  {
    name: "clone_instances",
    writes: true,
    description: "Clone instances (collision-free names; optional parent). MANY COPIES IN ONE CALL: `paths` (a template, up to 8 cycled) plus exactly one of `at` [[x,y,z],...], `along` {points, spacing|count} or `within` {rect:{min:[x,z],max:[x,z]}|polygon, count, minSpacing?, y?}; optional yaw (number or [min,max]), scale, jitter, seed, name, parent. Up to 1000 copies; no scripts, parts anchored. `within` without y measures the ground once at its centre (scatter_instances drops each copy onto rolling terrain). Plain clones: list a source more than once or pass copies (each source that many times; <=120 per call); a source may be a get_project_tree readRef.",
    parameters: {"type":"object","properties":{"paths":{"type":"array","minItems":1,"maxItems":120,"items":{"type":"string","maxLength":320}},"copies":{"type":"number","minimum":1,"maximum":120,"description":"Clones of each listed source. Default 1."},"parent":{"type":"string","maxLength":320},"at":{"type":"array","items":{"type":"array","items":{"type":"number"},"minItems":3,"maxItems":3},"maxItems":1000},"along":{"type":"object"},"within":{"type":"object"},"yaw":{},"scale":{},"jitter":{"type":"number","minimum":0,"maximum":1000},"seed":{"type":"integer"},"name":{"type":"string","maxLength":96}},"required":["paths"]},
  },
  {
    name: "transform_instances",
    writes: true,
    description: "Move, rotate and/or uniformly scale existing spatial instances as one bounded typed Studio edit. move is studs, rotate is degrees, scale is a positive multiplier.",
    parameters: {"type":"object","properties":{"paths":{"type":"array","minItems":1,"maxItems":120,"items":{"type":"string","maxLength":320}},"move":{"type":"array","minItems":3,"maxItems":3,"items":{"type":"number"}},"rotate":{"type":"array","minItems":3,"maxItems":3,"items":{"type":"number"}},"scale":{"type":"number","minimum":0.001,"maximum":1000}},"required":["paths"]},
  },
  {
    name: "edit_script",
    writes: true,
    description: "Create or edit a script. Provide exactly one of `source` (full new content), `edits` (find/replace list, exact match), or `source_file` (an exact saved .lua/.luau workspace version). One exact edit: edits:[{find:\"exact old text\",replace:\"new text\"}]; top-level find + replace is the same shorthand, never combined with another input. A new script: set `create_class` + `create_parent`. The result is parsed BEFORE it is written: a body that does not compile is refused, nothing changed. A script that newly assembles a Model from Parts waits until the library was tried (find_library_model). `base_hash` from read_script also refuses a write over a concurrent Studio edit.",
    parameters: {"type":"object","properties":{"path":{"type":"string","description":"Full path, e.g. game.ServerScriptService.RoundManager"},"source":{"type":"string"},"find":{"type":"string","description":"Single-edit shorthand: non-empty exact old text. Requires replace; omit source, edits and source_file."},"replace":{"type":"string","description":"Single-edit shorthand: replacement text, including an empty string for deletion. Requires find."},"all":{"type":"boolean","description":"For the single-edit shorthand only: replace all exact occurrences."},"baseHash":{"type":"string","description":"Alias for base_hash; both must match."},"edits":{"type":"array","items":{"type":"object","properties":{"find":{"type":"string"},"replace":{"type":"string"},"all":{"type":"boolean"}},"required":["find","replace"]}},"source_file":{"type":"object","properties":{"path":{"type":"string","description":"Project workspace path ending in .lua or .luau."},"version":{"type":"number","description":"Exact saved workspace version to use. No latest-version fallback."}},"required":["path","version"]},"create_class":{"type":"string","enum":["Script","LocalScript","ModuleScript"]},"create_parent":{"type":"string","description":"Parent path when creating"},"base_hash":{"type":"string","description":"The `baseHash` read_script returned for this path. The edit is refused if the file has changed since."}},"required":["path"]},
  },
  {
    name: "run_luau",
    writes: true,
    description: "Run a Luau snippet in Studio (edit-time, plugin context) for inspection, bulk edits and math when a typed tool does not cover the job. Use edit_terrain for Terrain. print() output and the returned value come back. No game scripts run. It may NOT be used to bring assets into the place: GetObjects, InsertService, rbxassetid://, Content.fromAssetId, loadstring and require of an asset id are refused here — use insert_asset, which verifies the id and scans the place afterwards.",
    parameters: {"type":"object","properties":{"code":{"type":"string"}},"required":["code"]},
  },
  {
    name: "edit_terrain",
    writes: true,
    description: "Edit Roblox smooth Terrain through bounded typed operations (no arbitrary Luau). Actions: clear (no fields; empties ALL Terrain in one call — use it for \"clear/remove the terrain\", never Air fills), fill_block (center,size,material), fill_ball (center,radius,material), fill_region (min,max,material), replace_material (min,max,sourceMaterial,targetMaterial), write_voxels (4-stud-grid origin, integer dimensions, flat voxels [{material,occupancy}]) or path. Materials are Enum.Material names (Enum.Material.Grass). At most 65,536 voxels per call. Needs Studio edit consent; one undo-recorded change. Checkpoint restore does not keep voxels: roll terrain back with Studio Undo. RECIPES FIRST for these landforms: \"floating_island\" (center, radius), a flat grassy top on a rock underside tapering to a point, returns surfaceY to stand things on; \"waterfall\" (top = the edge it pours over, height, width, endsIn) hangs a thin sheet of water. A CHANNEL OR LINE OF TERRAIN ALONG POINTS IS ONE CALL: action \"path\", points [[x,y,z],...] (2-32; y = the surface, or the ceiling of a covered cut), width, depth (studs down), fill \"Air\" (default), \"Water\" (waterLevel 0-1: share of the depth filled, default 0.75) or \"material\" (with `material`); run as blocks, at most 256 per call. BUILD A WHOLE FEATURE IN ONE CALL: pass operations (up to 32 of the actions above, each with its own fields); they run in order: overlapping fill_balls of decreasing radius make a mound; Air then a smaller Water ball, a basin. One operation per call costs a step each.",
    parameters: {"type":"object","properties":{"operations":{"type":"array","description":"Up to 32 actions run in order, each shaped like a single call. Stops at the first failure.","items":{"type":"object"}},"recipe":{"type":"string","enum":["floating_island","waterfall"],"description":"floating_island {center, radius 12-70}; waterfall {top, height, width, endsIn: \"pool\"|\"mist\"}."},"top":{"type":"array","items":{"type":"number"}},"height":{"type":"number"},"width":{"type":"number"},"endsIn":{"type":"string","enum":["pool","mist"]},"action":{"type":"string","enum":["clear","fill_block","fill_ball","fill_region","replace_material","write_voxels","path"]},"points":{"type":"array","items":{"type":"array","items":{"type":"number"}}},"depth":{"type":"number"},"fill":{"type":"string","enum":["Air","Water","material"]},"waterLevel":{"type":"number","minimum":0,"maximum":1},"center":{"type":"array","items":{"type":"number"}},"size":{"type":"array","items":{"type":"number"}},"radius":{"type":"number"},"min":{"type":"array","items":{"type":"number"}},"max":{"type":"array","items":{"type":"number"}},"material":{"type":"string"},"sourceMaterial":{"type":"string"},"targetMaterial":{"type":"string"},"origin":{"type":"array","items":{"type":"number"}},"dimensions":{"type":"array","items":{"type":"number"}},"voxels":{"type":"array","items":{"type":"object"}}}},
  },
  {
    name: "insert_from_store",
    writes: true,
    description: "Insert a Creator Store asset (model, mesh, decal, audio) you found with search_creator_store into the place. It lands in a holder folder under `parent`; any scripts inside are removed and reported. Returns the inserted paths and their bounding size, so you can inspect (get_instance, model_anatomy), then scale and position it (transform_instances) and rename or re-parent it to fit the request. Delete it if it does not fit.",
    parameters: {"type":"object","properties":{"assetId":{"type":"number"},"parent":{"type":"string","description":"Where to put it. Default game.Workspace."}},"required":["assetId"]},
  },
  {
    name: "animate_model",
    writes: true,
    description: "Make a model move: rig it, then keyframe clips. Read creation skill props-rig-animate first.",
    parameters: {"type":"object","properties":{"model":{"type":"string"},"rig":{"type":"object"},"clips":{"type":"object"}},"required":["model","clips"]},
  },
  {
    name: "play_check",
    writes: true,
    description: "Playtest AS A PLAYER: starts a real Studio Test session with one player, waits `seconds`, optionally walks the character onto each `touch` part (e.g. a coin), then reports what the player's screen actually shows (every ScreenGui in PlayerGui, enabled or not, and its visible text), the player's leaderstats before and after, and the errors from BOTH the client (LocalScripts) and the server. Use it before you say a counter, HUD, button or other on-screen UI works — run_and_check has no player and cannot see the screen or any LocalScript. It does not press buttons: to prove a button flow (Shop → Buy) use play_check_ui, which clicks each button and reports what the click changed. The session runs on a copy of the place; its temporary check scripts are removed afterwards. It takes Studio over for up to about a minute.",
    parameters: {"type":"object","properties":{"seconds":{"type":"number","description":"3-15, default 5: how long the player stays in before the touches and the screen read"},"touch":{"type":"array","items":{"type":"string"},"description":"up to 5 BasePart/Model paths inside game.Workspace to walk onto, in order, e.g. [\"game.Workspace.Coins.Coin1\"]"}}},
  },
];
