/**
 * THE BRAND: one mark, drawn here, used everywhere, and the three old logos gone.
 *
 * packages/design/brand/studpilot-mark.svg is the only drawing of the StudPilot mark. Everything that
 * shows it (the site header and footer, the app's rail and sign-in screens, the assistant's avatar,
 * the favicons, the share card, the dashboards) carries that same path, and this file holds them
 * equal by READING each one, not by being told they are.
 *
 * It also holds the retirement: the azure studded brick, the folded-sheet outline and the hexagon
 * holding a cube were three drawings in production at once (planning/sections/10-web-brand-design.md
 * 10.5.2). None of their files, none of their geometry and none of their palette may come back.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { readTokensCss, theme, themeBlocks } from './css-tokens.mjs';
import { ROOT, readText, walkText } from './tests/repo-walk.mjs';

const abs = (rel) => join(ROOT, rel);
const read = (rel) => readFileSync(abs(rel), 'utf8');
const BRAND = 'packages/design/brand';

const MARK = read(`${BRAND}/studpilot-mark.svg`);
const pathOf = (src) => /\sd="([^"]+)"/.exec(src)?.[1] ?? null;
const MARK_PATH = pathOf(MARK);

/** Width and height of a PNG, read from its IHDR chunk. Throws on anything that is not a PNG. */
function pngSize(rel) {
  const b = readFileSync(abs(rel));
  assert.equal(b.subarray(1, 4).toString('latin1'), 'PNG', `${rel} is not a PNG`);
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

/* ------------------------------------------------------------------ the mark */

test('the mark is one filled path in currentColor, simple enough for 16 px', () => {
  assert.ok(MARK_PATH, 'no path in studpilot-mark.svg');
  assert.match(MARK, /<svg[^>]*viewBox="0 0 32 32"/, 'the mark is drawn on a 32 unit canvas');
  assert.match(MARK, /<svg[^>]*fill="currentColor"/, 'the mark must take its colour from the page (currentColor)');
  assert.equal([...MARK.matchAll(/<path\b/g)].length, 1, 'the mark is one path');
  assert.doesNotMatch(MARK, /#[0-9a-f]{3,8}\b|rgba?\(|<image|<text|<linearGradient|<radialGradient|filter=/i, 'the mark carries a hard-coded colour, a gradient, an image or text');
  assert.match(MARK, /fill-rule="evenodd"/, 'the stud must be a real hole (even-odd), not a painted circle');
  assert.equal([...MARK_PATH.matchAll(/Z/gi)].length, 2, 'expected exactly two closed shapes: the tile and the stud');
  // Few segments: a mark that survives 16 px has little in it. Counting path commands is the proxy.
  assert.ok([...MARK_PATH.matchAll(/[MLHVQAZa-z]/g)].length <= 24, 'the mark is too intricate to read at 16 px');
});

test('the provenance states the mark was drawn here by Claude Code, not generated by an image service', () => {
  const p = read(`${BRAND}/PROVENANCE.md`);
  assert.match(p, /drawn in this repository by Claude Code/i);
  assert.match(p, /not generated by an AI image service/i);
  assert.match(p, /vector path data/i);
});

test('the wordmark lockup is the mark plus live text in the system font', () => {
  const w = read(`${BRAND}/studpilot-wordmark.svg`);
  assert.equal(pathOf(w), MARK_PATH, 'the lockup does not carry the mark');
  assert.match(w, /<text\b[^>]*>StudPilot<\/text>/, 'the lockup has no StudPilot text');
  assert.match(w, /font-family="-apple-system/, 'the lockup text is not set in the system stack');
  assert.doesNotMatch(w, /<image|@font-face|url\(/i, 'the lockup pulls in an image or a font');
});

/* ------------------------------------------------------------------ one drawing, everywhere */

/** The default dark base and accent: what the favicon is made of. */
const dark = theme(themeBlocks(readTokensCss()).dark);
const PAPER = dark.resolve('paper');
const ACCENT = dark.resolve('accent');

/** The favicon exactly as scripts/make-brand-assets.mjs composes it (kept in step by this test). */
const SCALE = 0.74;
const OFFSET = ((32 - 32 * SCALE) / 2).toFixed(2);
const faviconText = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" aria-label="StudPilot">` +
  `<rect width="32" height="32" rx="7" fill="${PAPER}"/>` +
  `<path transform="translate(${OFFSET} ${OFFSET}) scale(${SCALE})" fill="${ACCENT}" fill-rule="evenodd" d="${MARK_PATH}"/></svg>\n`;

test('the favicon is composed from the mark and the tokens, and every copy of it is identical', () => {
  for (const rel of [`${BRAND}/favicon.svg`, 'apps/site/public/favicon.svg', 'tools/repo-chat/public/favicon.svg']) {
    assert.equal(read(rel), faviconText, `${rel} is not the favicon composed from the mark and tokens.css; run \`pnpm brand\``);
  }
});

test('every place that draws the mark draws the same path', () => {
  const sources = {
    'the site header and footer': ['apps/site/src/components/StudPilotMark.astro', (s) => pathOf(s)],
    'the app rail, sign-in and illustrations': ['apps/web/src/components/glyphs.tsx', (s) => /export const MARK_PATH = '([^']+)'/.exec(s)?.[1]],
    'the share card source': ['apps/site/brand/og.html', (s) => pathOf(s)],
    'the owner dashboard rail': ['scripts/owner-dashboard/control/index.html', (s) => /<svg class="brand-m"[^>]*><path d="([^"]+)"/.exec(s)?.[1]],
    'the owner dashboard registry': ['scripts/owner-dashboard/control/logos.js', (s) => /STUDPILOT_MARK = '<path d="([^"]+)"/.exec(s)?.[1]],
  };
  for (const [what, [rel, extract]] of Object.entries(sources)) {
    assert.equal(extract(read(rel)), MARK_PATH, `${what} (${rel}) does not draw the StudPilot mark`);
  }
  // The assistant's avatar spends the same constant rather than a path of its own.
  const model = read('apps/web/src/components/ws/model-mark.tsx');
  assert.match(model, /import \{ MARK_PATH \} from '\.\.\/glyphs'/, 'the assistant avatar does not import the mark');
  assert.doesNotMatch(model, /\sd="M/, 'the assistant avatar draws a path of its own');
});

test("the app's inline favicon decodes to the same favicon", () => {
  const html = read('apps/web/index.html');
  const href = /rel="icon"\s+href="(data:image\/svg\+xml,[^"]+)"/.exec(html)?.[1];
  assert.ok(href, 'apps/web/index.html has no inline SVG favicon');
  const svg = decodeURIComponent(href.slice('data:image/svg+xml,'.length));
  assert.equal(svg.replace(/'/g, '"') + '\n', faviconText, 'the web app favicon is not the brand favicon');
});

/* ------------------------------------------------------------------ the raster set */

test('the PNG icon set exists at the right sizes, and the site serves the same bytes', () => {
  for (const [rel, [w, h]] of Object.entries({
    [`${BRAND}/icon-16.png`]: [16, 16],
    [`${BRAND}/icon-32.png`]: [32, 32],
    [`${BRAND}/icon-180.png`]: [180, 180],
    [`${BRAND}/icon-512.png`]: [512, 512],
    'apps/site/public/apple-touch-icon.png': [180, 180],
    'apps/site/public/icon-192.png': [192, 192],
    'apps/site/public/icon-512.png': [512, 512],
    'apps/site/public/og.png': [1200, 630],
  })) {
    assert.deepEqual(pngSize(rel), [w, h], `${rel} is not ${w}x${h}`);
    assert.ok(readFileSync(abs(rel)).length > 200, `${rel} is suspiciously small`);
  }
  assert.ok(readFileSync(abs(`${BRAND}/icon-512.png`)).equals(readFileSync(abs('apps/site/public/icon-512.png'))), 'the site icon-512 is not the brand icon-512');
  assert.ok(readFileSync(abs(`${BRAND}/icon-180.png`)).equals(readFileSync(abs('apps/site/public/apple-touch-icon.png'))), 'the apple-touch-icon is not the brand icon-180');
});

test('the site links the favicon and touch icon, and its manifest points at icons that exist', () => {
  for (const rel of ['apps/site/src/layouts/Base.astro', 'apps/site/src/layouts/Landing.astro']) {
    const src = read(rel);
    assert.match(src, /rel="icon" href="\/favicon\.svg"/, `${rel} does not link /favicon.svg`);
    assert.match(src, /rel="apple-touch-icon"[^>]*href="\/apple-touch-icon\.png"/, `${rel} does not link the touch icon`);
  }
  const manifest = JSON.parse(read('apps/site/public/site.webmanifest'));
  assert.ok(manifest.icons.length >= 2, 'the manifest lists fewer than two icons');
  for (const icon of manifest.icons) {
    const rel = `apps/site/public${icon.src}`;
    assert.ok(existsSync(abs(rel)), `the manifest names ${icon.src}, which does not exist`);
    const [w] = pngSize(rel);
    assert.equal(`${w}x${w}`, icon.sizes, `${icon.src} is ${w}px but the manifest says ${icon.sizes}`);
  }
});

/* ------------------------------------------------------------------ the three old logos are gone */

/** Geometry and palette of the three retired drawings, as fragments any copy of them must contain. */
const OLD_LOGO_FRAGMENTS = [
  // the folded-sheet outline (site header and footer, the web favicon, the assistant avatar, the dashboards)
  '5 24 12 5 19 14', 'm5 24 7-19 7 9', '12 5 1 13 6-4',
  // the hexagon holding a cube (the rail glyph, the wait pulse, the empty-state illustrations)
  '27.26 9.5', '4.74 9.5', 'm8 1.5l5.5 3.5', '122.91 49', '134.64 48', '84.2 18.5',
  // the azure studded brick (favicon, icon set, share card) and its source render
  '24 11 37 18.5', '11 18.5 24 26', '#3d93e8', '#0f62c4', '#0a468f', 'studpilot-mark-source',
];
/** The old files: the render the brick came from. (The icons and favicon were regenerated in place.) */
const OLD_LOGO_FILES = ['apps/site/brand/studpilot-mark-source.png'];

const findOldLogo = (src) => OLD_LOGO_FRAGMENTS.filter((f) => src.toLowerCase().includes(f));

test('no file of the three old logos exists', () => {
  for (const rel of OLD_LOGO_FILES) assert.ok(!existsSync(abs(rel)), `${rel} is an old logo file and must stay deleted`);
});

test('no geometry, palette or source name of the three old logos appears anywhere in the tree', () => {
  const files = walkText(['apps', 'packages', 'scripts', 'tools', 'infra', 'tests', '.github'], {
    skipPaths: ['packages/asset-library', 'packages/corpus', 'packages/training', 'packages/owner-corpus', 'packages/design/src/web'],
  });
  assert.ok(files.length > 1500, `only ${files.length} files scanned; the walk has drifted`);
  const hits = [];
  for (const f of files) for (const frag of findOldLogo(readText(f))) hits.push(`${f.rel}: ${frag}`);
  assert.deepEqual(hits, [], `an old logo drawing is still in the tree:\n  ${hits.join('\n  ')}`);
});

test('the guard has teeth: it finds each old logo in the form it shipped', () => {
  const folded = '<path d="M5 24 12 5 19 14 27 8 21 27 13 18Z"/><path d="m5 24 7-19 7 9 8-6-6 19-8-9-8 6Z"/>';
  const hexagon = '<path d="M16 3 L27.26 9.5 L27.26 22.5 L16 29 L4.74 22.5 L4.74 9.5 Z"/>';
  const brick = '<polygon points="24 11 37 18.5 24 26 11 18.5" fill="#3D93E8"/>';
  for (const [name, src] of Object.entries({ folded, hexagon, brick })) assert.ok(findOldLogo(src).length > 0, `the ${name} logo is not detected`);
  assert.deepEqual(findOldLogo(MARK), [], 'the new mark must not trip the old-logo guard');
});
