/**
 * THE BRAND: one mark, drawn here, used everywhere, and the three old logos gone.
 *
 * packages/design/brand/studpilot-mark.svg is the only drawing of the StudPilot mark. Everything that
 * shows it (the site header and footer, the app's rail and sign-in screens, the assistant's avatar,
 * the favicons, the share card, the dashboards) carries that same path, and this file holds them
 * equal by READING each one, not by being told they are.
 *
 * The generated assets are held to their sources without a browser: a manifest records a hash of what
 * every PNG is made from and of every PNG as written (brand-recipe.mjs), and this file recomputes both
 * from the tree, so a changed mark, a changed token or a PNG that was swapped or left behind fails in
 * `pnpm -r test` on any machine. scripts/make-brand-assets.mjs --check adds a re-render and runs in CI.
 *
 * It also holds the retirement: the azure studded brick, the folded-sheet outline and the hexagon
 * holding a cube were three drawings in production at once (planning/sections/10-web-brand-design.md
 * 10.5.2). None of their files, none of their geometry and none of their palette may come back.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  FAVICON_COPIES, MANIFEST_FILE, MARK_FILE, OG_SOURCE, PNGS, TOKENS_FILE, WEB_FAVICON_FILE,
  brandSources, cardLinks, cardProblems, iconSvg, manifestOf, manifestProblems, readManifest, withWebFavicon,
} from './brand-recipe.mjs';
import { ROOT, readText, walkText } from './tests/repo-walk.mjs';

const abs = (rel) => join(ROOT, rel);
const read = (rel) => readFileSync(abs(rel), 'utf8');
const BRAND = 'packages/design/brand';

const MARK = read(`${BRAND}/studpilot-mark.svg`);
/** The number of drawing commands in an SVG path `d`: every command letter, either case, and not an exponent's e. */
const pathCommands = (d) => [...d.replace(/\d[eE][+-]?\d/g, '0').matchAll(/[MLHVCSQTAZmlhvcsqtaz]/g)].length;
const pathOf = (src) => /\sd="([^"]+)"/.exec(src)?.[1] ?? null;
const MARK_PATH = pathOf(MARK);

/** Width and height of a PNG, read from its IHDR chunk. Throws on anything that is not a PNG. */
function pngSize(rel) {
  const b = readFileSync(abs(rel));
  assert.equal(b.subarray(1, 4).toString('latin1'), 'PNG', `${rel} is not a PNG`);
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

/* ------------------------------------------------------------------ the mark */

test('the mark is one filled path in currentColor, simple enough for 16 px', () => {
  assert.ok(MARK_PATH, 'no path in studpilot-mark.svg');
  assert.match(MARK, /<svg[^>]*viewBox="0 0 32 32"/, 'the mark is drawn on a 32 unit canvas');
  assert.match(MARK, /<svg[^>]*fill="currentColor"/, 'the mark must take its colour from the page (currentColor)');
  assert.equal([...MARK.matchAll(/<path\b/g)].length, 1, 'the mark is one path');
  assert.doesNotMatch(MARK, /#[0-9a-f]{3,8}\b|rgba?\(|<image|<text|<linearGradient|<radialGradient|filter=/i, 'the mark carries a hard-coded colour, a gradient, an image or text');
  assert.match(MARK, /fill-rule="evenodd"/, 'the stud must be a real hole (even-odd), not a painted circle');
  assert.equal([...MARK_PATH.matchAll(/Z/gi)].length, 2, 'expected exactly two closed shapes: the tile and the stud');
  // Few segments: a mark that survives 16 px has little in it. Counting path commands is the proxy.
  assert.ok(pathCommands(MARK_PATH) <= 24, `the mark has ${pathCommands(MARK_PATH)} path commands; that is too intricate to read at 16 px`);
  assert.ok(pathCommands(MARK_PATH) >= 8, 'the command count is implausibly low; the proxy is not reading the path');
});

test('the guard has teeth: the intricacy proxy counts every path command, cubic and smooth curves included', () => {
  // The first version counted M L H V Q A Z and every LOWERCASE letter, so an absolute C, S or T
  // (a cubic, a smooth cubic, a smooth quadratic) was not counted: a mark drawn in cubics read as simple.
  assert.equal(pathCommands('M0 0C1 1 2 2 3 3C4 4 5 5 6 6S7 7 8 8T9 9Z'), 6, 'an absolute C, S or T was not counted');
  assert.equal(pathCommands('m0 0c1 1 2 2 3 3s4 4 5 5t6 6z'), 5, 'a relative c, s or t was not counted');
  assert.equal(pathCommands('M12 3H27.8Q29 3 29 4.2V20A9 9 0 0 1 20 29Z'), 6, 'the drawing\'s own commands miscounted');
  assert.equal(pathCommands('M1e-3 2E+2L3 4'), 2, 'an exponent in a number was counted as a command');
  const flower = 'M0 0' + 'C1 1 2 2 3 3'.repeat(30) + 'Z';
  assert.ok(pathCommands(flower) > 24, 'a path of thirty cubics passed the intricacy bar');
});

test('the provenance states the mark was drawn here by Claude Code, not generated by an image service', () => {
  const p = read(`${BRAND}/PROVENANCE.md`);
  assert.match(p, /drawn in this repository by Claude Code/i);
  assert.match(p, /not generated by an AI image service/i);
  assert.match(p, /vector path data/i);
});

test('the wordmark lockup is the mark plus live text in the system font', () => {
  const w = read(`${BRAND}/studpilot-wordmark.svg`);
  assert.equal(pathOf(w), MARK_PATH, 'the lockup does not carry the mark');
  assert.match(w, /<text\b[^>]*>StudPilot<\/text>/, 'the lockup has no StudPilot text');
  assert.match(w, /font-family="-apple-system/, 'the lockup text is not set in the system stack');
  assert.doesNotMatch(w, /<image|@font-face|url\(/i, 'the lockup pulls in an image or a font');
});

/* ------------------------------------------------------------------ one drawing, everywhere */

/** The favicon exactly as the generator composes it: both read the one recipe in brand-recipe.mjs. */
const faviconText = iconSvg(brandSources());

test('the favicon is composed from the mark and the tokens, and every copy of it is identical', () => {
  assert.ok(FAVICON_COPIES.length >= 3, 'the generator lists fewer than three standalone favicon copies');
  for (const rel of FAVICON_COPIES) {
    assert.equal(read(rel), faviconText, `${rel} is not the favicon composed from the mark and tokens.css; run \`pnpm brand\``);
  }
});

test('no file carries a favicon the generator does not write', () => {
  // The recipe's signature: a 32 unit tile with a radius of 7, in either quoting (the app inlines it as
  // a data: URI). A copy made by hand somewhere new would be stale the next time the mark or the accent moves.
  const signature = /width=['"]32['"] height=['"]32['"] rx=['"]7['"]/;
  const files = walkText(['apps', 'packages', 'tools', 'scripts', 'infra', 'tests', '.github']);
  assert.ok(files.length > 1500, `only ${files.length} files scanned; the walk has drifted`);
  const carriers = files.filter((f) => !f.rel.startsWith('packages/design/src/web/') && signature.test(readText(f))).map((f) => f.rel).sort();
  assert.deepEqual(carriers, [...FAVICON_COPIES, WEB_FAVICON_FILE].sort(), 'a favicon copy exists that scripts/make-brand-assets.mjs does not regenerate, or one it regenerates is gone');
});

test('every place that draws the mark draws the same path', () => {
  const sources = {
    'the site header and footer': ['apps/site/src/components/StudPilotMark.astro', (s) => pathOf(s)],
    'the app rail, sign-in and illustrations': ['apps/web/src/components/glyphs.tsx', (s) => /export const MARK_PATH = '([^']+)'/.exec(s)?.[1]],
    'the share card source': ['apps/site/brand/og.html', (s) => pathOf(s)],
    'the owner dashboard rail': ['scripts/owner-dashboard/control/index.html', (s) => /<svg class="brand-m"[^>]*><path d="([^"]+)"/.exec(s)?.[1]],
    'the owner dashboard registry': ['scripts/owner-dashboard/control/logos.js', (s) => /STUDPILOT_MARK = '<path d="([^"]+)"/.exec(s)?.[1]],
  };
  for (const [what, [rel, extract]] of Object.entries(sources)) {
    assert.equal(extract(read(rel)), MARK_PATH, `${what} (${rel}) does not draw the StudPilot mark`);
  }
  // The assistant's avatar spends the same constant rather than a path of its own.
  const model = read('apps/web/src/components/ws/model-mark.tsx');
  assert.match(model, /import \{ MARK_PATH \} from '\.\.\/glyphs'/, 'the assistant avatar does not import the mark');
  assert.doesNotMatch(model, /\sd="M/, 'the assistant avatar draws a path of its own');
});

test("the app's inline favicon decodes to the same favicon", () => {
  const html = read(WEB_FAVICON_FILE);
  const href = /rel="icon"\s+href="(data:image\/svg\+xml,[^"]+)"/.exec(html)?.[1];
  assert.ok(href, 'apps/web/index.html has no inline SVG favicon');
  const svg = decodeURIComponent(href.slice('data:image/svg+xml,'.length));
  assert.equal(svg.replace(/'/g, '"') + '\n', faviconText, 'the web app favicon is not the brand favicon');
  assert.equal(withWebFavicon(html, faviconText), html, `${WEB_FAVICON_FILE} is not what the generator writes around its inline favicon; run \`pnpm brand\``);
});

/* ------------------------------------------------------------------ the raster set */

test('the PNG icon set exists at the right sizes, and the site serves the same bytes', () => {
  for (const [rel, [w, h]] of Object.entries({
    [`${BRAND}/icon-16.png`]: [16, 16],
    [`${BRAND}/icon-32.png`]: [32, 32],
    [`${BRAND}/icon-180.png`]: [180, 180],
    [`${BRAND}/icon-512.png`]: [512, 512],
    'apps/site/public/apple-touch-icon.png': [180, 180],
    'apps/site/public/icon-192.png': [192, 192],
    'apps/site/public/icon-512.png': [512, 512],
    'apps/site/public/og.png': [1200, 630],
  })) {
    assert.deepEqual(pngSize(rel), [w, h], `${rel} is not ${w}x${h}`);
    assert.ok(readFileSync(abs(rel)).length > 200, `${rel} is suspiciously small`);
  }
  assert.ok(readFileSync(abs(`${BRAND}/icon-512.png`)).equals(readFileSync(abs('apps/site/public/icon-512.png'))), 'the site icon-512 is not the brand icon-512');
  assert.ok(readFileSync(abs(`${BRAND}/icon-180.png`)).equals(readFileSync(abs('apps/site/public/apple-touch-icon.png'))), 'the apple-touch-icon is not the brand icon-180');
});

/* ------------------------------------------------------------------ the PNGs are tied to what they are made from */

const STORED = readManifest();

test('the manifest names every PNG the generator writes, and the input each is made from', () => {
  assert.deepEqual(Object.keys(STORED.outputs).sort(), PNGS.map((p) => p.out).sort(), `${MANIFEST_FILE} lists a different set of PNGs than the generator writes`);
  assert.deepEqual(Object.keys(STORED.inputs).sort(), ['icon', 'iconSquare', 'og'], 'the manifest must hash the three inputs: the round icon, the touch icon and the share card');
  for (const p of PNGS) assert.equal(STORED.outputs[p.out].input, p.input, `${p.out} is recorded as made from the wrong input`);
  assert.match(STORED.renderedOn, /^(darwin|linux|win32)$/, 'the manifest does not say which platform drew the share card');
});

test('every PNG is the one the generator wrote, from the mark, the tokens and the card as they are now', () => {
  // Recomputed from the tree, no browser: the icon SVG as composed from the mark and the dark tokens,
  // the share card's HTML with the token file it links, and the bytes of every PNG on disk.
  assert.deepEqual(manifestProblems(STORED, manifestOf(ROOT, STORED.renderedOn)), [], 'a PNG is stale: it was not made from the sources as they are now');
});

test('the guard has teeth: a swapped PNG, a moved mark, an edited card or a moved token is reported', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'brand-teeth-'));
  try {
    const copy = (rel) => { mkdirSync(dirname(join(tmp, rel)), { recursive: true }); cpSync(abs(rel), join(tmp, rel)); };
    for (const rel of [MARK_FILE, TOKENS_FILE, OG_SOURCE, ...PNGS.map((p) => p.out)]) copy(rel);
    const probe = () => manifestProblems(STORED, manifestOf(tmp, STORED.renderedOn));
    assert.deepEqual(probe(), [], 'the copy of the tree is not current; the fixture is wrong');

    // 1. an old or wrong PNG put in place of a current one
    const victim = PNGS.find((p) => p.out === 'apps/site/public/icon-192.png').out;
    const keep = readFileSync(join(tmp, victim));
    writeFileSync(join(tmp, victim), readFileSync(abs('packages/design/brand/icon-32.png')));
    assert.ok(probe().some((m) => m.startsWith(victim) && /not the PNG the generator wrote/.test(m)), 'a swapped PNG was not reported');
    writeFileSync(join(tmp, victim), keep);

    // 2. the mark moves and nobody regenerates
    const mark = readFileSync(join(tmp, MARK_FILE), 'utf8');
    writeFileSync(join(tmp, MARK_FILE), mark.replace(/Q29 3 29 4\.2/, 'Q29 3 29 5.2'));
    assert.notEqual(readFileSync(join(tmp, MARK_FILE), 'utf8'), mark, 'the fixture did not change the mark');
    const moved = probe();
    assert.ok(moved.some((m) => /"icon" render inputs changed/.test(m)) && moved.some((m) => /"iconSquare" render inputs changed/.test(m)), 'a moved mark was not reported');
    writeFileSync(join(tmp, MARK_FILE), mark);

    // 3. the share card is edited
    const card = readFileSync(join(tmp, OG_SOURCE), 'utf8');
    writeFileSync(join(tmp, OG_SOURCE), card + '\n<!-- edited -->\n');
    assert.ok(probe().some((m) => /"og" render inputs changed/.test(m)), 'an edited card was not reported');
    writeFileSync(join(tmp, OG_SOURCE), card);

    // 4. a token moves (the card links the whole token file)
    const tokens = readFileSync(join(tmp, TOKENS_FILE), 'utf8');
    // The paper's CURRENT value, nudged by one in its last channel (a literal here went stale when the surfaces moved).
    const paper = /--paper: #([0-9a-f]{6});/.exec(tokens);
    assert.ok(paper, 'the token file no longer declares --paper as a hex colour');
    const nudged = paper[1].slice(0, 4) + ((parseInt(paper[1].slice(4), 16) + 1) % 256).toString(16).padStart(2, '0');
    writeFileSync(join(tmp, TOKENS_FILE), tokens.replace(paper[0], `--paper: #${nudged};`));
    const dim = probe();
    assert.ok(dim.some((m) => /"og" render inputs changed/.test(m)) && dim.some((m) => /"icon" render inputs changed/.test(m)), 'a moved base colour was not reported for the icon and the card');
    writeFileSync(join(tmp, TOKENS_FILE), tokens);

    // 5. a PNG the manifest does not know, and one it lists that the generator dropped
    assert.ok(manifestProblems({ ...STORED, outputs: { ...STORED.outputs, 'apps/site/public/old.png': { input: 'icon', sha256: '0' } } }, manifestOf(tmp, STORED.renderedOn)).some((m) => /no longer writes/.test(m)), 'a stale manifest entry was not reported');
    assert.deepEqual(probe(), [], 'the fixture was not restored');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

/* ------------------------------------------------------------------ the share card must have its tokens */

test('the share card reaches its tokens: its stylesheet link resolves to the token file, and every token it spends is declared', () => {
  // The generator reported "BRAND ASSETS OK" and wrote a white, serif, unstyled og.png when this link was broken, because
  // the manifest hashes og.html and tokens.css by PATH from the recipe, not the file the browser actually loaded.
  const { hrefs, spends } = cardLinks(ROOT);
  assert.ok(hrefs.length >= 1, 'no stylesheet link was found in the card; the scan is blind');
  assert.ok(spends.length >= 8, `only ${spends.length} tokens found in the card; the scan is blind`);
  assert.deepEqual(cardProblems(ROOT), [], 'the share card does not reach its tokens');
});

test('the guard has teeth: a broken stylesheet link, a missing link, and a token nobody declares are each reported', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'brand-card-'));
  try {
    for (const rel of [TOKENS_FILE, OG_SOURCE]) { mkdirSync(dirname(join(tmp, rel)), { recursive: true }); cpSync(abs(rel), join(tmp, rel)); }
    const [cardPath, tokensPath] = [join(tmp, OG_SOURCE), join(tmp, TOKENS_FILE)];
    const [card, tokens] = [readFileSync(cardPath, 'utf8'), readFileSync(tokensPath, 'utf8')];
    assert.deepEqual(cardProblems(tmp), [], 'the copy of the card is not clean; the fixture is wrong');

    writeFileSync(cardPath, card.replace(/(<link[^>]*href="[^"]*)tokens\.css/, '$1tokens-moved.css'));
    const broken = cardProblems(tmp);
    assert.ok(broken.some((m) => /tokens-moved\.css, which does not exist/.test(m)) && broken.some((m) => /does not link/.test(m)), `a link to a file that is not there was not reported: ${broken.join(' | ')}`);

    writeFileSync(cardPath, card.replace(/<link[^>]*>/, ''));
    assert.ok(cardProblems(tmp).some((m) => /links no stylesheet/.test(m)), 'a card with no stylesheet link was not reported');

    assert.notEqual(card.replace(/(<link[^>]*href="[^"]*)tokens\.css/, '$1tokens-moved.css'), card, 'the fixture did not move the link');
    writeFileSync(cardPath, card.replace('var(--paper)', 'var(--paperx)'));
    assert.ok(cardProblems(tmp).some((m) => /spends --paperx/.test(m)), 'a token the card spends and nobody declares was not reported');

    // The other end: the token file renames a token the card still spends.
    writeFileSync(cardPath, card);
    writeFileSync(tokensPath, tokens.replaceAll('--faint:', '--faintx:'));
    assert.ok(cardProblems(tmp).some((m) => /spends --faint,/.test(m)), 'a token renamed in the token file was not reported');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('CI runs the brand check, headless, after Chromium is installed', () => {
  const ci = read('.github/workflows/ci.yml');
  const start = ci.indexOf('\n  typecheck-and-test:');
  assert.ok(start > 0, 'ci.yml has no typecheck-and-test job');
  const rest = ci.slice(start + 1);
  const end = rest.search(/\n  [a-z][\w-]*:\n/);
  const job = end === -1 ? rest : rest.slice(0, end);
  const install = job.search(/playwright install --with-deps chromium/);
  const check = job.search(/^\s+run: node scripts\/make-brand-assets\.mjs --check\s*$/m);
  assert.ok(install > 0, 'the job that runs the tests no longer installs Chromium; the brand check has no browser');
  assert.ok(check > install, 'ci.yml does not run `node scripts/make-brand-assets.mjs --check` after installing Chromium in the typecheck-and-test job');
});

test('the site links the favicon and touch icon, and its manifest points at icons that exist', () => {
  for (const rel of ['apps/site/src/layouts/Base.astro', 'apps/site/src/layouts/Landing.astro']) {
    const src = read(rel);
    assert.match(src, /rel="icon" href="\/favicon\.svg"/, `${rel} does not link /favicon.svg`);
    assert.match(src, /rel="apple-touch-icon"[^>]*href="\/apple-touch-icon\.png"/, `${rel} does not link the touch icon`);
  }
  const manifest = JSON.parse(read('apps/site/public/site.webmanifest'));
  assert.ok(manifest.icons.length >= 2, 'the manifest lists fewer than two icons');
  for (const icon of manifest.icons) {
    const rel = `apps/site/public${icon.src}`;
    assert.ok(existsSync(abs(rel)), `the manifest names ${icon.src}, which does not exist`);
    const [w] = pngSize(rel);
    assert.equal(`${w}x${w}`, icon.sizes, `${icon.src} is ${w}px but the manifest says ${icon.sizes}`);
  }
});

/* ------------------------------------------------------------------ the three old logos are gone */

/** Geometry and palette of the three retired drawings, as fragments any copy of them must contain. */
const OLD_LOGO_FRAGMENTS = [
  // the folded-sheet outline (site header and footer, the web favicon, the assistant avatar, the dashboards)
  '5 24 12 5 19 14', 'm5 24 7-19 7 9', '12 5 1 13 6-4',
  // the hexagon holding a cube (the rail glyph, the wait pulse, the empty-state illustrations)
  '27.26 9.5', '4.74 9.5', 'm8 1.5l5.5 3.5', '122.91 49', '134.64 48', '84.2 18.5',
  // the azure studded brick (favicon, icon set, share card) and its source render
  '24 11 37 18.5', '11 18.5 24 26', '#3d93e8', '#0f62c4', '#0a468f', 'studpilot-mark-source',
];
/** The old files: the render the brick came from. (The icons and favicon were regenerated in place.) */
const OLD_LOGO_FILES = ['apps/site/brand/studpilot-mark-source.png'];

const findOldLogo = (src) => OLD_LOGO_FRAGMENTS.filter((f) => src.toLowerCase().includes(f));

test('no file of the three old logos exists', () => {
  for (const rel of OLD_LOGO_FILES) assert.ok(!existsSync(abs(rel)), `${rel} is an old logo file and must stay deleted`);
});

test('no geometry, palette or source name of the three old logos appears anywhere in the tree', () => {
  const files = walkText(['apps', 'packages', 'scripts', 'tools', 'infra', 'tests', '.github'], {
    skipPaths: ['packages/asset-library', 'packages/corpus', 'packages/training', 'packages/owner-corpus', 'packages/design/src/web'],
  });
  assert.ok(files.length > 1500, `only ${files.length} files scanned; the walk has drifted`);
  const hits = [];
  for (const f of files) for (const frag of findOldLogo(readText(f))) hits.push(`${f.rel}: ${frag}`);
  assert.deepEqual(hits, [], `an old logo drawing is still in the tree:\n  ${hits.join('\n  ')}`);
});

test('the guard has teeth: it finds each old logo in the form it shipped', () => {
  const folded = '<path d="M5 24 12 5 19 14 27 8 21 27 13 18Z"/><path d="m5 24 7-19 7 9 8-6-6 19-8-9-8 6Z"/>';
  const hexagon = '<path d="M16 3 L27.26 9.5 L27.26 22.5 L16 29 L4.74 22.5 L4.74 9.5 Z"/>';
  const brick = '<polygon points="24 11 37 18.5 24 26 11 18.5" fill="#3D93E8"/>';
  for (const [name, src] of Object.entries({ folded, hexagon, brick })) assert.ok(findOldLogo(src).length > 0, `the ${name} logo is not detected`);
  assert.deepEqual(findOldLogo(MARK), [], 'the new mark must not trip the old-logo guard');
});
