#!/usr/bin/env node
// Writes src/tools/generated.ts: the Studio agent's tools, taken from the worker's own definitions
// (apps/worker/src/tools.ts) so a name, a description or an argument can never differ between the two.
//
//   node apps/studio/scripts/gen-tools.mjs          write the file
//   node apps/studio/scripts/gen-tools.mjs --check  exit 1 when the committed file is stale
//
// Which tools: STUDIO_TOOLS in apps/worker/src/studio-surface.ts (the gate serves exactly that list).
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WORKER = join(HERE, '..', '..', 'worker');
const OUT = join(HERE, '..', 'src', 'tools', 'generated.ts');

const tmp = mkdtempSync(join(tmpdir(), 'studio-tools-'));
try {
  const entry = join(tmp, 'entry.ts');
  writeFileSync(entry, `export { toolDefs } from ${JSON.stringify(join(WORKER, 'src', 'tools.ts'))};\nexport { STUDIO_TOOLS, STUDIO_WRITE_TOOLS } from ${JSON.stringify(join(WORKER, 'src', 'studio-surface.ts'))};\n`);
  const bundle = join(tmp, 'bundle.mjs');
  execFileSync(join(WORKER, 'node_modules', '.bin', 'esbuild'), [entry, '--bundle', '--format=esm', '--target=es2022', '--platform=node', `--outfile=${bundle}`], { cwd: WORKER, stdio: 'pipe' });
  const { toolDefs, STUDIO_TOOLS, STUDIO_WRITE_TOOLS } = await import(pathToFileURL(bundle).href);

  const defs = toolDefs(true);
  const byName = new Map(defs.map((d) => [d.name, d]));
  const missing = STUDIO_TOOLS.filter((n) => !byName.has(n));
  if (missing.length) throw new Error(`STUDIO_TOOLS names tools the worker does not define: ${missing.join(', ')}`);

  const src = render(STUDIO_TOOLS.map((n) => byName.get(n)), new Set(STUDIO_WRITE_TOOLS));
  if (process.argv.includes('--check')) {
    const now = readFileSync(OUT, 'utf8');
    if (now !== src) {
      console.error('apps/studio/src/tools/generated.ts is stale: run node apps/studio/scripts/gen-tools.mjs');
      process.exit(1);
    }
    console.log(`generated.ts is current (${STUDIO_TOOLS.length} tools)`);
  } else {
    writeFileSync(OUT, src);
    console.log(`wrote ${OUT} (${STUDIO_TOOLS.length} tools)`);
  }
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

/** JSON Schema (the subset tools.ts uses) to a valibot expression. */
function valibot(s, required = true) {
  let e;
  const pipe = [];
  if (s.description) pipe.push(`v.description(${JSON.stringify(s.description)})`);
  switch (s.type) {
    case 'object': {
      const props = Object.entries(s.properties ?? {});
      if (!props.length) {
        e = 'v.record(v.string(), v.unknown())';
      } else {
        const req = new Set(s.required ?? []);
        e = `v.object({ ${props.map(([k, p]) => `${JSON.stringify(k)}: ${valibot(p, req.has(k))}`).join(', ')} })`;
      }
      break;
    }
    case 'array':
      e = `v.array(${s.items ? valibot(s.items) : 'v.unknown()'})`;
      if (s.minItems !== undefined) pipe.unshift(`v.minLength(${s.minItems})`);
      if (s.maxItems !== undefined) pipe.unshift(`v.maxLength(${s.maxItems})`);
      break;
    case 'string':
      e = s.enum ? `v.picklist(${JSON.stringify(s.enum)})` : 'v.string()';
      if (s.maxLength !== undefined) pipe.unshift(`v.maxLength(${s.maxLength})`);
      break;
    case 'number':
    case 'integer':
      e = 'v.number()';
      if (s.type === 'integer') pipe.unshift('v.integer()');
      if (s.minimum !== undefined) pipe.unshift(`v.minValue(${s.minimum})`);
      if (s.maximum !== undefined) pipe.unshift(`v.maxValue(${s.maximum})`);
      break;
    case 'boolean':
      e = 'v.boolean()';
      break;
    default:
      e = 'v.unknown()';
  }
  if (pipe.length) e = `v.pipe(${[e, ...pipe].join(', ')})`;
  return required ? e : `v.optional(${e})`;
}

function render(defs, writes) {
  const items = defs.map((d) => {
    const params = d.parameters ?? { type: 'object', properties: {} };
    const input = Object.keys(params.properties ?? {}).length ? `\n    input: ${valibot({ ...params, description: undefined })},` : '';
    return `  {\n    name: ${JSON.stringify(d.name)},\n    writes: ${writes.has(d.name)},\n    description: ${JSON.stringify(d.description)},${input}\n  },`;
  });
  return `// GENERATED by apps/studio/scripts/gen-tools.mjs from apps/worker/src/tools.ts. Do not edit by hand.
import * as v from 'valibot';

export interface StudioToolSpec {
  name: string;
  /** Changes the place: the gate takes a checkpoint first, so the change can be undone. */
  writes: boolean;
  description: string;
  input?: v.ObjectSchema<v.ObjectEntries, undefined>;
}

export const STUDIO_TOOL_SPECS: readonly StudioToolSpec[] = [
${items.join('\n')}
];
`;
}
