#!/usr/bin/env node
// Compiles the Creator Store UI harvest (../sources/ui-creator-store.jsonl.gz, written by
// harvest-creator-store-ui.mjs) into index.json beside this file: the compact table that
// apps/worker/src/ui-store-search.ts imports into the Worker bundle, the way fx-library.ts imports
// sfx/index.json. Nothing is served from storage: every row is an Image asset id that
// ImageLabel.Image takes as rbxassetid://<imageId>, so there are no bytes to host.
//
// A row is [imageId, decalId - imageId, name, verified 0/1, upVotes, kind#, genreMask, keyword#s].
// Kinds, genres and search keywords are interned into tables so the rows stay short. Creator names
// stay in the gz harvest only: 36k of them would add half a megabyte to the Worker bundle for a
// field no search uses (the Creator Store page of each hit names its creator).
// Keywords are kept only when they add words the name does not already have, at most three a row.
//
//   node packages/asset-library/ui-store/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, '..', 'sources', 'ui-creator-store.jsonl.gz');
const OUT = join(HERE, 'index.json');

export const KINDS = ['icon', 'button', 'frame', 'bar', 'background', 'border', 'badge', 'emoji', 'text', 'cursor'];
export const GENRES = ['Simulator/Tycoon', 'Obby', 'Horror/Adventure', 'Shooter/Fighting', 'City/Roleplay'];
const tokens = (s) => String(s ?? '').replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);

export function build(rows) {
  const keywords = [];
  const keywordIx = new Map();
  const intern = (list, ix, v) => { if (!ix.has(v)) { ix.set(v, list.length); list.push(v); } return ix.get(v); };
  const out = [];
  for (const r of rows) {
    if (!Number.isSafeInteger(r.imageId) || !Number.isSafeInteger(r.decalId) || !r.name) continue;
    const kind = KINDS.indexOf(r.kind);
    let mask = 0;
    for (const g of r.genres ?? []) { const i = GENRES.indexOf(g); if (i >= 0) mask |= 1 << i; }
    const nameTokens = new Set(tokens(r.name));
    const extra = [];
    for (const kw of r.keywords ?? []) {
      if (extra.length >= 3) break;
      if (tokens(kw).some((t) => !nameTokens.has(t))) extra.push(intern(keywords, keywordIx, kw));
    }
    out.push([
      r.imageId,
      r.decalId - r.imageId,
      r.name.replace(/\s+/g, ' ').slice(0, 80),
      r.verifiedCreator ? 1 : 0,
      Math.max(0, r.upVotes | 0),
      kind < 0 ? 0 : kind,
      mask,
      extra,
    ]);
  }
  out.sort((a, b) => a[0] - b[0]);
  return {
    about: 'Free Roblox Creator Store decals resolved to their Image asset ids (ImageLabel.Image = rbxassetid://<imageId>). Generated by packages/asset-library/ui-store/build.mjs from harvest-creator-store-ui.mjs; do not edit by hand.',
    licence: 'Roblox-free (Creator Store free asset, usable in any experience by id)',
    count: out.length,
    columns: ['imageId', 'decalOffset', 'name', 'verified', 'upVotes', 'kind', 'genreMask', 'keywords'],
    kinds: KINDS,
    genres: GENRES,
    keywords,
    rows: out,
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const rows = gunzipSync(readFileSync(SRC)).toString('utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
  const index = build(rows);
  const text = JSON.stringify(index);
  writeFileSync(OUT, text + '\n');
  console.log(`ui-store: ${index.count} rows, ${index.keywords.length} keywords, ${(text.length / 1e6).toFixed(2)} MB`);
}
