#!/usr/bin/env node
// Bundles packages/skills/<name>/SKILL.md (+ references/*.md) into apps/studio/src/skills.generated.ts after
// validating each skill against the agentskills.io spec.
//
//   node scripts/gen-skills.mjs          write the file
//   node scripts/gen-skills.mjs --check  exit 1 when the committed file is stale or a skill is invalid
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_DIR = join(ROOT, 'packages', 'skills');
const OUT = join(ROOT, 'apps', 'studio', 'src', 'skills.generated.ts');
const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const MAX_DESCRIPTION = 1024;
const MAX_BODY_LINES = 350;

export function parseSkill(text, folder) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text.replace(/\r\n/g, '\n'));
  if (!m) throw new Error(`${folder}/SKILL.md: missing YAML frontmatter`);
  const meta = {};
  for (const line of m[1].split('\n')) {
    const kv = /^([a-z][a-z0-9-]*):\s*(.*)$/.exec(line);
    if (!kv) throw new Error(`${folder}/SKILL.md: unsupported frontmatter line: ${line}`);
    meta[kv[1]] = kv[2].replace(/^(['"])(.*)\1$/, '$2').trim();
  }
  const errors = [];
  const { name = '', description = '' } = meta;
  if (!NAME_RE.test(name) || name.length > 64) errors.push(`name "${name}" must be 1-64 lowercase letters, digits and single hyphens`);
  if (name !== folder) errors.push(`name "${name}" must equal its folder "${folder}"`);
  if (!description) errors.push('description is required');
  if (description.length > MAX_DESCRIPTION) errors.push(`description is ${description.length} chars (max ${MAX_DESCRIPTION})`);
  if (errors.length) throw new Error(`${folder}/SKILL.md: ${errors.join('; ')}`);
  return { name, description, body: m[2].trim() + '\n' };
}

export function collect() {
  const skills = [];
  const warnings = [];
  for (const folder of readdirSync(SKILLS_DIR).sort()) {
    const dir = join(SKILLS_DIR, folder);
    if (!statSync(dir).isDirectory()) continue;
    const skill = parseSkill(readFileSync(join(dir, 'SKILL.md'), 'utf8'), folder);
    const lines = skill.body.split('\n').length;
    if (lines > MAX_BODY_LINES) warnings.push(`${folder}: body is ${lines} lines (aim for <= ${MAX_BODY_LINES}; move depth to references/)`);
    const files = {};
    const refs = join(dir, 'references');
    if (existsSync(refs)) {
      for (const f of readdirSync(refs).sort()) {
        if (!f.endsWith('.md')) continue;
        files[`references/${f}`] = readFileSync(join(refs, f), 'utf8').replace(/\r\n/g, '\n');
      }
    }
    skills.push({ ...skill, files });
  }
  return { skills, warnings };
}

export function render(skills) {
  return `// Generated by scripts/gen-skills.mjs from packages/skills. Do not edit by hand.\n` +
    `export interface Skill { name: string; description: string; body: string; files: Record<string, string> }\n\n` +
    `export const SKILLS: Skill[] = ${JSON.stringify(skills, null, 2)};\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { skills, warnings } = collect();
  for (const w of warnings) console.warn(`warning: ${w}`);
  const src = render(skills);
  const indexTokens = Math.round(skills.reduce((n, s) => n + s.name.length + s.description.length, 0) / 4);
  if (process.argv.includes('--check')) {
    const now = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (now !== src) {
      console.error('apps/studio/src/skills.generated.ts is stale: run node scripts/gen-skills.mjs');
      process.exit(1);
    }
    console.log(`skills.generated.ts is current (${skills.length} skills, index ~${indexTokens} tokens)`);
  } else {
    writeFileSync(OUT, src);
    console.log(`wrote ${OUT} (${skills.length} skills, index ~${indexTokens} tokens)`);
  }
}
