#!/usr/bin/env node
// Validates packages/blocks/<kind>/<id>/ (the format in packages/blocks/README.md) and compiles every block into
// apps/worker/src/blocks.generated.ts, so the worker ships the exact reviewed recipes and sources.
// `node scripts/gen-blocks.mjs --check` exits 1 when the generated file is stale or a block is invalid.
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'packages', 'blocks');
const OUT = join(ROOT, 'apps', 'worker', 'src', 'blocks.generated.ts');
const ICONS_OUT = join(ROOT, 'apps', 'worker', 'src', 'studkit-icons.generated.ts');

/** The kit's icon names (assets/glyphs.json) with the vetted image of each that has one (assets/icons.json). */
export function renderIcons(dir = DIR) {
  const glyphs = JSON.parse(readFileSync(join(dir, 'assets', 'glyphs.json'), 'utf8')).glyphs;
  const packFile = join(dir, 'assets', 'icons.json');
  const pack = existsSync(packFile) ? JSON.parse(readFileSync(packFile, 'utf8')).icons ?? [] : [];
  const icons = {};
  for (const [name, glyph] of Object.entries(glyphs)) icons[name] = { glyph };
  for (const p of pack) {
    if (!icons[p.name]) throw new Error(`assets/icons.json names ${p.name}, which glyphs.json does not list`);
    if (!/^rbxassetid:\/\/\d{1,20}$/.test(p.imageId)) throw new Error(`assets/icons.json: ${p.name} has no image id`);
    icons[p.name].image = p.imageId;
  }
  return '// GENERATED by scripts/gen-blocks.mjs from packages/blocks/assets. Do not edit.\n' +
    `export const ICONS: Record<string, { glyph: string; image?: string }> = ${JSON.stringify(icons)};\n` +
    `export const ICON_NAMES: string[] = ${JSON.stringify(Object.keys(icons))};\n`;
}

export const KINDS = ['ui', 'system', 'prop', 'zone', 'fx', 'lighting'];
const OPS = ['create_instances', 'set_props', 'edit_script', 'clone_instances'];
const CHECKS = { exists: ['path'], prop: ['path', 'prop', 'equals'], script_has: ['path', 'contains'], play_clean: [] };
const SCHEMA_KEYS = new Set(['type', 'enum', 'minimum', 'maximum', 'minLength', 'maxLength', 'pattern', 'items', 'minItems', 'maxItems', 'properties', 'required', 'additionalProperties', 'default', 'description']);
const TYPES = new Set(['string', 'number', 'integer', 'boolean', 'array', 'object']);
const PALETTE = JSON.parse(readFileSync(join(DIR, 'palette.json'), 'utf8'));
const SHADES = Object.keys(Object.values(PALETTE)[0]);
const SLOT = /\{\{([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*){0,2})\}\}/g;

const json = (file) => JSON.parse(readFileSync(file, 'utf8'));
const dirs = (p) => readdirSync(p, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort();

function checkSchema(where, schema, problems, asItems = false) {
  for (const key of Object.keys(schema)) if (!SCHEMA_KEYS.has(key)) problems.push(`${where}: "${key}" is outside the supported schema keywords`);
  if (!TYPES.has(schema.type)) problems.push(`${where}: type must be one of ${[...TYPES].join(', ')}`);
  if (schema.type === 'array') {
    if (!schema.items || typeof schema.items !== 'object') problems.push(`${where}: an array needs items`);
    else checkSchema(`${where}.items`, schema.items, problems, true);
  }
  if (schema.type === 'object') {
    // An object is one entry of a list (`each`); its fields are plain values.
    if (!asItems) problems.push(`${where}: an object is allowed only as the items of a list`);
    if (schema.additionalProperties !== false || typeof schema.properties !== 'object') problems.push(`${where}: an object needs properties and additionalProperties: false`);
    for (const [k, sub] of Object.entries(schema.properties ?? {})) {
      checkSchema(`${where}.${k}`, sub, problems);
      if (sub.type === 'array' || sub.type === 'object') problems.push(`${where}.${k}: a list entry's fields are plain values`);
    }
    for (const r of schema.required ?? []) if (!(r in (schema.properties ?? {}))) problems.push(`${where}: required names ${r}, not a field`);
  }
}

/**
 * Every slot in a recipe step that does not resolve: a top-level slot must be a parameter; `{{item.<field>}}` and
 * `{{index}}` only inside an entry repeated with `"each": "<list parameter>"`, and the field must be one the list's
 * entries have.
 */
export function badSlots(value, props, item = null, out = []) {
  if (typeof value === 'string') {
    for (const m of value.matchAll(SLOT)) {
      const [head, field, shade] = m[1].split('.');
      // `{{accent.top}}`: a colour parameter (an enum of palette names) read as one of its shades.
      const colour = (schema, s) => SHADES.includes(s) && schema?.enum?.length && schema.enum.every((c) => c in PALETTE);
      if (item && head === 'index' && field === undefined) continue;
      if (item && head === 'item') {
        const sub = item.properties?.[field];
        if (field === undefined ? item.type === 'object' : !sub || (shade !== undefined && !colour(sub, shade))) out.push(m[1]);
        continue;
      }
      if (!(head in props) || shade !== undefined) { out.push(m[1]); continue; }
      if (field !== undefined && !colour(props[head], field)) out.push(m[1]);
    }
  } else if (Array.isArray(value)) {
    for (const v of value) {
      if (v && typeof v === 'object' && typeof v.each === 'string') {
        const list = props[v.each];
        if (list?.type !== 'array') { out.push(`each ${v.each}`); continue; }
        badSlots(Object.fromEntries(Object.entries(v).filter(([k]) => k !== 'each')), props, list.items, out);
      } else badSlots(v, props, item, out);
    }
  } else if (value && typeof value === 'object') Object.values(value).forEach((v) => badSlots(v, props, item, out));
  return out;
}

export function loadBlocks(dir = DIR) {
  const blocks = {};
  const problems = [];
  for (const kind of dirs(dir).filter((d) => d !== 'proof')) {
    if (kind === 'assets') continue;
    if (!KINDS.includes(kind)) { problems.push(`${kind}/: not a block kind (${KINDS.join(', ')})`); continue; }
    for (const id of dirs(join(dir, kind))) {
      const at = join(dir, kind, id);
      const where = `${kind}/${id}`;
      const need = ['block.json', 'recipe.json', 'checks.json', 'hint.md', 'proof'];
      const missing = need.filter((f) => !existsSync(join(at, f)));
      if (missing.length) { problems.push(`${where}: missing ${missing.join(', ')}`); continue; }
      const block = json(join(at, 'block.json'));
      const recipe = json(join(at, 'recipe.json'));
      const checks = json(join(at, 'checks.json'));
      const hint = readFileSync(join(at, 'hint.md'), 'utf8').trim();

      if (block.id !== id) problems.push(`${where}: block.json id is ${block.id}`);
      if (block.kind !== kind) problems.push(`${where}: block.json kind is ${block.kind}`);
      if (typeof block.summary !== 'string' || !block.summary || block.summary.length > 120) problems.push(`${where}: summary must be one line of 1-120 characters`);
      if (hint.length > 600) problems.push(`${where}: hint.md is ${hint.length} characters (at most 600)`);
      if (!readdirSync(join(at, 'proof')).some((f) => f.endsWith('.luau'))) problems.push(`${where}: proof/ has no .luau test`);
      for (const list of ['provides', 'depends']) if (!Array.isArray(block[list]) || block[list].some((v) => typeof v !== 'string')) problems.push(`${where}: ${list} must be a list of strings`);

      const params = block.params ?? {};
      if (params.type !== 'object' || params.additionalProperties !== false || typeof params.properties !== 'object') {
        problems.push(`${where}: params must be { type: "object", additionalProperties: false, properties }`);
      }
      const names = new Set(Object.keys(params.properties ?? {}));
      for (const [name, schema] of Object.entries(params.properties ?? {})) {
        checkSchema(`${where} params.${name}`, schema, problems);
        if (!('default' in schema)) problems.push(`${where} params.${name}: needs a default`);
      }

      const sources = {};
      if (existsSync(join(at, 'src'))) {
        for (const f of readdirSync(join(at, 'src')).sort()) if (f.endsWith('.luau')) sources[`src/${f}`] = readFileSync(join(at, 'src', f), 'utf8');
      }
      const stepIds = new Set();
      for (const [i, step] of (recipe.steps ?? []).entries()) {
        const s = `${where} step ${step.id ?? i}`;
        if (typeof step.id !== 'string' || stepIds.has(step.id)) problems.push(`${s}: needs a unique id`);
        stepIds.add(step.id);
        if (!OPS.includes(step.op)) problems.push(`${s}: op ${step.op} is not one of ${OPS.join(', ')}`);
        if (step.op === 'edit_script') {
          if (!sources[step.file]) problems.push(`${s}: file ${step.file} is not in src/`);
          else for (const slot of badSlots(sources[step.file], params.properties ?? {})) problems.push(`${s}: ${step.file} names {{${slot}}}, not a parameter`);
          if (!['Script', 'LocalScript', 'ModuleScript'].includes(step.create?.className)) problems.push(`${s}: create.className must be a script class`);
        }
        for (const slot of badSlots(step, params.properties ?? {})) problems.push(`${s}: {{${slot}}} is not a parameter${slot.includes('.') || slot === 'index' ? ' (item fields and index exist only inside an "each" entry)' : ''}`);
      }
      if (!stepIds.size) problems.push(`${where}: recipe has no steps`);

      const checkIds = new Set();
      for (const c of Array.isArray(checks) ? checks : []) {
        const s = `${where} check ${c.id}`;
        if (typeof c.id !== 'string' || checkIds.has(c.id)) problems.push(`${s}: needs a unique id`);
        checkIds.add(c.id);
        if (!CHECKS[c.kind]) { problems.push(`${s}: kind ${c.kind} is not one of ${Object.keys(CHECKS).join(', ')}`); continue; }
        for (const f of CHECKS[c.kind]) if (!(f in c)) problems.push(`${s}: a ${c.kind} check needs ${f}`);
        if (typeof c.describes !== 'string' || !c.describes) problems.push(`${s}: needs describes`);
        if (c.after !== undefined && !stepIds.has(c.after)) problems.push(`${s}: after names no step`);
        if (c.kind === 'play_clean' && c.after !== undefined) problems.push(`${s}: play_clean always runs last`);
        if (c.param !== undefined && !names.has(c.param)) problems.push(`${s}: param ${c.param} is not a parameter`);
        for (const slot of badSlots(c, params.properties ?? {})) problems.push(`${s}: {{${slot}}} is not a parameter`);
      }
      if (!checkIds.size) problems.push(`${where}: checks.json has no checks`);
      if (blocks[id]) problems.push(`${where}: id ${id} is used twice`);
      blocks[id] = { block, recipe, checks, hint, sources };
    }
  }
  for (const [id, b] of Object.entries(blocks)) {
    for (const dep of b.block.depends ?? []) if (!blocks[dep]) problems.push(`${b.block.kind}/${id}: depends on ${dep}, which is not a block`);
  }
  // A dependency cycle would leave the interpreter no order to run in.
  const state = {};
  const visit = (id, trail) => {
    if (state[id] === 'done' || !blocks[id]) return;
    if (state[id] === 'open') { problems.push(`dependency cycle: ${[...trail, id].join(' -> ')}`); return; }
    state[id] = 'open';
    for (const dep of blocks[id].block.depends ?? []) visit(dep, [...trail, id]);
    state[id] = 'done';
  };
  Object.keys(blocks).forEach((id) => visit(id, []));
  return { blocks, problems };
}

export function render(dir = DIR) {
  const { blocks, problems } = loadBlocks(dir);
  if (problems.length) throw new Error(`invalid blocks:\n  ${problems.join('\n  ')}`);
  return '// GENERATED by scripts/gen-blocks.mjs from packages/blocks. Do not edit.\n' +
    '/* eslint-disable */\n' +
    "import type { Block } from './block-types';\n" +
    `export const PALETTE: Record<string, Record<string, string>> = ${JSON.stringify(PALETTE)};\n` +
    `export const BLOCKS: Record<string, Block> = ${JSON.stringify(blocks)};\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  let text;
  try { text = render(); } catch (e) { console.error(e.message); process.exit(1); }
  const icons = renderIcons();
  if (process.argv.includes('--check')) {
    const current = existsSync(OUT) && statSync(OUT).isFile() ? readFileSync(OUT, 'utf8') : '';
    if (current !== text) { console.error('blocks.generated.ts is stale: run node scripts/gen-blocks.mjs'); process.exit(1); }
    if ((existsSync(ICONS_OUT) ? readFileSync(ICONS_OUT, 'utf8') : '') !== icons) { console.error('studkit-icons.generated.ts is stale: run node scripts/gen-blocks.mjs'); process.exit(1); }
    console.log('blocks.generated.ts and studkit-icons.generated.ts are current');
  } else {
    writeFileSync(OUT, text);
    writeFileSync(ICONS_OUT, icons);
    console.log(`wrote ${OUT} (${text.length} bytes) and the icon table`);
  }
}
